### ISSUE TITLE
How to access methods in inner class

### ISSUE THREAD

**Issue by compilerNayan** [rovo89/XposedBridge#10]
I dont know if this is the right place to post this question. But I am trying to hook a method 
            findAndHookMethod("com.android.keyguard.KeyguardPatternView.UnlockPatternListener", lpparam.classLoader, "onPatternDetected", new XC_MethodHook()

where UnlockPatternListener is a nested class(inner class) and it has a method called onPatternDetected. The inner class is private. I am unable to hook this method. Can you tell me the way to do it?

**Comment by rovo89** [comment]
Which error message do you get? Maybe you need to write it as "KeyguardPatternView$UnlockPatternListener". Also, your hook is for a method without any parameters. If it has parameters, you need mentioned them after the method name.

In general, please post such questions on XDA. Many people can help there, here it's just me.

**Comment by compilerNayan** [comment]
Thanks for the help
public void onPatternDetected(List<LockPatternView.Cell> pattern)
is the method that I am trying to hook. 

and LockPatternView is imported from
import com.android.internal.widget.LockPatternView;

I tried importing LockPatternView in my code but I cant find that so how would it be possible to get reference LockPatternView (or any other class which is not listed and I need to hook the method). In the red clock example  the clock came from "com.android.systemui.statusbar.policy.Clock" but as it was inheriting from textview you had used textview reference. But if I had to use the class Clock itself then how should I go about it. Do I need to add any jar files for it, if so where to get those jar files?

Also I could not get an example of how to hook a method which has parameters in the development tutorial. Can you just show me an simple example. And does the return type matter? I mean can I change the return value of a function by hooking it.

PS : Please bear with me as I am new to java and android and have coded only in C++. Thanks a lot for the help. And thanks for the great framework :)

**Comment by compilerNayan** [comment]
I hooked method 
            findAndHookMethod("com.android.keyguard.KeyguardPatternView$UnlockPatternListener", lpparam.classLoader, "onPatternDetected", "List<LockPatternView.Cell> pattern", new XC_MethodHook() { .........code......... }

I got an error saying ClassNotFoundException List<LockPatternView.Cell> pattern

I dont have reference to LockPatternView as I said. Can you please help me out with this.

**Comment by rovo89** [comment]
I suggest you have a look at existing projects, quite a few are open source. Just one example: https://github.com/rovo89/XposedAppSettings/blob/master/src/de/robv/android/xposed/mods/appsettings/XposedMod.java

**Comment by compilerNayan** [comment]
Hi
Thanks for the link. It was indeed helpful. But I have only seen methods which are available for normal android project being hooked. I am still unable to hook a method "onPatternDetected" in the class "com.android.keyguard.KeyguardPatternView$UnlockPatternListener".
Actually I can hook the method but I am unable to import the library classes. 
For example if I try to get "param.thisObject" I cannot typecast it into appropriate object as I am unable to import "com.android.keyguard.KeyguardPatternView$UnlockPatternListener"

Is there any way to do this?

**Comment by compilerNayan** [comment]
Ok I found a way to find the class reference using following code
Class<?> classKeyLock = findClass("com.android.keyguard.KeyguardPatternView$UnlockPatternListener", null);  
Class<?> classCell = findClass("com.android.internal.widget.LockPatternView.Cell", null);

But my function onPatternDetected takes a List. I don't know how to tell xposed framework that it takes a list. I have a class reference for classCell. But it takes List<classCell>. Simply passing as List<classCell is not helping me as findAndHookMethod accepts a .class and list is not having any .class attribute.

Also I found a way to search for class reference as I showed before but how to access those class member variables and function as we still dont have any skelton of the class.

**Comment by rovo89** [comment]
This is really not the right place for "how to start with module development". As mentioned before, please have a look at modules like App Settings to understand how modules work: https://github.com/rovo89/XposedAppSettings

**Comment by compilerNayan** [comment]
Hi
Thanks for the help. And those modules are really helpful. But I would like to know if there is any forum where I can ask xposed development related questions.

**Comment by rovo89** [comment]
Seems like you have found it. ;)

**Comment by compilerNayan** [comment]
;) :)
