### ISSUE TITLE
Cannot hook <init> function

### ISSUE THREAD

**Issue by mingwayzhang** [rovo89/XposedBridge#100]
This might be a simple question instead of a real issue. I recently tried to write an Xposed module which hooks "android.content.Intent.<init>". Looks like it does not work (I don't see anything printed out to logcat on beforeHookedMethod and afterHookedMethod). May I know why and how to do that? Other functions such as "getExtra" work. Thanks.

**Comment by rovo89** [comment]
These are constructors, Xposed has separate methods to hook them.
