### ISSUE TITLE
Update Tutorial: "Disable Instant Run in Android Studio"

### ISSUE THREAD

**Issue by nareddyt** [rovo89/XposedBridge#101]
I just started developing Xposed modules and have been following the tutorial. For the past day, I kept getting a java.lang.ClassNotFoundException whenever I ran my module. After doing hours of research, I realized that it has to do with Android Studio's Instant Run feature. Apparently Xposed does not work too well with this, and as soon as I disabled Instant Run, the module worked perfectly.

Here is a better description of the problem I was facing: http://forum.xda-developers.com/xposed/development-question-to-development-t3382261

Apparently other's have noticed it too: http://forum.xda-developers.com/xposed/xposed-problems-android-studios-instant-t3357754

I understand that there probably isn't much you can do about getting Xposed to work with Instant Run. However, could you update the tutorial to tell users to turn it off? I spent upwards of 4 hours just staring at my code and googling around until I found the XDA thread above. Updating the tutorial would make the process a lot less frustrating for new developers :)

**Comment by rovo89** [comment]
Thanks! I'll try to find out more about how Instant Run works and then update the tutorial if necessary.

**Comment by rovo89** [comment]
I have added some instructions here:
https://github.com/rovo89/XposedBridge/wiki/Using-the-Xposed-Framework-API

Also, Xposed v85 will try to detect APKs produced for Instant Run (they indeed look different) and will print a better error message in that case.
