### ISSUE TITLE
XSharedPreferences doesn't work

### ISSUE THREAD

**Issue by theblixguy** [rovo89/XposedBridge#102]
I am using XSharedPreferences to read my app's preferences in my module (part of my app), but things like getBoolean() return false even if the preference value is actually true.

I call it like:

`XSharedPreferences prefs = new XSharedPreferences("com.app.packagename");` in `initZygote` (also tried calling it in `handleLoadPackage`)

and in `handleLoadPackage`, I call:

`XposedBridge.log("testPref: " + prefs.getBoolean("testPref", false));`

just to test the preference, and it prints `false` always, even if testPref is `true` in my app.

Just to be sure, I added `prefs.makeWorldReadable()` in `initZygote` but that didn't help as well.

I am on Galaxy S7 edge running Xposed v85.1 and Marshmallow 6.0.1.

**Comment by rovo89** [comment]
Is the preferences file actually world-readable? The call in Zygote doesn't seem to work anymore in some cases, and you always needed to add some logic to your UI to make the files readable.

**Comment by theblixguy** [comment]
Actually no, the permission on the preference file is 660. I tried adding `getPreferenceManager.setSharedPreferencesMode(Context.MODE_WORLD_READABLE()` in my settings activity but it didn't make any difference

**Comment by theblixguy** [comment]
Here's my Xposed module code: https://github.com/theblixguy/ForceDoze/blob/master/app/src/main/java/com/suyashsrijan/forcedoze/XposedModule.java
Here's my SettingsActivity: https://github.com/theblixguy/ForceDoze/blob/master/app/src/main/java/com/suyashsrijan/forcedoze/SettingsActivity.java

I am so confused, I've spent so many hours trying to get it to work, but nothing really works. Manually changing the permission of the file to 664 (via Root Browser), still doesn't help. The value of my preferences are still printed wrong.

**Comment by rovo89** [comment]
Maybe the `getDefaultSharedPreferences()` call causes the restricted permissions. Can you try if removing these calls temporarily results in the correct permissions? If you need them, maybe `preference.getSharedPreferences()`.

**Comment by theblixguy** [comment]
I didn't get you there. Do you mean in my `SettingsActivity`, I replace every instance of `PreferenceManager.getDefaultSharedPreferences(getActivity());` with `getPreferenceManager().getSharedPreferences()`?

**Comment by rovo89** [comment]
As far as I can see, you have these two lines:
https://github.com/theblixguy/ForceDoze/blob/master/app/src/main/java/com/suyashsrijan/forcedoze/SettingsActivity.java#L182
https://github.com/theblixguy/ForceDoze/blob/master/app/src/main/java/com/suyashsrijan/forcedoze/SettingsActivity.java#L256

The second one can probably be commented out for testing as it's just for resetting the preference. Maybe the first one can be commented out as well, but it could anyway be optimized by using the `getSharedPreferences()` of the `preference` that you get as parameter.

Then obviously you need to open your app and change a few settings to check if the permissions are correct.

**Comment by theblixguy** [comment]
Yeah, but I am not trying to modify those two preferences, so the code on those two lines don't ever get called and hence has no effect on the issue I am facing

**Comment by theblixguy** [comment]
I tried putting 

`prefs = new XSharedPreferences("com.suyashsrijan.forcedoze");
prefs.getFile().setReadable(true, false);` in `initZygote` and the Xposed log says **File does not exist**, so I guess that explains why the pref can't be loaded in initZygote, but that kind of sucks because you can't conditionally do something based on preferences at system startup.

EDIT: I tried putting the same code in `handleLoadPackage` and it changes the permission from 660 to 664, but the preference values are still returned as false

**Comment by C3C0** [comment]
Try checking how "shared_prefs" folder permissions look like. I had an issue in the past when shared_prefs folder lost permissions necessary to access files located inside it. So even if prefs file has correct permissions they won't be accessible in case folder permissions are insufficient. I had to make a workaround to manually fix folder permissions every time module UI app opens. I know this is not perfect as it's too late if device boots with folder permissions not being OK but at least things get OK after next reboot.
@rovo89 maybe consider extending XSharedPreferences.makeWorldReadable() to also adjust direct parent folder permissions?
https://github.com/GravityBox/GravityBox/commit/2a96528ec9f51964355d9c699b7b1cbe027d52f5

**Comment by theblixguy** [comment]
I added `XposedBridge.log("Pref size: " + prefs.getAll().size());` in `handleLoadPackage` and it prints `0` for mostly all packages, but `11` for my package. Calling `getPreferenceManager().setSharedPreferencesMode(MODE_WORLD_READABLE);` in my SettingsActivity resets the preference file's permissions to 660. I've removed that line now.

But the problem is, I can only load the preferences when my package is loaded, and then read the preferences, but the package I want to hook can be called before my package and then I won't be able to hook it conditionally depending on the value of my preference

**Comment by rovo89** [comment]
> maybe consider extending XSharedPreferences.makeWorldReadable() to also adjust direct parent folder permissions?

Just checked the implementation and docs again, `makeWorldReadable()` is incompatible with SELinux anyway: http://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html#makeWorldReadable%28%29

**Comment by theblixguy** [comment]
Strange how calling `prefs.getFile().setReadable(true, false)` in `handleLoadPackage` works, but not `makeWorldReadable` (at least in my case)

**Comment by C3C0** [comment]
Ah. Missed this one. I am still using it as my module's code simply propagated from JellyBean up to MM but I actually never had issues with prefs files having wrong permissions as I always make sure to open them with MODE_WORLD_READABLE in my module settings. The only issue I had was with the parent folder permissions as I wrote in my post above. @theblixguy I would definitely suggest you check how permissions of "shared_prefs" folder look like.

**Comment by theblixguy** [comment]
I have fixed the issue I believe, this is my new code:

`@Override public void handleLoadPackage(XC_LoadPackage.LoadPackageParam loadPackageParam) throws Throwable {`

`if (loadPackageParam.packageName.equals("com.suyashsrijan.forcedoze")) {`
 `XposedBridge.log("ForceDozeXposed: Module found");`
`prefs = new XSharedPreferences("com.suyashsrijan.forcedoze");`
`XposedBridge.log("ForceDozeXposed: Pref file readable -> " + prefs.getFile().canRead());`
`if (!prefs.getFile().canRead()) {`
`XposedBridge.log("ForceDozeXposed: Making Pref file readable");`
`prefs.getFile().setReadable(true, false);`
`XposedBridge.log("ForceDozeXposed: Pref file readable -> " + prefs.getFile().canRead());
}`
`XposedBridge.log("ForceDozeXposed: Reloading prefs");`
`prefs.reload();`
`XposedBridge.log("ForceDozeXposed: Populating prefs");`
`usePermanentDoze = prefs.getBoolean("usePermanentDoze", false);`
`useXposedSensorWorkaround = prefs.getBoolean("useXposedSensorWorkaround", false);`
`serviceEnabled = prefs.getBoolean("serviceEnabled", false);`
`XposedBridge.log("ForceDozeXposed: usePermanentDoze: " + usePermanentDoze + ", useXposedSensorWorkaround: " + useXposedSensorWorkaround + ", serviceEnabled: " + serviceEnabled);`
`} else if (loadPackageParam.packageName.equals("android")) {`
`if (useXposedSensorWorkaround && serviceEnabled) {`
`XposedBridge.log("ForceDozeXposed: Hooking AnyMotionDetector");`
`final Class AnyMotionDetector = XposedHelpers.findClass("com.android.server.AnyMotionDetector", loadPackageParam.classLoader);`
`XposedHelpers.findAndHookMethod(AnyMotionDetector, "getStationaryStatus", XC_MethodReplacement.returnConstant(0));`
`XposedHelpers.setStaticLongField(AnyMotionDetector, "ACCELEROMETER_DATA_TIMEOUT_MILLIS", 0);`
`XposedHelpers.setStaticLongField(AnyMotionDetector, "ORIENTATION_MEASUREMENT_DURATION_MILLIS", 0);`
`XposedHelpers.setStaticIntField(AnyMotionDetector, "SAMPLING_INTERVAL_MILLIS", 0);`
`XposedBridge.log("ForceDozeXposed: Hooked AnyMotionDetector");`
`}`
`}`
`}`

Now the problem is, I want to hook `android` and the code for that isn't getting called there, even when the preference values are correctly loaded

**Comment by C3C0** [comment]
I'm not sure this makes sense to me. You are hooking your own package to fix permissions. Hook is executed when user opens your app. You could simply use the same code within onCreate of your Application class.

**Comment by theblixguy** [comment]
Yeah, because trying to read them in `initZygote` doesn't help, and it only returns me the preference if I try to read it when loading my app's package in `handleLoadPackage`.

My problem is, I want to hook a class in the [Android server package](https://android.googlesource.com/platform/frameworks/base/+/android-6.0.1_r43/services/core/java/com/android/server/AnyMotionDetector.java) and my code for hooking is executing fine normally, but after introducing the conditionals (`useXposedSensorWorkaround && serviceEnabled`), it no longer hooks. I believe that's because the value of the preference is by default false and only gets populated when I load the prefs for my package, and the android server package gets loaded before mine does and hence the hook fails.

I'll try what you said and see if it makes a difference, but I think I'll need root?

**Comment by theblixguy** [comment]
Adding `File mFile = new File(Environment.getDataDirectory(), "data/" + "com.suyashsrijan.forcedoze" + "/shared_prefs/" + "com.suyashsrijan.forcedoze_preferences" + ".xml");` and `mFile.setReadable(true, false);` in the Application class's `onCreate()` has no effect @C3C0

**Comment by C3C0** [comment]
One way or another, code you provided above cannot work. You are initializing serviceEnabled and other variables within different process than where you actually use them. You cannot expect them to contain correct value. You have to initialize them within "android" process.

**Comment by theblixguy** [comment]
Calling `chmod 664 /data/data/com.suyashsrijan.forcedoze/shared_prefs/com.suyashsrijan.forcedoze_preferences.xml` using root fixes the permissions, I do that now on my MainActivity.

@C3C0 I did that as well, here's my new code:

`if (loadPackageParam.packageName.equals("android")) {`
`prefs = new XSharedPreferences("com.suyashsrijan.forcedoze");`
`useXposedSensorWorkaround = prefs.getBoolean("useXposedSensorWorkaround", false);`
`serviceEnabled = prefs.getBoolean("serviceEnabled", false);`
`XposedBridge.log("ForceDozeXposed: usePermanentDoze: " + usePermanentDoze + ", useXposedSensorWorkaround: " + useXposedSensorWorkaround + ", serviceEnabled: " + serviceEnabled);`
`if (useXposedSensorWorkaround && serviceEnabled) {`
`XposedBridge.log("ForceDozeXposed: Hooking AnyMotionDetector");`
`final Class AnyMotionDetector = XposedHelpers.findClass("com.android.server.AnyMotionDetector", loadPackageParam.classLoader);`
`XposedHelpers.findAndHookMethod(AnyMotionDetector, "getStationaryStatus", XC_MethodReplacement.returnConstant(0));`
`XposedHelpers.setStaticLongField(AnyMotionDetector, "ACCELEROMETER_DATA_TIMEOUT_MILLIS", 0);`
`XposedHelpers.setStaticLongField(AnyMotionDetector, "ORIENTATION_MEASUREMENT_DURATION_MILLIS", 0);`
`XposedHelpers.setStaticIntField(AnyMotionDetector, "SAMPLING_INTERVAL_MILLIS", 0);`
`XposedBridge.log("ForceDozeXposed: Hooked AnyMotionDetector");`
`}`
`}`

In Xposed log:

`06-04 12:13:21.049 I/Xposed  ( 3005): Loading modules from /data/app/com.suyashsrijan.forcedoze-1/base.apk`
`06-04 12:13:21.949 I/Xposed  ( 3005):   Loading class com.suyashsrijan.forcedoze.XposedModule`
`06-04 12:13:22.699 I/Xposed  ( 3593): ForceDozeXposed: usePermanentDoze: false, useXposedSensorWorkaround: false, serviceEnabled: false`

The values are printed as false, even if they are true. So, loading preferences of an app in another package's context doesn't work. You can only load them when loading your own package in `handlePackageLoad`, at least that's what the case is at the moment.

EDIT: I think preference permissions are getting reset to 660 on reboot.

**Comment by C3C0** [comment]
That's why I suggested you also check not only xml file permission but also shared_prefs FOLDER permissions. What are they?

**Comment by theblixguy** [comment]
RWX (700) @C3C0

chmod'ing the pref file works but the permissions get reset on bootup so I don't think changing the permission of the folder will work if they get reset on bootup. Calling `prefs.getFile().setReadable(true, false);` when loading `android` (in the code above) doesn't work.

**Comment by C3C0** [comment]
You have to do chmod 755 on /data/data/com.suyashsrijan.forcedoze/shared_prefs 
That's exactly an issue I was talking about in my today's initial post

**Comment by theblixguy** [comment]
I can do that, but if permissions get reset on device reboot, then it won't have any effect when trying to load the preference in `handleLoadPackage`, right?

**Comment by C3C0** [comment]
Try it. My experience is that if you set those permissions they will stay like that until some external factor changes them again. Happens rare and I don't know which external factor is responsible for changing those permissions on a folder. That's why I introduced a workaround that can fix if it happens again. Here is a commit: https://github.com/GravityBox/GravityBox/commit/2a96528ec9f51964355d9c699b7b1cbe027d52f5

**Comment by theblixguy** [comment]
Wow, rebooted and the permission for the folder didn't change and and the hook worked.

Calling 

`chmod 664 /data/data/com.suyashsrijan.forcedoze/shared_prefs/com.suyashsrijan.forcedoze_preferences.xml` 

and

`chmod 755 /data/data/com.suyashsrijan.forcedoze/shared_prefs`

fixes the permission issues. You sir are a genius!

**Comment by C3C0** [comment]
Well, far from being a genius, but thanks :) 
Anyway, workaround I was talking about eralier is not perfect as it will not assure permissions are OK during boot when you need them. But it's easier to guide your users to "open module settings and reboot" than to guide them on how to change folder permissions using shell or file manager or whatever method.
Things can still be improved. If my assumption that folder permissions are set to 700 by package manager when app is installed for the first time is correct then it wouldn't be too complicated to code a simple android.intent.action.PACKAGE_ADDED receiver that would fix folder permissions as soon as module gets installed (although I'm not 100% sure if such receiver would kick in also for app that just got installed, but why not?)

**Comment by theblixguy** [comment]
I'm using libsuperuser in my app, so I just call it and pass the chmod command and it works like magic. I call it when people launch my app right now, but I'll be moving the code to the SettingsActivity, so it's executed when users toggle my app (restore permissions to default when the user toggles the setting to OFF and set permissions to 664/755 when the user toggles the setting ON).

**Comment by theblixguy** [comment]
Since this issue is fixed, I am closing it now. If I face any further issues, I'll re-open. Thanks for all your help.
