### ISSUE TITLE
Detecting Xposed at runtime

### ISSUE THREAD

**Issue by mingwayzhang** [rovo89/XposedBridge#103]
Hi,

I am interested in writing an app to identify the existence of Xposed. I have come up with this post:
[http://d3adend.org/blog/?p=589](url)

However, excluding the detection on /proc/pid/maps, I don't think any of the above bypass will work if certain API are hooked (e.g., getStackTrace). So, my question is whether there is any generic method for app developer to detect Xposed even if Xposed plugins hook all method needed to hide itself? Thanks.

**Comment by rovo89** [comment]
I don't think I want to think about answers to that question. Several apps seem to check for Xposed already, and while this might be critical for them to avoid fraud and cheating with malicious modules, it also hits those users who just have Xposed installed with good intentions.

**Comment by liudongmiao** [comment]
@mingwayzhang As xposed framework runs at the user-level, so user can know it directly.

And there is way to disable xposed from user-level.

**Comment by mingwayzhang** [comment]
@liudongmiao Thanks for the feedback. Could you give me some code references? For instance, how to detect xposed using java and/or native code. Appreciate it. (BTW: methods mentioned in the above post could be easily evaded if Xposed is slightly augmented.)

@rovo89 This is not to offend you. My intention is to see what is the maximum that Xposed could do to hide itself and how much it could do for malware analysis.

**Comment by rovo89** [comment]
I don't think these things should be discussed here. It will always be a cat-and-mouse game between those who want to detect and those who want to hide. Promoting ways to detect or even disable Xposed and giving step-by-step instructions will make it easier for app developers to discriminate against Xposed users and will force Xposed devs to come up with new ways to hide, increasing the overall complexity and error rate. So in the end, it would hurt Xposed's progress - exactly the opposite of what this place is meant for.
