### ISSUE TITLE
Change result method in runtime

### ISSUE THREAD

**Issue by luuquangict** [rovo89/XposedBridge#109]
Hello! i'm trying to change value of result of method.
The result of method is changed when i reboot my device, But, the method always return 1 result.
It mean always return "**123456789**" for IMEI in applications check info, or **MyModel** for Model.

Now,  i want to change result of method in runtime, it mean when i change value of field in class **Data** (such as i change: Data.IMEI = "555", Data.MODEL = "new model"), then, when I using any application to check info of device, it will return new value that i was change.
Please help me!!!

This is my code:

``` java
public void handleLoadPackage(final LoadPackageParam lpparam) throws Throwable {
     HookMethod(TelephonyManager.class, "getDeviceId", Data.IMEI);
     XposedHelpers.setStaticObjectField(Build.class, "MODEL", Data.MODEL);
}

private void HookMethod(Class iClass, String methodName, final String value) {
    XposedHelpers.findAndHookMethod(iClass, methodName, new XC_MethodHook() {
        @Override
        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
            param.setResult(value);
            XposedBridge.log("Call Hook: " + value);
        }
    });
}

private class Data
{
    public static String IMEI = "123456789";
    public static String MODEL = "MyModel";
}
```

**Comment by rovo89** [comment]
I don't really understand what you're trying to do.. but I guess you want to build e.g. a UI where you can set these values? Then it probably doesn't work because it's in a different process. Try logging `Process.myPid()` in `afterHookedMethod()` and also in the method where you have `Data.IMEI = "555"`, that will probably confirm it. You'll have to use IPC, e.g. Intents, Content Provider, or simply (X)SharedPreferences for that.

**Comment by luuquangict** [comment]
thanks for reply. 
Sorry about my english is bad.

Yes!!! I want to build a UI and have a button, when i click a button, i will set 

> Data.IMEI = "555"

But it don't work after i set. Please give me an example :(

**Comment by LuuQuangICT** [comment]
it is my skyper: luuquangict
can you add me and support for me :( tks

**Comment by luuquangict** [comment]
in my UI, i used this function in button click event:

`private void change() {
        SharedPreferences pref = getSharedPreferences("refs", MODE_WORLD_READABLE);
        SharedPreferences.Editor edit = pref.edit();

```
    Random rd = new Random();
    edit.putString("id", "DeviceID: " + rd.nextInt(1999));
    edit.commit();
}`
```

And in my Hook class:
` public void handleLoadPackage(final LoadPackageParam lpparam) throws Throwable {

```
    HookMethod(TelephonyManager.class, "getDeviceId");
}


private void HookMethod(Class iClass, String methodName) {
    XposedHelpers.findAndHookMethod(iClass, methodName, new XC_MethodHook() {
        @Override
        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
            XSharedPreferences shareRef = new XSharedPreferences("com.luuquangict.filemanager", "refs");
            String content = shareRef.getString("id", "_defaultValue");
            param.setResult(content);
        }
    });
}`
```

But it alway change to **_defaultValue**

**Comment by luuquangict** [comment]
Oke may be because for me forget to reset my phone :D i'm so sory :) thank you :)
