### ISSUE TITLE
Hook android.app.Activity->startActivity doesn't work always.

### ISSUE THREAD

**Issue by melonaerial** [rovo89/XposedBridge#111]
Hello.
I'm trying to use Xposed Framework for analysis of some malware sample. So I'm setting some hooks, also hook for  android.app.Activity->startActivity call. So I doesn't see in log any information about execution of this part of malware code(this code reconstructed by me from smali-bytecode):

```
File file = new File(Environment.getExternalStorageDirectory(), "no_iconjar.apk");
Uri apkUri = Uri.fromFile(file);
Intent intent = new Intent(Intent.ACTION_VIEW).setDataAndType(apkUri, "application/vnd.android.package-archive");

Log.d("CHECK_LOG", "Installing of app called");
startActivity(intent);
```

I see in log some call of startActivity method, but doen't see for this. I've tried to write my own application with this part of code and with it hook working well. Also I've found some differences in behaviour if I set hooks for javax.crypto.Mac->doFinal and javax.crypto.Cipher->doFinal. I have no idea how it's working, but application makes installation of apk file only if I set that hooks(and sometimes without them, but only sometimes). Have u got any idea what is the reason of such behaviour ? I'm using 2.7 experimental1 Xposed Framework with Android 4.1.2 in Emulator. And XposedBridge v53. Maybe it doesn't support right, then if you advice me how to debug XposedBridge I will be very grateful.

**Comment by rovo89** [comment]
Can you please share more technical details, especially the code you use for hooking these methods and the smali statement with the call that isn't hooked properly? I suspect that you might be hooking just one variant of this method, not all different signatures.

**Comment by melonaerial** [comment]
So here is the code for hooking.
https://gist.github.com/melonaerial/7fdee6a874d505c5db56f85d57064279

As you can see I've set 2 hooks for android.app.Activity->startActivity and for javax.crypto.Cipher->doFInal .

So error.log contains such kind of information(i've copied only connected with startActivity method, because there is a lot of call for javax.crypto.Cipher->doFinal, because this malware uses obfuscation a lot)

```
Droidmon-shell-fehdhuxht.tsgjwcr.vtgk:PID: 1427 UID: 10052 Method: startActivity Class: android.app.Activity signatures number :2 signatures: (android.content.Intent)void (android.content.Intentandroid.os.Bundle)void
Droidmon-shell-fehdhuxht.tsgjwcr.vtgk:PID: 1449 UID: 10052 Method: startActivity Class: android.app.Activity signatures number :2 signatures: (android.content.Intent)void (android.content.Intentandroid.os.Bundle)void
```

Here it is smali-byte code for calling android.app.Activity->startActivity method:

```
    new-instance v0, Landroid/content/Intent;

    const-string v1, "android.intent.action.VIEW"

    invoke-direct {v0, v1}, Landroid/content/Intent;-><init>(Ljava/lang/String;)V

    const/high16 v1, 0x10000000

    invoke-virtual {v0, v1}, Landroid/content/Intent;->setFlags(I)Landroid/content/Intent;

    new-instance v1, Ljava/io/File;

    invoke-static {}, Landroid/os/Environment;->getExternalStorageDirectory()Ljava/io/File;

    move-result-object v2

    const/16 v3, 0xe

    new-array v3, v3, [I

    fill-array-data v3, :array_0

    invoke-static {v3}, Lfehdhuxht/tsgjwcr/vtgk/tools/o;->a([I)Ljava/lang/String;

    move-result-object v3

    invoke-direct {v1, v2, v3}, Ljava/io/File;-><init>(Ljava/io/File;Ljava/lang/String;)V

    invoke-static {v1}, Landroid/net/Uri;->fromFile(Ljava/io/File;)Landroid/net/Uri;

    move-result-object v1

    const-string v2, "application/vnd.android.package-archive"

    invoke-virtual {v0, v1, v2}, Landroid/content/Intent;->setDataAndType(Landroid/net/Uri;Ljava/lang/String;)Landroid/content/Intent;

# !!! DEBUG!!! Inserted by melon!!!

    const-string/jumbo v3, "INSTALL_LOG"

    new-instance v4, Ljava/lang/StringBuilder;

    invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V

    const-string/jumbo v5, "starting install apk with uri (gJydCDs->b()V ) : "

    invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v4

    invoke-virtual {v4, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    move-result-object v4

    invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v4

    invoke-static {v3, v4}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

# !!! DEBUG !!!! Inserted by melon!!!

    invoke-virtual {p0, v0}, Lfehdhuxht/tsgjwcr/vtgk/gJydCDs;->startActivity(Landroid/content/Intent;)V

    return-void
```

In logcat I see such kind of message:

`D/INSTALL_LOG( 1427): starting install apk with uri (gJydCDs->b()V ) : file:///mnt/sdcard/no_iconjar.apk`

But if I set only hook for android.app.Activity->startActivity my error.log file looks like this:

```
Droidmon-shell-fehdhuxht.tsgjwcr.vtgk:PID: 3902 UID: 10052 Method: startActivity Class: android.app.Activity signatures number :2 signatures: (android.content.Intent)void (android.content.Intentandroid.os.Bundle)void 
Droidmon-shell-fehdhuxht.tsgjwcr.vtgk:PID: 3923 UID: 10052 Method: startActivity Class: android.app.Activity signatures number :2 signatures: (android.content.Intent)void (android.content.Intentandroid.os.Bundle)void 
Droidmon-apimonitor-fehdhuxht.tsgjwcr.vtgk:{"U":10052,"T":3902,"t":5848576430705,"P":3902,"args":[{"data":"null","action":"null","cmp":"fehdhuxht.tsgjwcr.vtgk\/fehdhuxht.tsgjwcr.vtgk.a.d","objType":"intent","type":"null","extras":[{"value":"","key":"errorInfo"}]}],"class":"android.app.Activity","method":"startActivity","type":"binder"}
Droidmon-apimonitor-fehdhuxht.tsgjwcr.vtgk:{"U":10052,"T":3902,"t":5848827387898,"P":3902,"args":[{"data":"null","action":"null","cmp":"fehdhuxht.tsgjwcr.vtgk\/fehdhuxht.tsgjwcr.vtgk.a.d","objType":"intent","type":"null","extras":[{"value":"","key":"errorInfo"}]}],"class":"android.app.Activity","method":"startActivity","type":"binder"}
```

And the smali bytecode that I've written above don't execute. So this is really very strange for me. If you want, I can give you sample with this malware and you can test it on your own emulator this Xposed Framework.

**Comment by melonaerial** [comment]
But how do you usually debug XposedBridge ? Do you debug all Android Framework like in this post http://apienthusiast.blogspot.ru/2014/06/debugging-android-java-framework.html ? is it possible to debug XposedBridge code using this method ?

**Comment by rovo89** [comment]
Well, your hooking code could certainly be improved (e.g. with [this](http://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#hookAllMethods%28java.lang.Class%3C?%3E,%20java.lang.String,%20de.robv.android.xposed.XC_MethodHook%29)), but it should work.

In the smali code, I only see this:
`invoke-virtual {p0, v0}, Lfehdhuxht/tsgjwcr/vtgk/gJydCDs;->startActivity(Landroid/content/Intent;)V`

That's a `startActivity()` method, but not in the `Activity` class. Have you checked whether `Activity.startActivity()` is really called? Could it also be `Context.startActivity()` or something like that?

As for debugging: I usually debug it by inserting additional logging. Not sure if it would work like the link describes as Xposed works distributed across processes.

**Comment by melonaerial** [comment]
Yeah,  Lfehdhuxht/tsgjwcr/vtgk/gJydCDs class extends android.app.Service. And android.app.Service extends android.content.ContextWrapper which also contains startActivity. I will try to check why there is difference in work of application when I hook javax.crypto.Cipher;->doFinal and if I will found something interesting I will report you. Thank you very much for your help!!!

Note: Hooking android.content.Context startActivity method couldn't work because startActivity method there is abstract.

**Comment by nanshihui** [comment]
Is there any way to hook all potential possible startActivity function
