### ISSUE TITLE
update os version, happen error.  

### ISSUE THREAD

**Issue by hhhaiai** [rovo89/XposedBridge#114]
hi：
   thx share this plugin. when I hook os version happen a issue.  android phone 4.2/4.3 update version to 4.4.  will app crash.   4.4phone test update version to 4.2 happen issue too. 
   the log show me, arraylist happen error, or DL(DynamicLoad) error.  can you help me ..
   app: baidu video  apk
  scene:  4.2===4.4  modify version.

   hook single app resolution.  this app lanuch so long time..

**Comment by hhhaiai** [comment]
If you have time, please help me.

**Comment by hhhaiai** [comment]
3Q

**Comment by rovo89** [comment]
I have no idea what you're talking about, but I doubt it's about the Xposed Framework. If it is, read and follow this guide: https://github.com/rovo89/XposedBridge/wiki/Bugs
