### ISSUE TITLE
Is it posible to hook Unity api methods in Unity based app/game?

### ISSUE THREAD

**Issue by arslancharyev31** [rovo89/XposedBridge#116]
For instance I wanna hook ScreenToWorldPoint method from Camera class. Is that possible? If yes, how?

**Comment by rovo89** [comment]
I have no idea. Is it a Java method? Then you can probably hook it.

**Comment by arslancharyev31** [comment]
Well, it's a C# method...

**Comment by rovo89** [comment]
I can't help you when you give such little information. Xposed can hook Java/dex methods, and that's it. If that C# method is somehow converted to a Java/dex/JNI method, than you can hook it, otherwise not.

**Comment by arslancharyev31** [comment]
Thanks for support! The thing is, I don't know much thing about that either. I hope someone who knows Unity framework one day will visit this thread :)
