### ISSUE TITLE
letv leecoo2 xposed issue

### ISSUE THREAD

**Issue by ghost** [rovo89/XposedBridge#122]
Hello I'am using letv x620 which have mtk6797 helio processor and eui OS. I was using xposed and some modules(app settings, gravitybox,xtana, and a special module named eui modder) which were working on 14s eui version. After updates of 15s-16s and last 17s i can't use xposed, cause of system crash it is still stuck at lockscreen after activating modules( installing xposedframework from twrp >reboot>installing xposed installer>giving root privilege>activating modules>reboot) here is a video of issue and xposed log in attachment. Please help us, many user having this issue in letv forums.
[xposed_error_20160905_120942.zip](https://github.com/rovo89/XposedBridge/files/454737/xposed_error_20160905_120942.zip)
[video-1472895638.zip](https://github.com/rovo89/XposedBridge/files/454739/video-1472895638.zip)

**Comment by rovo89** [comment]
> it is still stuck at lockscreen after activating modules

Does it also happen when no modules are active?
See also: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by ghost** [comment]
Ty for your reply. There is only problem when any module activated.

**Comment by rovo89** [comment]
So it's probably not a problem with the Xposed Framework, but with the module. Find out which one causes the issues and report it to the author.

**Comment by ghost** [comment]
but all was working on 14s

**Comment by rovo89** [comment]
Yes, so something changed that broke one or more modules. You already confirmed that the framework itself is working fine, so I can't help you.

**Comment by ghost** [comment]
ok ty

**Comment by rovo89** [comment]
I guess this module might be causing it, as it's very specific to your ROM and might make expectations that are no longer true in the latest versions: http://forum.xda-developers.com/xposed/modules/mod-leeco-eui-moder-t3416932

**Comment by ghost** [comment]
i will try again
