### ISSUE TITLE
Changing a drawable resource with an image file on storage

### ISSUE THREAD

**Issue by ailieff** [rovo89/XposedBridge#123]
Im trying to find a way to change a leanback launcher's background image. Swapping it with a resource within my module works just fine via the fwd method. Although, I wanted to make the user place a png file in the internal (or external) storage and use this as a background image.

This is in Marshmallow with framework version 86 (tried also 82) installed.

``` java
@Override
public void handleInitPackageResources(XC_InitPackageResources.InitPackageResourcesParam resparam) throws Throwable {

    if (!resparam.packageName.equals("com.nvidia.shield.nvcustomize")) {
        return;
    }

    final String filePath = Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "nv_wallpaper.png";

    XposedBridge.log("FilePath: " + filePath);
    XposedBridge.log("Environment.getDataDirectory().getAbsolutePath()): " + Environment.getDataDirectory().getAbsolutePath());
    XposedBridge.log("isExternalStorageWritable: " + isExternalStorageWritable());

    final Bitmap bitmap = BitmapFactory.decodeFile(filePath);

    //resparam.res.setReplacement("com.nvidia.shield.nvcustomize", "drawable", "nv_wallpaper", modRes.fwd(R.drawable.nv_wallpaper)); // this works
    resparam.res.setReplacement("com.nvidia.shield.nvcustomize", "drawable", "nv_wallpaper", new XResources.DrawableLoader() {
        @Override
        public Drawable newDrawable(XResources xResources, int i) throws Throwable {
            XposedBridge.log("newDrawable");
            return new BitmapDrawable(xResources, bitmap);
            // return new BitmapDrawable(xResources, filePath);
        }
    });
}
```

Not sure if my code to return the correct image works - there are no exceptions while running the module, just the image is missing (and black). Strage is writable (not that Im writing there)

Any ideas as to why its not changing the image, or perhaps some other approach?

**Comment by rovo89** [comment]
Does the app you're hooking (not your own app/module!) have access to that path?

**Comment by ailieff** [comment]
Should have access, as its a system app.
Is this the correct way of returning an image to a drawable resource?

If you have any other ideas, I can try them out.

**Comment by rovo89** [comment]
It should work like this, but it's been a long time since I developed this API.
Things you could try:
- Try it with a `ColorDrawable` to see if the replacement works in general.
- Make sure that you can actually read from that location (e.g. create a text file in the same place and really try to read the first line from it).
- Try using the `new BitmapDrawable()` approach for an `ImageView` in a simple app, without any Xposed involvment.
