### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by nicolasSchirmer** [rovo89/XposedBridge#125]
@rovo89
I'm trying to use the Xposed Framework  with the face recognition, but I'm encountering a CastClassException with this package:

> com.google.android.gms.vision.face.Face

Here is the hook structure for the [**detect**](https://developers.google.com/android/reference/com/google/android/gms/vision/face/FaceDetector) method:

``` java
findAndHookMethod(
   "com.google.android.gms.vision.face.FaceDetector",loadPackageParam.classLoader,
   "detect",
   findClass("com.google.android.gms.vision.Frame", loadPackageParam.classLoader),
   new XC_MethodReplacement() {

   @Override
   protected Object replaceHookedMethod(MethodHookParam methodHookParam) throws Throwable {
       StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());

       SparseArray<Face>  faces = findFaces();
       return faces;
   }
//...
```

```
java.lang.ClassCastException: com.google.android.gms.vision.face.Face cannot be cast to com.google.android.gms.vision.face.Face
```

I know that is because of the classloader that differ from what the app is expecting. I also looked on this [xdaThread](http://forum.xda-developers.com/xposed/xposed-hook-cast-to-t3188642). It's possible to overcome this exception?

> - Phone: Moto X force
> - Android 5.1.1
> - Xposed v86
> - play-services-vision:7.8.0

**Comment by rovo89** [comment]
> I know that is because of the classloader that differ from what the app is expecting.

Exactly, that's why you can't cast the object. The `Face` class you refer to in the code above is resolved with your module's classloader, whereas the app expects a `Face` class resolved with the app's classloader.

You could avoid this reference to by simply using `return findFaces()` (no need to assign the result to a variable first), but I guess that won't help you as the `findFaces()` method probably has the `Face` class in its return value anyway. Not sure what you do in that method, but basically, you cannot have any direct references to the `Face` class, which will usually mean that you'll have to use reflection for many things and just return an unspecific `Object`.

**Comment by romuloreis** [comment]
I got the same problem when I was trying to hook the method `detect` from [BarcodeDetector](https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/BarcodeDetector). I couldn’t find out a solution, so after many hours trying I gave up. 

> ...use reflection for many things and just return an unspecific Object.

What do you mean by that? Can you give an example please?

That was the code:

``` java
   @Override
   protected Object replaceHookedMethod(MethodHookParam methodHookParam) throws Throwable {
       StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());

       SparseArray<Barcode>  barcodes = new SparseArray<Barcode>();
       barcodes.append(new Barcode(/*params*/));
       return barcodes;
   } 
```

@nicolasSchirmer Have you gotten some solution?

**Comment by nicolasSchirmer** [comment]
> You could avoid this reference to by simply using return findFaces()

Yes, I was doing that on the module itself, but did that way here for better code understatement.

---

@romuloreis  Not have found an answer yet. Tried unsuccessful use reflection directly to an `Object` of `SparseArray<Face>`, but I couldn't access the `Face` object, only the `SparseArray` object structure.

No Exception is thrown when return a new instance.

``` java
return new SparseArray<Face>;
// or
SparseArray<Face> faces = new SparseArray<>();
return faces;
```

`ClassCastException` is thrown when a `Face` is added to the `SparseArray` 

``` java
SparseArray<Face> _faces = new SparseArray<>();
Landmark[] landmarks = new Landmark[]{};
Face _face = new Face(i, new PointF(0, 0), 0, 0, 0, 0, landmarks, 0, 0, 0);

_faces.append(i, _face);

return _faces;
```

Here is how I call the detect method:

``` java
// hook here
SparseArray<Face> faces = faceDetector.detect(frame);
```

**Comment by rovo89** [comment]
What I mean with using reflection is:

`new Face()` will create an instance of the `Face` class that has been loaded with your module's classloader. But you need an instance of the `Face` class with the app's classloader. This becomes more obvious if you think about it as an additional prefix for the package:

``` java
moduleclassloader.com.google.android.gms.vision.face.Face
appclassloader.com.google.android.gms.vision.face.Face
```

You can't possibly cast between the two, and there's no way you can say `new appclassloader.com.google.android.gms.vision.face.Face()`. So you have to use reflection to get an instance of that class and its constructor, then call the latter. Xposed has some helpers for this e.g. [this one](http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#newInstance%28java.lang.Class%3C?%3E,%20java.lang.Object...%29). Note that for the `Landmark` array, you need to use reflection as well. There's no helper for creating an array, but it shouldn't be [too hard](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Array.html#newInstance%28java.lang.Class,%20int...%29). As for adding the object to the `SparseArray`: Generic types are compile-time only, so just leave out the `<...>` and ignore the warnings.

I know that this isn't easy, but that's not Xposed's fault. `Face` class could be resolved to completely different implementations, so Java is right not to let you handle them as if they were the same. You're probably better off when you don't import the classes from the library in your module, and even remove the dependencies on it. That way, you're forced to use reflection.
