### ISSUE TITLE
Color is not changing 

### ISSUE THREAD

**Issue by nikandlv** [rovo89/XposedBridge#127]
Hi. I tried all of these and it dont change the target color 
```java
@Override
public void handleInitPackageResources(InitPackageResourcesParam resparam) throws Throwable {
	// replacements only for target
	if (!resparam.packageName.equals("com.aide.ui"))
		return;

	// lets see if our change works !
	resparam.res.setReplacement("com.aide.ui", "color", "editor_background_light", "#ff000000");
	resparam.res.setReplacement("com.aide.ui:color/editor_background_light", "#ff000000");
	resparam.res.setReplacement("com.aide.ui", "color", "editor_background_light", "#ff000000");
	resparam.res.setReplacement("com.aide.ui", "color", "editor_background_light", "#ff000000");
}
```

What part im missing?

**Comment by rovo89** [comment]
You're trying to replace a color (-> an integer value) with String. That's not supported, see the [API docs](http://api.xposed.info/reference/android/content/res/XResources.html#setReplacement%28java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.Object%29) (which also mention you could use `Color.parseColor`).

**Comment by nikandlv** [comment]
Thats it! Thanks for helping :)
