### ISSUE TITLE
little problems

### ISSUE THREAD

**Issue by wx-chevalier** [rovo89/XposedBridge#13]
Recently I try to develop an application containing some function like wireshark in Android. I want to Hook the method:org.apache.http.client.HttpClient -> execute but always be unsuccessful. I wonder the reason : is the method running in new thread can't be hooked in Main Thread? I think they are in the some application Context.

so sorry to bother you. LOL

**Comment by rovo89** [comment]
This really isn't a good place for support questions. Please use http://forum.xda-developers.com/xposed/ instead. And please give more details, I don't even understand your question.
