### ISSUE TITLE
Xposed doesn't work after unroot

### ISSUE THREAD

**Issue by lacheolsoo** [rovo89/XposedBridge#130]
Xposed doesn't work after unrooting..
I've already installed Xposed Framework & Installer. 

Rooting -> Install Framework & Installer & modules (work very well) -> Unrooting -> not work

**"Xposed Framework version 86 is installed, but not active. Please check the logs for details."**

Root util - Kingo ROOT

Here is the log..
11-14 19:20:27.597 I/Xposed  (  467): -----------------
11-14 19:20:27.597 I/Xposed  (  467): Starting Xposed version 86, compiled for SDK 23
11-14 19:20:27.597 I/Xposed  (  467): Device: T2 (unknown), Android version 6.0.1 (SDK 23)
11-14 19:20:27.597 I/Xposed  (  467): ROM: bigHand_v2-eng 6.0.1 MMB29M eng.liangjp.20161019.184746 test-keys
11-14 19:20:27.597 I/Xposed  (  467): Build fingerprint: qcom/bigHand_v2/bigHand_v2:6.0.1/MMB29M/liangjp10191849:eng/test-keys
11-14 19:20:27.597 I/Xposed  (  467): Platform: armeabi-v7a, 32-bit binary, system server: yes
11-14 19:20:27.597 I/Xposed  (  467): SELinux enabled: yes, enforcing: no
11-14 19:20:31.373 I/Xposed  (  467): -----------------
11-14 19:20:31.378 I/Xposed  (  467): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-14 19:20:31.913 I/Xposed  (  467): Detected ART runtime
11-14 19:20:31.946 I/Xposed  (  467): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-14 19:20:32.561 I/Xposed  (  467): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
11-14 19:20:32.854 I/Xposed  (  467):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
11-14 19:21:51.523 E/Xposed  ( 8802): **Could not hook Xposed Installer**
11-14 19:21:51.523 E/Xposed  ( 8802): **de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: de.robv.android.xposed.installer.XposedApp**
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedInit.hookXposedInstaller(XposedInit.java:335)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedInit.access$000(XposedInit.java:43)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:96)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.os.Looper.loop(Looper.java:148)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at java.lang.reflect.Method.invoke(Native Method)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-14 19:21:51.523 E/Xposed  ( 8802): Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.installer.XposedApp
11-14 19:21:51.523 E/Xposed  ( 8802): 	at java.lang.Class.classForName(Native Method)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at java.lang.Class.forName(Class.java:324)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
11-14 19:21:51.523 E/Xposed  ( 8802): 	... 15 more
11-14 19:21:51.523 E/Xposed  ( 8802): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.installer.XposedApp" on path: DexPathList[[zip file "/data/app/de.robv.android.xposed.installer-1/base.apk"],nativeLibraryDirectories=[/data/app/de.robv.android.xposed.installer-1/lib/arm, /vendor/lib, /system/lib]]
11-14 19:21:51.523 E/Xposed  ( 8802): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-14 19:21:51.523 E/Xposed  ( 8802): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-14 19:21:51.523 E/Xposed  ( 8802): 	... 19 more
11-14 19:21:51.523 E/Xposed  ( 8802): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.installer.XposedApp" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-14 19:21:51.523 E/Xposed  ( 8802): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-14 19:21:51.523 E/Xposed  ( 8802): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-14 19:21:51.523 E/Xposed  ( 8802): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-14 19:21:51.523 E/Xposed  ( 8802): 		... 20 more
11-14 19:21:51.523 E/Xposed  ( 8802): 		Suppressed: java.lang.ClassNotFoundException: de.robv.android.xposed.installer.XposedApp
11-14 19:21:51.523 E/Xposed  ( 8802): 			at java.lang.Class.classForName(Native Method)
11-14 19:21:51.523 E/Xposed  ( 8802): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-14 19:21:51.523 E/Xposed  ( 8802): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-14 19:21:51.523 E/Xposed  ( 8802): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-14 19:21:51.523 E/Xposed  ( 8802): 			... 21 more
11-14 19:21:51.523 E/Xposed  ( 8802): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by aviraxp** [comment]
https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by lacheolsoo** [comment]
I can't find this issue anywhere in XDA. Does rooting essential when running Xposed? I though it needs only installing Xposed Framework. I have full OS source code and system signing key. Is there any way to solve this problem? or something wrong with KingROOT unrooting?

This is the end of java source code.. android-23\java\lang\Class.java
static native Class<?> classForName(String className, boolean shouldInitialize,
            ClassLoader classLoader) throws ClassNotFoundException;

**Comment by rovo89** [comment]
Once installed, Xposed shouldn't required root access. Are you using the official versions of the framework and the installer?

**Comment by lacheolsoo** [comment]
Thank you for your answer.
I used pure Xposed Installer(v3.1.1) & Xposed Framework(v86).

Suspect is "KingoROOT".. I'll find out..

**Comment by lacheolsoo** [comment]
I solved this problem.
"adb install XposedInstaller_3.1.1.apk" is work.

Android Studio 2.2.2 - Run 'app' makes some problem. I don't know the reason yet..

**Comment by rovo89** [comment]
Instant Run causes this, because it modifies the APK and doesn't make the classes directly available. That's why I asked whether you're using the official installer, i.e. the official APK released and signed by me. Turns out you don't use the official version, but a self-compiled version. Turn off Instant Run if you really want to do that, otherwise just use the official version.
