### ISSUE TITLE
how to set installer permission?

### ISSUE THREAD

**Issue by netstu** [rovo89/XposedBridge#132]
i don't install ther xposed installer, i use adb mkdir an dir , /data/data/de.robv.android.xposed.installer/conf/

and add a modules.list to this dir

chown -R system.system dir
chmod -R 755 dir 
the module is ok, right loaded

but i want to set this dir is 511, but i don't know this dir right user? 

http://stackoverflow.com/questions/29494508/enable-xposed-modules-from-shell

**Comment by rovo89** [comment]
I think the file is only read as root user, so any permissions should be fine. But note that I only support the official way, i.e. activation via the official Xposed Installer app.
