### ISSUE TITLE
ClassNotFound Which Extract At Runtime

### ISSUE THREAD

**Issue by Jasi2169** [rovo89/XposedBridge#133]
i am trying to hook application which has class for example aB

now that class actually extracted at runtime ,
small details for better understanding :- 

```
app package :- com.example.test
some classes :- com.example.test.MainActivity
```

this can be hooked okay
now if you decompile the apk
`/smali/com/example/test`
but there is another package as
```
/smali/o/aB <= Not Visible in classes.dex but loadded at runtime (which i extracted with baseclassloader)
/smali/o/aC  <= this one is visible statically
```

now the method name are also in chinese for example,i know the parameters so here is my code

```
Class<?> appClass = XposedHelpers.findClass("o.aB", cls); // cls is classloader
            Method[] appMethods = XposedHelpers.findMethodsByExactParameters(appClass, int.class,int.class,String.class,String.class);
            XposedBridge.log("appmethodname :- "+appMethods[0].getName());

            if (appMethods.length >= 1) {
                Method resultMethod = appMethods[0];

                XposedBridge.hookMethod(resultMethod, new XC_MethodHook() {
                    @Override
                    protected void beforeHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {
                        super.beforeHookedMethod(param);

bla bla......


```

i am getting error :- classnotfond exception 

what can be done and how this class can be hooked

**Comment by Jasi2169** [comment]
well i believe the package name of the application is not same i guess

for example if i use
if(packagename.equals("com.example.test")){
add hook code here for the class which is loaded at runtime wont execute
}

do you think the package name should be o.aB instead of "com.example.test" as it is loaded by another classloader right ?

**Comment by rovo89** [comment]
You need to check for the Android package name, so `com.example.test` is fine in either case.

What you'll need to find out is how exactly that `o.AB` class is loaded. Is it a separate .dex file? Does the application create a new class loader or does it use reflection to extend the existing "main" class loader? The latter is (I think) done by Instant Run, also XposedBridge itself does this. The second question is: When is this done?

Once you know these two things, you'll need to place a hook in a way that it's executed after your target class is loaded (or at least the class loader is prepared). In that callback, you then place the real hook, for which you'll need the class loader that actually loads your target class.

**Comment by Jasi2169** [comment]
File is loaded from this API

public DexFile(String fileName) throws IOException {
as per api "Opens a DEX file from a given filename. This will usually be a ZIP/JAR
     * file with a "classes.dex" inside."

the filename is actually a zip file which has classes.dex inside it and the only package inside it is
"o/aB.smali" ,so i extracted that api and took the zip file and decompiled

so seems this is separate classes.dex from zip

so i guess the hook i am trying first checks if pckagename.equals where as i think as this is loaded separately ain't i have to hook package "o" or something ?

call is like this 
`Ldalvik/system/DexFile;->loadDex(Ljava/lang/String;Ljava/lang/String;I)Ldalvik/system/DexFile;`

**Comment by rovo89** [comment]
> so i guess the hook i am trying first checks if pckagename.equals where as i think as this is loaded separately ain't i have to hook package "o" or something ?

No, you can't hook package "o". The name "package" is badly chosen actually, not by me but by the Android team. You are talking about the Java package, but in `handleLoadPackage()`, "package" actually means "app", so it's about the technical name for the app. These two (Java package and app ID) are often the same, but that's not necessarily the case. Just think about `java.lang.String` and such - these are all used by apps, but you don't need a check in `handleLoadPackage()` that the package name is `java.lang`.

The line you mentioned will return a `DexFile`, which has a `loadClass()` method. I assume they're using reflection to create objects of `o.aB` or call its stack methods. Could you show more of the code that's used to do that?

**Comment by Jasi2169** [comment]
so how can i hook this class ?

anyway here is the decompiled java code from jeb decompiler

```
static void ॱ(ClassLoader arg11, ArrayList arg12) {
        int v2 = ((List)arg12).size();
        Field v3 = ᐝ.ˏ(arg11, "path");
        StringBuilder v4 = new StringBuilder(v3.get(arg11));
        String[] v5 = new String[v2];
        File[] v6 = new File[v2];
        ZipFile[] v7 = new ZipFile[v2];
        DexFile[] v2_1 = new DexFile[v2];
        ListIterator v12 = ((List)arg12).listIterator();
        while(v12.hasNext()) {
            Object v8 = v12.next();
            String v9 = ((File)v8).getAbsolutePath();
            v4.append(':').append(v9);
            int v10 = v12.previousIndex();
            v5[v10] = v9;
            v6[v10] = ((File)v8);
            v7[v10] = new ZipFile(((File)v8));
            v2_1[v10] = DexFile.loadDex(v9, v9 + ".dex", 0);
        }

        v3.set(arg11, v4.toString());
        ᐝ.ˊ(arg11, "mPaths", ((Object[])v5));
        ᐝ.ˊ(arg11, "mFiles", ((Object[])v6));
        ᐝ.ˊ(arg11, "mZips", ((Object[])v7));
        ᐝ.ˊ(arg11, "mDexs", ((Object[])v2_1));
    }
```

**Comment by rovo89** [comment]
As far as I can see, that method extends the ClassLoader in the first parameter with the files it gets as second parameters. Depends on the ClassLoader how well that works, but this doesn't matter for you.

If you hook the function you posted and use the `afterHookedMethod()` callback, you have both things you need: the class loader (`param.args[0]`) and it's at the right time (the class loader should know `o.aB` by then, but hasn't done anything with it yet).

**Comment by Jasi2169** [comment]
okay so you mean hook above function get classloader from it and then use that classloader here

```
Class<?> appClass = XposedHelpers.findClass("o.aB", cls); // cls is classloader used here 
            Method[] appMethods = XposedHelpers.findMethodsByExactParameters(appClass, int.class,int.class,String.class,String.class);
            XposedBridge.log("appmethodname :- "+appMethods[0].getName());

            if (appMethods.length >= 1) {
                Method resultMethod = appMethods[0];

                XposedBridge.hookMethod(resultMethod, new XC_MethodHook() {
                    @Override
                    protected void beforeHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {
                        super.beforeHookedMethod(param);

bla bla......

```
so it will come in same statement like

```
if(lpparam.packagename.equals("com.example.test")){

hook function to get class loader by afterhook

now use that classloader between if statement to hook right ?
}
```
