### ISSUE TITLE
xposed module how to load so lib?

### ISSUE THREAD

**Issue by netstu** [rovo89/XposedBridge#134]
in xposed module, i want to use System.loadLibrary("xx.so"), but can't loaded

i use System.load("/data/data/xxx/lib/xx.so"); in part of mobile can load, other part of mobile can't load

Is there a better way？

**Comment by rovo89** [comment]
I think you're using the right method as you seem to need to use an absolute path. Does that answer your question?

**Comment by liudongmiao** [comment]
In short, look through into basedexclassloader, and pathList, and nativeLibraryDirectories.

**Comment by truthslave** [comment]
I am a beautiful person. I will be a good time to time. the first time in
the world of the most important thing is that the company.
