### ISSUE TITLE
Possible Issues when Flashed in the Wrong Order?

### ISSUE THREAD

**Issue by Ibuprophen** [rovo89/XposedBridge#135]
@rovo89, I would like to ask a simple but, important question to me... 

I was just wondering what your thoughts were regarding the order in which to flash a clean install. 

Here's the order that I use when I flash a clean installation of my device:

1) CM13 ROM
2) Open GApps package
3) XPosed Framework
4) SuperSU

I am under the assumption that, possibly, i need to leave out the XPosed Framework until i install BusyBox (to include running the BusyBox Binary and Symlink process) then flash the XPosed Framework. 

Am i performing the install correctly (as listed above)? 

What prompted me to ask this is the possibility of installing the XPosed Framework at an incorrect time/order that may result in an improper installation. 

Or is my assumption correct by installing BusyBox first (as stated above)? 

I just wanted to be sure and get your input. 

I know that your a very busy person and I appreciate your time, assistance and understanding regarding this simple question. ****

**Comment by rovo89** [comment]
You don't need to flash BusyBox, Xposed doesn't rely on it at all (it comes with its own BusyBox binary for installation).

You can install Xposed at any time after flashing the ROM. In the future, you might need to flash it after SuperSU for systemless, but as official Xposed doesn't support systemless yet, it doesn't matter at this time.
