### ISSUE TITLE
  请问不能解析 是怎么回事？我反编译看了字节码文件发现类是对的呀没有被混淆。 I would like to ask how can not be resolved? I looked at the bytecode file and found that the class was right.

### ISSUE THREAD

**Issue by lozn00** [rovo89/XposedBridge#139]
I/dalvikvm: Failed resolving Lcn/qssq666/qq/redpackaget/SBM; interface 1967 'Lde/robv/android/xposed/IXposedHookLoadPackage;'

**Comment by rovo89** [comment]
I don't understand what you want. What's the full stack trace etc.? What did you do?
See also: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by lozn00** [comment]
This problem seems to me solved. I adjusted the confusion.
