### ISSUE TITLE
xposed plugin can not be used after reinforcement

### ISSUE THREAD

**Issue by lozn00** [rovo89/XposedBridge#141]
xposed plugin can not be used after reinforcement
dont find class ****  apk Can not be reinforced on the plugin do？

**Comment by rovo89** [comment]
I didn't understand anything. What is "reinforcement"? Please express yourself properly and in more detail, otherwise I'll ignore you in the future...

**Comment by lozn00** [comment]
Sorry, my English is not good enough.
Means the use of domestic encryption software after encryption can not find the class entrance

**Comment by rovo89** [comment]
OK, **especially** if you don't speak English that good, it's important that you give many details. Context is often very important for understanding.

I'm aware of tools that encrypt the classes in your APK, see #69. Decryption will take place when the app is started, but Xposed just wants to load the classes. This is something I won't fix.

**Comment by lozn00** [comment]
@rovo89  


Excuse me, is there a compatible xposed encryption tool recommended? Although Android development can basically crack this I remain silent, but I do not want my software to make one apktool very easy encryption.

**Comment by rovo89** [comment]
ProGuard should work with Xposed, as long as you keep the name of the start class unchanged (the one you enter in `xposed_init`).

**Comment by lozn00** [comment]
Well, thank you for your answer,
