### ISSUE TITLE
Mistakes but not specific reasons

### ISSUE THREAD

**Issue by lozn00** [rovo89/XposedBridge#142]
Mistakes but not specific reasons
I did not add the try catch statement
This error led to my program in the second implementation of a function can not be used normally.
Ncent.mobileqq W/System.err: at de.robv.android.xposed.XposedHelpers.callStaticMethod (XposedHelpers.java:985)
12-19 13:08:39.981 W/System.err: at de.robv.android.xposed.XposedBridge.handleHookedMethod (XposedBridge.java:645) 1173-1665/com.tencent.mobileqq

develop xposed lib XposedBridgeApi-82.jar

**Comment by rovo89** [comment]
Again, follow https://github.com/rovo89/XposedBridge/wiki/Bugs!
Post the full stack trace, post your source code, post the Java or smali code you're trying to hook.
