### ISSUE TITLE
The class object of the same package called by the plugin is created multiple times

### ISSUE THREAD

**Issue by qssq666123** [rovo89/XposedBridge#144]
Why does a static class address different static member variables?
he broadcast recceiver is registered multiple times, but and the broadcast recipient declaration is a static member at class   

The class object of the same package called by the plugin is created multiple times. Why are there multiple memory addresses?
When hook a bag when I call a static class static class I registered a register broadcastreceiver, found to be repeatedly registered so I judge whether the field is empty, empty is not registered, finally does not solve the problem, I print the memory address that static class 2 will hold how is it?

Log.i(TAG,"SETTING"+mSetingReceiver);
The static member variable address found in the broadcast print I received is not the same
Main.java

```
 

public class Main extends MainHandlerPackage implements IXposedHookLoadPackage, IXposedHookZygoteInit {
                        public static final String MainName = Main.class.getPackage().getName();
                    
                        public static XSharedPreferences xpSharePrefrences;
                    
                        @Override
                        public void handleLoadPackage(LoadPackageParam loadPackageParam) {
                            handlerLoadPackage(loadPackageParam);
                    
                        }
                    
                        @Override
                        public void initZygote(StartupParam startupParam) {
                    
                            xpSharePrefrences = new XSharedPreferences(BuildConfig.APPLICATION_ID);
                    
                        }
                    }




```

```

 */
public class MainHandlerPackage {
    protected static void handlerLoadPackage(XC_LoadPackage.LoadPackageParam loadPackageParam) {
        Main.xpSharePrefrences.reload();
....call  DoHookInterface.java  
}
```

//DoHookInterface.java

.....
    static BroadcastReceiver mSetingReceiver;//......
 static class ApplocationOnCrateHook extends XC_MethodHook {

        protected void beforeHookedMethod(MethodHookParam methodHookParam) {
            DoInterfaceHook.regSettingChangeReceiver((Context) methodHookParam.thisObject);
        }
    }
    private static void regSettingChangeReceiver(final Context context) {
        Utils.Log("regSettingChangeReceiver->" + context);
        if (mSetingReceiver == null) {
            Intent intent = new Intent(SETCHANGEINTENT_UNI);
            context.sendBroadcast(intent);
            Utils.Log("reg new regsettingReceiver->" + mSetingReceiver + ",context" + context + "," + context.getClass().getName());
            /**
        
             */
            mSetingReceiver = new SettingReceiver(context);
            IntentFilter intentFilter = new IntentFilter();
            intentFilter.addAction(ConfigConstants.SETCHANGEINTENT);
            intentFilter.addAction(ConfigConstants.SETCHANGEINTENT_TEST);
                     context.registerReceiver(mSetingReceiver, intentFilter);
        }
//        Utils.Log("reg new regsettingReceiverend->" + mSetingReceiver);
    }

class SettingReceiver extends BroadcastReceiver {

    private final Context context;

    public SettingReceiver(Context context) {
        this.context = context;
    }

    public void onReceive(Context context, Intent intent) {
        String action = intent.getAction();
        Utils.Log("qq_action" + action + ",context " + context + "," + SettingReceiver.this + "," + DoHookInterface.mSetingReceiver);
//DoHookInterface.mSetingReceiver  This is a static member variable received 2 memory addresses are not the same

}

}

**Comment by qssq666123** [comment]
12-25 19:54:57.470 928-928/? I/Xposed: qssq_pro :qq_actioncn.qssq666.pro.redpackaget.SETTING_CHANGED,context android.app.ContextImpl@4a444444444o.redpackaget.SettingReceiver@4a950268,cn.qssq666.pro.redpackaget.SettingReceiver@4a950268
12-25 19:54:57.470 1028-1028/? I/Xposed: qssq_pro :qq_actioncn.qssq666.pro.redpackaget.SETTING_CHANGED,context android.app.ContextImpl@4a928644444SettingReceiver@4a950b2c,cn.qssq666.pro.redpackaget.SettingReceiver@4a950b2c
12-25 19:55:48.840 928-928/? I/Xposed: qssq_pro :qq_actionSETTING_CHANGED_UNI,context android.app.ContextImpl@4a92b4c0,cn44444
12-25 19:55:48.840 1028-1028/? I/Xposed: qssq_pro :qq_actionSETTING_CHANGED_UNI,context android.app.ContextImpl@4a9286b4,444444dpackaget.SettingReceiver@4a950b2c,cn.qssq666.pro.redpackaget.SettingReceiver@4a950b2c

**Comment by qssq666123** [comment]
Static internal class to class problem seems to solve

**Comment by qssq666123** [comment]
问题依然存在
我用中文再说一遍
我注册了一个广播接受者 广播接受者 是静态成员变量  注册方法也是静态的 发现被多次注册了,于是我判断是否这个静态变量为空,发现这样也不好使,以为是崩溃导致的,崩溃也会出现这种情况所以我try了 可能出现的错误发现并没有结果，  为什么会调用2次而且第二次调用这个静态方法的时候成员变量(广播接受者) 依然为空 所以又被调用了一次  我尝试在 onReceive()打印 静态成员变量 发现地址是不一样的（2个静态变量地址 注册了2次广播接受者），静态成员变量怎么会存在这种情况？  我只在xposed handleLoadPackage 里面间接调用了呀 ，理论上不可能出现的,所以无百思不得其解..

**Comment by rovo89** [comment]
If I understood your problem correctly, your code is executed in handleLoadPackage(). This callback is run whenever a new app is started, and as (almost) every app runs in its own process, each invocation of your code takes place in different processes with different memory. If you set a variable in process 1, it won't be set on process 2. That's how Android/Linux works. So your variable will always be null.

**Comment by qssq666123** [comment]
Well, thank you very much for your answer, 

So it seems that BroadCastReceiver IPC communication is not feasible? Is it? Registered broadcast recipients can not log off, I tried sendBroadCast way to cancel
UnregisterReceiver,
But there are still many problems
How can I solve this problem? I can't think of any way.
? Because I interprocess communication through the radio, now I found that some significant memory leaks. The XSharedPreferences efficiency is low and can't write configuration

**Comment by qssq666123** [comment]
我非常不理解为什么是这样的结果

  handlerLoadPackage 所在class 申明 定义 对象 都是同一个内存地址
但是如果我调用其它class 不管是静态的还是非静态的  
在  handlerLoadPackage  下次调用的时候就为null  

下面是正常的代码 处于handlerLoadPackage   所在类  只会执行一次


但是我如果放在其他类

每次 handlerLoadPackage   调用这个类 内存地址都是null
```
I don't understand why this is so.
HandlerLoadPackage where the class declaration defines the object is the same memory address
But what if I call other class whether static or non static
The next time handlerLoadPackage calls is null
Here is the normal code in the handlerLoadPackage where the class will only execute once
But if I put it in other classes
Each time handlerLoadPackage calls this class memory address is null
```
```
public class Test {
    static Info object = null;

    public static void init(String name) {
        if (object == null) {
            object = new Info();
            object.setHello("address_" + Integer.toHexString(object.hashCode()));
            Utils.Log("init_static_obj_at_test_" + name + "," + object.getHello());
        }
        Utils.Log(name + "Test_address_" + name + "_" + object);
    }
}
I don't understand why this is so.
HandlerLoadPackage where the class declaration defines the object is the same memory address
But what if I call other class whether static or non static
The next time handlerLoadPackage calls is null
Here is the normal code in the handlerLoadPackage where the class will only execute once
But if I put it in other classes
Each time handlerLoadPackage calls this class memory address is null
Class Test public {
Info object static = null;
Public static init void (String name) {
If (object = = null) {
Object = Info new ();
Object.setHello ("address_" + Integer.toHexString (object.hashCode) ());
Utils.Log ("init_static_obj_at_test_" + name + "," + object.getHello);
}
Utils.Log (name + Test_address_ + name + object + _ ");
}
}









```
```
Take a look at the next example.
Public class implements IXposedHookLoadPackage, IXposedHookZygoteInit {, Main
I try to ublic void initZygote (StartupParam startupParam) {}
Calling the initialization method created by the current class
Public XSharedPreferences xpSharePrefrences;
Private MainHandlerPackage mainHandlerPackage;
@Override
Public void handleLoadPackage (LoadPackageParam loadPackageParam) {
MainHandlerPackage.handlerLoadPackage (loadPackageParam);
}
@Override
Public void initZygote (StartupParam startupParam) {
XpSharePrefrences = new XSharedPreferences (BuildConfig.APPLICATION_ID);
(/ / DoInterfaceHook.initValue);
MainHandlerPackage = new MainHandlerPackage (xpSharePrefrences);
MainHandlerPackage.initConfig ();
}
}
Public class MainHandlerPackage {
Private final XSharedPreferences xSharedPreferences;
QqConfig QQConfig;
WeChatConfig WeChatConfig;
QqVersionInit QQVersionInit;
InitConfig ()
Void initConfig public () {
MemoryCache = new MemoryCache ();
QqVersionInit = new QQVersionInit ();
QqConfig = QQConfig new ();
WeChatConfig = new WeChatConfig ();
}
Protected void handlerLoadPackage (XC_LoadPackage.LoadPackageParam loadPackageParam) {
Utils.log ("qqConfig" +qqConfig);
To solve the above wording / / create repeat problem but the problem comes.
Each call to the method of qqVersionInit / null is not always the same address
But some things need to do / / initialization in handlerLoadPackage, such as the initialization of Context
"I try to do
(initContext); / /
}
/ / set value again next time after the handlerLoadPackage call initContext null has been leading to repeated what I create context how should write to solve this problem.
Void initContext private () {
Utils.Log ("memoryCache1" + memoryCache + "," + memoryCache.getContext () + "," + memoryCache.isInit ());
(if) (memoryCache.getContext = = null) {
Class<? > aClass = XposedHelpers.findClass ("android.app.ActivityThread", ClassLoader.getSystemClassLoader);
Utils.Log ("classTheread:" + aClass);
/ / android.app.ActivityThread
Object currentActivityThread = XposedHelpers.callStaticMethod (aClass, "currentActivityThread"); //ActivityThread
MemoryCache.setContext (Context) XposedHelpers.callMethod (currentActivityThread, "getSystemContext"); //ContextImpl
String packageName = memoryCache.getContext ().GetPackageName ();
Utils.Log ("packageName:" + packageName + "," + (memoryCache.getContext)); / /.
If (memoryCache.isInit ()) {
Return;
}
RegSettingChangeReceiver (memoryCache.getContext ());
MemoryCache.setInit (true);
}
Utils.Log ("memoryCache" + memoryCache + "," + memoryCache.getContext () + "," + memoryCache.isInit ());
}
}
```





12-26 14:01:20.747 10260-10260/? I/Xposed: qssq_pro :memoryCache1cn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,null,false
12-26 14:01:20.747 10260-10260/? I/Xposed: qssq_pro :memoryCachecn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,android.app.ContextImpl@4a85ad14,true
12-26 14:01:39.663 10674-10674/? I/Xposed: qssq_pro :memoryCache1cn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,null,false
12-26 14:01:39.663 10674-10674/? I/Xposed: qssq_pro :memoryCachecn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,android.app.ContextImpl@4a85c3f4,true
12-26 14:01:50.323 10973-10973/? I/Xposed: qssq_pro :memoryCache1cn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,null,false
12-26 14:01:50.323 10973-10973/? I/Xposed: qssq_pro :memoryCachecn.qssq666.pro.redpackaget.bean.MemoryCache@4a816d44,android.app.ContextImpl@4a85a150,true

**Comment by qssq666123** [comment]
The definitions here do not initialize multiple times are normal.

```

public class Main implements IXposedHookLoadPackage, IXposedHookZygoteInit {

   Info object;
    public static Info object_static;

    @Override
    public void handleLoadPackage(LoadPackageParam loadPackageParam) {
        mainHandlerPackage.handlerLoadPackage(loadPackageParam);
    if (loadPackageParam.packageName.equals("com.tencent.mobileqq")) {
            Test.init("qq");//Here the call will determine whether the member variable is empty or not null is //created to find that each time is null
            Utils.Log("handleLoadPackage_QQ");
            Utils.Log("object_qq_start:" + object);
            Utils.Log("object_qq_static_start:" + object_static);
            if (object == null) {

                object = new Info();
                Utils.Log("init_obj_at_qq");
            } else {
                object.setRunCount(object.getRunCount() + 1);
            }
            if (object_static == null) {
                object_static = new Info();
                Utils.Log("init_static_obj_at_qq");
            } else {
                object_static.setRunCount(object_static.getRunCount() + 1);
            }
            Utils.Log("object_qq_start_end:" + object + "," + object.getRunCount());
            Utils.Log("object_qq_static_end:" + object_static + "," + object_static.getRunCount());


        } else {
            Test.init("other");
            Utils.Log("object_other_start:" + object);
            Utils.Log("object_other_static_start:" + object_static);
            if (object == null) {
                object = new Info();
                Utils.Log("init_obj_at_other");
            }
            if (object_static == null) {
                object_static = new Info();
                Utils.Log("init_static_obj_at_other");
            }

            Utils.Log("object_other_end:" + object);
            Utils.Log("object_other_static_end:" + object_static);


        }
    }
}
```

**Comment by qssq666123** [comment]
he object_static test above is wrong
Object_static is initialized after being initialized in member variables
Otherwise each handleLoadPackage variable is empty
conclusion
**Unable to set member variables within handleLoadPackage,
Sets property values for declared member variables such as info.setStr ("test")
Are not valid
The modified value is empty at the next handleLoadPackage
So what should I do,
Some logic must be initialized after handleLoadPackage**
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: object_other_start:null
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: object_other_static_start:null
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: init_obj_at_other
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: init_static_obj_at_other
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: object_other_end:cn.qssq666.pro.redpackaget.qq694886526.Info@4a83eed8
12-26 14:32:13.309 2946-2946/ I/Xposed: qssq_pro: object_other_static_end:cn.qssq666.pro.redpackaget.qq694886526.Info@4a83efd0
12-26 14:32:14.069 3034-3034/? Qssq_pro: init_static_obj_at_test_qq, address_4a83f170, I/Xposed:
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: qqTest_address_qq_cn.qssq666.pro.redpackaget.qq694886526.Info@4a83f170
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: handleLoadPackage_QQ
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: object_qq_start:null
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: object_qq_static_start:null
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: init_obj_at_qq
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: init_static_obj_at_qq
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: object_qq_start_end:cn.qssq666.pro.redpackaget.qq694886526.Info@4a840934,0
12-26 14:32:14.069 3034-3034/ I/Xposed: qssq_pro: object_qq_static_end:cn.qssq666.pro.redpackaget.qq694886526.Info@4a840a24,0
12-26 14:32:14.979 3115-3115/? Qssq_pro: init_static_obj_at_test_other, address_4a83eeb4, I/Xposed:
12-26 14:32:14.979 3115-3115/ I/Xposed: qssq_pro: otherTest_address_other_cn.qssq666.pro.redpackaget.qq694886526.Info@4a83eeb4
12-26 14:32:14.979 3115-3115/ I/Xposed: qssq_pro: object_other_start:null

**Comment by rovo89** [comment]
Sorry, I can't follow your examples, they're too confusing.

I think you still didn't get that each app has its own process and therefore its own state. So everything you do in one process (for example in handleLoadPackage) applies only to one process. I agree that this is confusing in the beginning, but I can't change it.

You try to register a broadcast receiver. But you first need to be sure in which process that receiver is needed. Currently, you create it in every process. If the null checked worked the way you think, you would create it in the first process that is started. That's usually the system server. If that is what you want, check the package name in handleLoadPackage.  But be aware that from that receiver, you can only call code in the system server process. If you update variables from the receiver, this will only apply to the same process, other apps will still see the previous value. If you plan to use this to send values to each process, you will really need to register a receiver in each process.

**Comment by qssq666123** [comment]
hank you very much
No way, then only this way
Just want to the 2 processes these share the configuration information variables but I found that can not be achieved processes of control
But in this every time handleLoadPackage (package APP) will destroyed it is big problem that an application should only need calls a radio receiver right process be when
I thought today that I could do again maybe it
I now is into 2 divided BroadReceiver
Ordered broadcast Send
First received call setResultExtras
Then back receive the direct unibroadcever to self
Bundle extras = getResultExtras (false);
If (extras! = null || extras.getBoolean (UNIRECEIVER, false)) {
Utils.Log ("log off broadcast a" + context + "," + this);
Context.unregisterReceiver (this);
Return;

**Comment by rovo89** [comment]
Sorry, but I really don't understand what you are trying to do and why. This is a complex topic and there are various complex ways to achieve things, but it requires understanding the goal

**Comment by qssq666123** [comment]
I just think of various ways to use the broadcast recipients to dynamically modify the variables but I found that the problem of duplicate registration is difficult to solve
An application restart will register a new at handleLoadPackage, I can not determine whether the registration has been
Want to use AIDL also solve the problem of cancellation
I hope you can provide some examples of other methods other than using local storage. I am more stupid
