### ISSUE TITLE
xposed module how to load so lib of the app process itself?

### ISSUE THREAD

**Issue by qssq666123** [rovo89/XposedBridge#146]
[https://github.com/rovo89/XposedBridge/issues/134 ](url)
I would also like to ask this question
How to call the so Library of the app process itself?
I want to use  at  findHookMethod logic inside JNI

I tried to call the app itself within the hook callback static class UnsatisfiledLinkError
But I'm not hook but app itself activity call Jni code is normal.
They do not belong to the same process so there is no way to solve this problem?

Hehe I English expression is not as I code without borders
```
package cn.test.aaa
public class Main extends MainHandlerPackage implements IXposedHookLoadPackage,  {
 
            

                        @Override
                        public void handleLoadPackage(LoadPackageParam loadPackageParam) {
                 
JNIPro.getDuration();// UnsatisfiledLinkError
                        }

}
package cn.test.aaa
public class JNIPro {
    static {
        System.loadLibrary("native-lib");
    }  public static native long getDuration();
}

package cn.test.aaa
public class mYActivity extends Activity{
public void   onCreate(Bundle bundle){
   JniPro.  getDuration();//There is no problem with this call 
}

```

I want to write this reason or prevent some users illegally packaged my program..

**Comment by rovo89** [comment]
Did you try using System.load() as suggested in the other issue? loadLibrary() can't work for the reasons mentioned there.

**Comment by qssq666123** [comment]
Well, it seems only to use absolute path
But I do not know how to use Android own command to get app Lib

Hook or trouble is still too low efficiency may be the reason for the xposed frame mechanism.. I can think of is hook or fill in /data/data/packagename/lib/ ...

**Comment by liudongmiao** [comment]
You must know current classloader. It should be a subclass of basedexclassloader, you can use reflect to modify private pathList which including the private nativeLibraryDirectories.

**Comment by netstu** [comment]
@rovo89  
 i use System.load() , but don't work on some phones

**Comment by rovo89** [comment]
> i use System.load() , but don't work on some phones

OK, were you able to find out the reason and a possible fix?
