### ISSUE TITLE
About XSharedPreference on Android 7.0

### ISSUE THREAD

**Issue by zzyandzzy** [rovo89/XposedBridge#150]
Hello, thank you for developing such a 6 framework,I have a problem in the use of the process.
Android N can not be used SharedPreferences sp = Context.getSharedPreferences("xxx",Context.MODE_WORLD_READABLE);Resulting in XSharedPreference can not read the contents of the file,How to solve this problem?Thank you

**Comment by rovo89** [comment]
There is no Xposed for Nougat.

**Comment by zzyandzzy** [comment]
（｡ò ∀ ó｡）...
