### ISSUE TITLE
How can I hook a anonymous class like ....

### ISSUE THREAD

**Issue by thenullvector** [rovo89/XposedBridge#152]
Hi, I got a trouble .. really really hassle me
I wanna hook class blablabla's method, anyone knows it ?
`Class a
{
    public void onCreate(Bundle b)
    {
         ...
         this.xxx.setOnClickListener( new blablabla () { method A, method B });
         ...
    }
}`

**Comment by rovo89** [comment]
The class names for anonymous classes are generated by the Java compiler. So you'll need to decompile the APK to find out the name (probably something like `a$1`) and then hook the method with that.
