### ISSUE TITLE
Request su in handleLoadPackage ?

### ISSUE THREAD

**Issue by suraj0208** [rovo89/XposedBridge#154]
For one of my modules I need to request su in handleLoadPackage(). Actually I need to access database of other app for which su is necessary. Is it a bad practice ? by doing so zygote asks for su permissions if we are using supersu by chainfire. For cyanogen supersu there's no such request by zygote. 

So in short
is it bad practice to request su in handleLoadPackage?
if it is what is the best alternative to handle such situation?

Thanks in advance.

**Comment by MolotovCherry** [comment]
Su is able to provide root during boot, but you need to check the relevant 'enable su during boot' option. I believe that permission also has to have been granted before in the past (not completely sure about that)

Whether it's bad practice I cannot be completely sure (I'm not a seasoned dev yet), but it seems to me that if there is any alternative way to do so, it should be done. It seems that using su during boot in such a way is a pretty nasty workaround, and also cumbersome for the end user.

Note: This applies to SuperSU, don't know about other alternative su implementations

**Comment by rovo89** [comment]
If you have a legit reason to use root, then I'd say why not. You can see your module as an extension to the app you're hooking, so if the app is lacking some functionality which you add with your module and which requires root, then go ahead.
