### ISSUE TITLE
calling a method from another class (with no context/instance/etc)

### ISSUE THREAD

**Issue by 1LineAtaTime** [rovo89/XposedBridge#156]
I have hooked a function from a class (w.class) and I want to call another function from another class (x.class). However, this x.class does not have any context or instance.
I tried searching XDA, Google and Github, but couldn't solve my problem. The closest thing I found was https://forum.xda-developers.com/xposed/findclass-returning-java-lang-class-t2853108 but as I stated, I do not have a context or instance.

My w.class is:
```java
final class w
  extends Thread
{
  private Handler b = new Handler();
  
  w(SplashActivity paramSplashActivity) {}
  
  public final void run()
  {
    this.b.postDelayed(new x(this), 2000L);
    super.run();
  }
}
```

and the x.class is
```java
final class x
  implements Runnable
{
  x(w paramw) {}
  
  public final void run()
  {
    w.a(this.a).startActivity(new Intent(w.a(this.a).getApplicationContext(), pack.class));
  }
}
```

I have hooked the run() function from w.class, but I don't know how to call the run() method from x.class.

My Xposed module looks like this:
```java
XposedHelpers.findAndHookMethod("com.pack.w", lpparam.classLoader, "run", new XC_MethodReplacement() {
               @Override
                protected Object replaceHookedMethod(MethodHookParam param) {
                XposedBridge.log(TAG + " we are replacing... " );
                Class<?> classstart = XposedHelpers.findClass("com.pack.x", lpparam.classLoader);
                Context context = (Context) XposedHelpers.getObjectField(param.thisObject, "context");
                Object class2Instance = XposedHelpers.newInstance(classstart, context);
                XposedHelpers.callMethod(class2Instance, "run");
                XposedBridge.log(TAG + " replacing should be done " );
                return null;
                 }
              });
```
but since there is no "context" in x.class, it does not get the object and I cannot use callMethod()
any ideas, please? I am bit stucked

P.S.: Btw, the main goal is to remove the 2000ms wait from "postDelayed()". I did it through .smali already, but wanted to learn how to do it in Xposed.

**Comment by josephcsible** [comment]
GitHub is for actual bugs in Xposed. This is being handled at https://forum.xda-developers.com/xposed/calling-method-class-t3547398 so this can be closed.
