### ISSUE TITLE
How debug xposed modules?

### ISSUE THREAD

**Issue by Radzhab** [rovo89/XposedBridge#157]
Ex, i want develop module. How its debug in Android Studio?

**Comment by rovo89** [comment]
There's no easy way to do that, see this question:
https://github.com/rovo89/XposedBridge/issues/138#issuecomment-267774617

**Comment by liudongmiao** [comment]
It's possible, however, I don't recommend. 

1. You must know the process that running your xposed module.
2. You must run that process with debug on. (The simplest should be let all process including system_server debuggable, through property)
3. Attach it in Android studio.

**Comment by Radzhab** [comment]
@liudongmiao How attach it to Android Studio? Can you share tutorial

**Comment by MPeti1** [comment]
UPDATE: I've found an easy solution and written about it in the Issue linked by rovo89
