### ISSUE TITLE
how to modify custom class while the method hook 

### ISSUE THREAD

**Issue by 838514984** [rovo89/XposedBridge#164]
etc:
public class MyClass{
 public int age;
 public String name;
}

public class BlaBla{
  public void hookMe(MyClass myClass){
    Log.e("xxx",myClass.age+"   "+myClass.name);
  }
}

-----------------------------------------------------------------------------------
我把MyClass复制放到同一目录下，也是不行的。
I copy 'MyClass' with the same packagename to the moudle project ,but is wrong ,classCast error.
 if you give me any advice ,i will be very appreciate.
------------------------------------------------------------------------------------
Class<?> clz=XposedHelpers.findClass("xxx.MyClass",lpparam.classLoader);
XposedHelpers.findAndHookMethod("xxx.BlaBla", lpparam.classLoader, " hookMe",clz,new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    MyClass myClass= (MyClass) param.args[0];      //cast error
                    myClass.name="hello";
                   
                }

                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    super.afterHookedMethod(param);

                }
            });

**Comment by wanam** [comment]
Are "MyClass" class sources compiled inside your module? they shouldn't.

**Comment by 838514984** [comment]
No, there is only one moudle which should be hooked has "MyClass".
In XposedMoudle, I was trying to get MyClass parameters and modify him, so I  copy MyClass with the Package into the XposedMoudle ,but its not work.

**Comment by wanam** [comment]
I don't understand what you are trying to do? you are making a module to hook an other module? or just one module trying to hook it self?

**Comment by 838514984** [comment]
yeah yeahyeah ,making a moudle to hook an other moudle,the other moudle has a custom class.
just list: 
class HookMeClass{
    public void hookMe(CustomClass customClass){
    }
}

hook this method is not diffcult ,i just wanner know how to modify this parameter while you've hook.
----------------------------------------------------------------------------------------------------------------

**Comment by wanam** [comment]
I don't know why would you do that, but i guess as i said before you should just reference "MyClass", and do not compile it inside the hooker module.

**Comment by 838514984** [comment]
if you dont transfer object to a specific class,how can you modify this class?
haha,maybe you do not understand me what i want to do.thanks anyway

**Comment by 838514984** [comment]
Suddenly thought, we can use reflection
