### ISSUE TITLE
How can I hook FileInputStream?

### ISSUE THREAD

**Issue by ShuaigeLee** [rovo89/XposedBridge#166]
I want to hook the FileInputStream/FileOutputStream to encrypt files. 
But I got a class not fount error when I used the XposedBridge.BOOTCLASSLOADER. 
How can I hook these class.
Thank you！

**Comment by aviraxp** [comment]
Use application's own classloader instead.

**Comment by ShuaigeLee** [comment]
Thanks for your reply. But I'm a novice, could you talk to me how to use the application's classloader in details？

**Comment by aviraxp** [comment]
If you use Xposed hooking method in interface initZygote(), use null for classloader.

If in interface handleLoadPackage(), use lpparam.classLoader (lpparam refers to XC_LoadPackage.LoadPackageParam, like this:

```
Class<?> blockGuardOsClz = XposedHelpers.findClass("libcore.io.BlockGuardOs", lpparam.classLoader);
XposedBridge.hookAllMethods(blockGuardOsClz, "connect", blockGuardOsHook);
```

**Comment by ShuaigeLee** [comment]
I used wrong package name. There is no error when I using the correct pakcage. 
I'm so sorry for this stupid question.
