### ISSUE TITLE
how to get object's filed's filed?

### ISSUE THREAD

**Issue by netstu** [rovo89/XposedBridge#167]
E/Xposed(5245): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:848)

```java
class a {
   private b bb;

   test() {

    }
}

class b {
     private c cc;
}

class c {
    d dd;
}
```

i want to hook a object's test() method, in this hook, i want to get class c's filed d?

```java
beforeHookedMethod (MethodHookParam param) {
      Object b = getObjectFiled(param.thisObject, "b");
      Object c = getObjectFiled(b, "c");  // this is error, how to do ?
}
```

**Comment by rovo89** [comment]
Your pseudo-hook doesn't really match to the pseudo-code. Your fields are named `bb`, `cc` and `dd`, so you obviously have to use these names in your hook as well. Anyway, if this question still needs an answer, please reopen with real code and the full error message.
