### ISSUE TITLE
How to find method with extended arguments

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#170]
`public void sendScreenshotMessage(TLRPC.EncryptedChat encryptedChat, ArrayList<Long> random_ids, TLRPC.Message resendMessage)`

**Comment by aviraxp** [comment]
You needn't hook there. Check my No TelegramScreenshot app on xposed repo.

**Comment by daimoniuma** [comment]
Checked.
[https://github.com/aviraxp/No-Screenshot-Notification-for-Telegram](url)
It's empty. Something else? 😅

Anyway. Is it possible/impossible to hook such methods? Just for education.

**Comment by daimoniuma** [comment]
Seems like I need to use findClass to create 2 classes before searching it. Is it?

**Comment by aviraxp** [comment]
XposedBridge.hookAllMethods.

**Comment by daimoniuma** [comment]
Just for clarification: I could create 2 classes (TLRPC.EncryptedChat and TLRPC.Message) and findExact, right?

**Comment by rovo89** [comment]
>If you don't have the class reference, you can simply use the full class name as a string, e.g. java.lang.String or com.example.MyClass. It will be passed to findClass(String, ClassLoader) with the same class loader that is used for the target method, see its documentation for the allowed notations. 

http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#findAndHookMethod(java.lang.String,%20java.lang.ClassLoader,%20java.lang.String,%20java.lang.Object...)

**Comment by daimoniuma** [comment]
> You can simply use the full class name as a string.

So easy! Nice!
