### ISSUE TITLE
findAndHook anonymous classes

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#173]
I decompiled some app and faced with ClassA, ClassA$1, ClassA$2, etc. Method which I want to hook in ClassA$2. How to find it?

**Comment by rovo89** [comment]
Exactly like that, the class name is ClassA$2 etc.

**Comment by daimoniuma** [comment]
Of course I tried. Class not found. 🙄

**Comment by rovo89** [comment]
Please show what exactly you tried.

**Comment by daimoniuma** [comment]
I used default classloader. Do I need to use other?

**Comment by daimoniuma** [comment]
```
package secret;

import android.view.ActionMode;
import android.view.ActionMode.Callback;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

class h$2
  implements ActionMode.Callback
{
  h$2(h paramh) {}
  
  public boolean onCreateActionMode(ActionMode paramActionMode, Menu paramMenu)
  {
    ...
    return true;
  }
```
`findAndHookMethod("secret.h$2", lpparam.classloader, "onCreateActionMode", ActionMode.class, Menu.class...`

**Comment by daimoniuma** [comment]
That's my typo. I'm become blind. Sorry about that.

**Comment by rovo89** [comment]
Where was the typo? I didn't see it yet.

**Comment by daimoniuma** [comment]
Spare my blushes. It was the stupid typo like "app.view.h$2" when it's "app.h$2". I don't know how I missed it. 😒 

By the way. How you are feeling yourself? Whole humanity is waiting for Xposed for Nougat.

Okay, I know that's nagging, but... But I'm dying. 🌚 I'd like to see Xposed for Nougat before it will. 🌚
