### ISSUE TITLE
hook final method

### ISSUE THREAD

**Issue by wangyuan0217** [rovo89/XposedBridge#178]
Can Xposed hook the method that with final?
I just write a test for that and I get an error like :noSuchMethod

**Comment by rovo89** [comment]
Hooking a final method is possible and works the same way like any hooking other method. Make sure you follow the hints given in the docs: http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#findAndHookMethod(java.lang.String,%20java.lang.ClassLoader,%20java.lang.String,%20java.lang.Object...)

**Comment by wangyuan0217** [comment]
thanks
