### ISSUE TITLE
I want to Hook a method,but it has interface param,HELP! 

### ISSUE THREAD

**Issue by the7urn1ph34d** [rovo89/XposedBridge#179]
# Method i want to hook:

Class:javax.crypto.Cipher 

`void  init(int opmode,  Key key)`

---

As you see,"key" parameter is a java.security Interface,and also has All Known Subinterfaces: 
DHPrivateKey,DHPublicKey,DSAPrivateKey,DSAPublicKey,ECPrivateKey,ECPublicKey,PBEKey,PrivateKey ， PublicKey,RSAMultiPrimePrivateCrtKey,RSAPrivateCrtKey, RSAPrivateKey,RSAPublicKey,**SecretKey**

People often use it such as:

`Cipher.init(Cipher.ENCRYPT_MODE,secretKey)`
# So my question is:
Whether i can hook this method like this:

`
XposedHelpers.findAndHookMethod(
                        "javax.crypto.Cipher ",
                        lpparam.classLoader,
                        "init",
                        int.class,
                        "java.security.key",
                       new XC_MethodHook(){};)
`

If not please tell me what should i hook this method.

**Comment by rovo89** [comment]
It's still the same method definition, no matter with which exact values the method is called. So your attempt to hook it should succeed, however the `Key` should probably be uppercase. Besides that, all of these classes should be available from the Android framework itself, so you can probably use:
`findAndHookMethod(Cipher.class, init", int.class, Key.class, new XC_MethodHook(){});`

**Comment by the7urn1ph34d** [comment]
Thank you @rovo89 ,your reply are always timely.   : )
