### ISSUE TITLE
How to download XposedBridgeApi-40

### ISSUE THREAD

**Issue by MlgmXyysd** [rovo89/XposedBridge#180]
I want to build an module use Api-40 or 42.
There isn't download link at the internet.

**Comment by rovo89** [comment]
You should use a new API version. If you really want to make your module available to users with an ancient Xposed version, you can still compile your module with a API v53 and set your `xposedminversion` to `40`. As long as you don't use things like `findAndHookConstructor()`, which have been added in a later version, that will work. You can check here for details when certain functions have been added:
http://api.xposed.info/
https://raw.githubusercontent.com/rovo89/XposedBridge/art/app/doclib/api/changelog.txt
Obviously, you'll need to test this well to be sure.
