### ISSUE TITLE
Cant getObjectField from variable in method

### ISSUE THREAD

**Issue by JojiiOfficial** [rovo89/XposedBridge#181]
I tried to get a variable which is declared and only available in a certain method. I hooked this method but i want to get the ObjectField.

For example this is the Class:

`public class hi(){
    String hello  = "hello"; //This variable I can get

    public void hie(){
       String hello2 = "hi"; //This Variable I can not get using XposedHelpers.getObjectField(param.thisObject,"hello2");
    }
}

and this the Hookmethod:
`Class<?> ProfileInfoClass = XposedHelpers.findClass("com.hi",lpparam.classLoader);     
XposedBridge.hookAllMethods(ProfileInfoClass,"hie",new XC_MethodHook() {
     @Override
     protected void afterHookedMethod(MethodHookParam param) throws Throwable {
          super.afterHookedMethod(param);
          String s = (String)XposedHelpers.getObjectField(param.thisObject,"hello2"); //not found
     }
});
` 

Thanks. Jojii
How can I get Access to variables in methods?

**Comment by wanam** [comment]
You can't, you need to do it otherwise, see how this field is set, and try to do the same using method parameters and class fields.

**Comment by JojiiOfficial** [comment]
This Method has no parameters and it is only used in this method. Maybe I could get this object by findViewByID but I do not have the parent View/Layout. Does this might work?

**Comment by JojiiOfficial** [comment]
My destiny is, that I can view other ProfilePictures from my contacts in WhatsApp and now I try to get the ImageView. This is set in one method (i guess) but I dont get access and I dont any other way to do this

**Comment by wanam** [comment]
Can you put a real case with the method body and what you want to do?

**Comment by RealJojii** [comment]
What do you mean with real case?
I want to get the ImageView an change the resource of it to another image.

**Comment by JojiiOfficial** [comment]
`final Class<?> ContactinfoClass = 
XposedHelpers.findClass("com.whatsapp.ContactInfo",lpparam.classLoader);

        XposedHelpers.findAndHookMethod(ContactinfoClass, "t", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                super.afterHookedMethod(param);
                ImageView iv = (ImageView) XposedHelpers.getObjectField(param.thisObject, "localImageView");
                if(iv == null){
                    XposedBridge.log("iuv is nulll");
                    return;
                }
                iv.setImageResource(R.drawable.ic_info_black_24dp);
            }
        });`


this is my code, what I tried. I need the ImageView to change the resource.

**Comment by wanam** [comment]
You can do something like this:
```
		XposedHelpers.findAndHookMethod(ContactinfoClass, "t", new XC_MethodHook() {
		        @Override
		        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
		            Activity activity = (Activity) param.thisObject;
		            ImageView iv = (ImageView) activity.findViewById(R.id.encryption_indicator);
		            if(iv == null){
		                XposedBridge.log("iv is nulll");
		                return;
		            }
		            iv.setImageResource(R.drawable.ic_info_black_24dp);
		        }
		   });
```

**Comment by JojiiOfficial** [comment]
Thanks!
What should be `encryption_indicator`?

**Comment by wanam** [comment]
@RealJojii Your imageView id.

**Comment by JojiiOfficial** [comment]
You mean the WhatsAppImageViewId?

**Comment by wanam** [comment]
I don't know what "WhatsappImageId" should mean for you, but i'm talking about the resource id of your image on the layout file, please read the official doc on how to use findViewById : https://developer.android.com/reference/android/view/View.html

By the way if the "ImageResource" is not set with Java code, you can still change it by hooking its parent layout instead of hooking the Java part.

**Comment by JojiiOfficial** [comment]
With WhatsAppImageViewId I mean the ImageView from the method I hooked, from the Whatsapp Activity

**Comment by JojiiOfficial** [comment]
But `private` methods and `private static` methods I can hook, right?

**Comment by wanam** [comment]
Yes.

**Comment by JojiiOfficial** [comment]
Because now Iam hooking an other method and XposedLog says that there is no such function :/

**Comment by rovo89** [comment]
I guess you have sorted this out meanwhile. If not, please reopen with more context.
