### ISSUE TITLE
API for Native

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#183]
Some thing is hidden from Xposed: [jni_internal.cc](https://android.googlesource.com/platform/art/+/master/runtime/jni_internal.cc). Is it possible to include native hooking?

**Comment by rovo89** [comment]
Not sure what you mean. You *can* hook native (JNI) methods.

**Comment by daimoniuma** [comment]
How? 😯 I know only findAndHook method which should be applied to Java. I also can hook calls from Java to Native and vice versa, but methods execution into JNI... 🤔

**Comment by rovo89** [comment]
> I also can hook calls from Java to Native and vice versa

Exactly that **is** JNI. So what else do you want to hook?

**Comment by daimoniuma** [comment]
So it's a wrong source file. I'm not a big expert here. 😾 You know, some apps can be completely without java classes (NativeActivity). I meant hooking directly into native.

**Comment by rovo89** [comment]
No, that's not possible with Xposed and never will be.

**Comment by daimoniuma** [comment]
😿
