### ISSUE TITLE
xposed framework 87 installed but not active

### ISSUE THREAD

**Issue by findmenowzero** [rovo89/XposedBridge#185]
after update miui 9 6.0.1 xposed give error phone mi4 
09-13 14:08:41.053 I/Xposed  (29511): Starting Xposed version 87, compiled for SDK 23
09-13 14:08:41.053 I/Xposed  (29511): Device: MI 4W (Xiaomi), Android version 6.0.1 (SDK 23)
09-13 14:08:41.053 I/Xposed  (29511): ROM: MMB29M
09-13 14:08:41.053 I/Xposed  (29511): Build fingerprint: Xiaomi/cancro_wc_lte/cancro:6.0.1/MMB29M/7.9.7:user/release-keys
09-13 14:08:41.053 I/Xposed  (29511): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-13 14:08:41.053 I/Xposed  (29511): SELinux enabled: yes, enforcing: yes
09-13 14:08:41.066 I/Xposed  (29511): -----------------
09-13 14:08:41.067 I/Xposed  (29511): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-13 14:08:41.272 I/Xposed  (29511): Detected ART runtime
09-13 14:08:41.274 I/Xposed  (29511): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-13 14:08:41.438 E/Xposed  (29511): Errors during Xposed initialization
09-13 14:08:41.438 E/Xposed  (29511): java.lang.NoSuchFieldError: no "J" field "BOOT_START_TIME" in class "Lde/robv/android/xposed/XposedBridge;" or its superclasses

**Comment by findmenowzero** [comment]
![screenshot_2017-09-10-22-41-19-120_de robv android xposed installer](https://user-images.githubusercontent.com/28023198/30392597-ee83c20a-98da-11e7-8ebf-536290f90f6b.png)

**Comment by rovo89** [comment]
I can't give support for custom versions of Xposed. There aren't any references to `BOOT_START_TIME` in the original Xposed code at all.

**Comment by Sygmei** [comment]
Got the exaxt same problem with original version of Xposed v88

```
10-12 08:37:01.822 I/Xposed  (  345): -----------------
10-12 08:37:01.822 I/Xposed  (  345): Starting Xposed version 88, compiled for SDK 23
10-12 08:37:01.822 I/Xposed  (  345): Device: MI 4W (Xiaomi), Android version 6.0.1 (SDK 23)
10-12 08:37:01.822 I/Xposed  (  345): ROM: xiaomi.eu
10-12 08:37:01.822 I/Xposed  (  345): Build fingerprint: Xiaomi/cancro_wc_lte/cancro:6.0.1/MMB29M/V8.1.6.0.MXDMIDI:user/release-keys
10-12 08:37:01.822 I/Xposed  (  345): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-12 08:37:01.822 I/Xposed  (  345): SELinux enabled: yes, enforcing: yes
10-12 08:37:02.843 I/Xposed  (  345): -----------------
10-12 08:37:02.843 I/Xposed  (  345): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-12 08:37:03.423 I/Xposed  (  345): Detected ART runtime
10-12 08:37:03.450 I/Xposed  (  345): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-12 08:37:03.620 E/Xposed  (  345): Errors during Xposed initialization
10-12 08:37:03.620 E/Xposed  (  345): java.lang.NoSuchFieldError: no "J" field "BOOT_START_TIME" in class "Lde/robv/android/xposed/XposedBridge;" or its superclasses
```

**Comment by rovo89** [comment]
@Sygmei See #198. It's still unclear where that field is coming from, propably some crazy MIUI stuff again. That's why MIUI has such low priority for me...

**Comment by Sygmei** [comment]
Haha I can understand that MIUI is not the easiest ROM to work with. 
If you need any help for this problem I'm available :)
