### ISSUE TITLE
Xposed 83 and up not in the Maven repo

### ISSUE THREAD

**Issue by coolnickname** [rovo89/XposedBridge#186]
[https://jcenter.bintray.com/de/robv/android/xposed/api/](https://jcenter.bintray.com/de/robv/android/xposed/api/)

**Comment by rovo89** [comment]
The latest API version is 82. API version != Xposed version:

> Generally, the API version equals the Xposed version that it was built on. However, only some framework changes actually result in API changes, as you can see in the change log. I only publish a new API version when there were API changes, and I try to keep them compatible with existing modules as good as possible. So when you build a module with API version 82, it will most likely also work with Xposed version 90.

https://github.com/rovo89/XposedBridge/wiki/Using-the-Xposed-Framework-API#api-versions
