### ISSUE TITLE
MODE_WORLD_READABLE limit on Nougat

### ISSUE THREAD

**Issue by aviraxp** [rovo89/XposedBridge#191]
From Nougat, we will no longer able to use MODE_WORLD_READABLE, which is used by many modules to keep preferences readable. We can get around it with some hacks, or switch to other stuff (content providers) instead. But may I ask if you can add a hook in XposedBridge to restore that flag's usage?

**Comment by rovo89** [comment]
This would have the side-effect that not only modules would be able to use it, but also regular apps. For those, I think the warning makes sense. A better workaround would be to set your target SDK version lower than 24, or if you really can't do this for some reason, hook `ContextImpl.checkMode()` only for your own app.

That said, I'm totally aware that there needs to be a better way. You already mentioned content providers, but it would be great to have a solution that even works in `initZygote()`, where no `Context` is available and the system server isn't running yet.
