### ISSUE TITLE
Xposed for Nougat on bq Aquaris X5 Plus doesn't load modules

### ISSUE THREAD

**Issue by krakan** [rovo89/XposedBridge#193]
The Xposed framework seems to install nicely but I don't get any differences. In the Xposed Installer app there are a bunch of modules selected and configured but none of them seem to do anything. When booting I get the following lines in the log:

```
10-08 21:52:58.387   672   672 I Xposed  : Detected ART runtime
10-08 21:52:58.401   672   672 I Xposed  : Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-08 21:52:58.501   672   672 I Radio-JNI: register_android_hardware_Radio DONE
10-08 21:52:58.649   683   683 V NatController: runCmd(/system/bin/iptables -w -W 10000 -F natctrl_FORWARD) res=0
10-08 21:52:58.659   683   683 V NatController: runCmd(/system/bin/ip6tables -w -W 10000 -F natctrl_FORWARD) res=0
10-08 21:52:58.669   683   683 V NatController: runCmd(/system/bin/iptables -w -W 10000 -A natctrl_FORWARD -j DROP) res=0
10-08 21:52:58.679   683   683 V NatController: runCmd(/system/bin/iptables -w -W 10000 -t nat -F natctrl_nat_POSTROUTING) res=0
10-08 21:52:58.698   683   683 V NatController: runCmd(/system/bin/ip6tables -w -W 10000 -t raw -F natctrl_raw_PREROUTING) res=0
10-08 21:52:58.708   683   683 V NatController: runCmd(/system/bin/iptables -w -W 10000 -F natctrl_tether_counters) res=1
10-08 21:52:58.716   672   672 E Xposed  : Cannot load any modules because /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list was not found

```
I notice that there is an empty `modules.list` in `/data`**/user/**`0/de.robv.android.xposed.installer/conf/modules.list ` which do get populated when I unselect and reselect any module in the installer. Moving that file to the `/data/user_de/...` path does nothing.

Here's a boot log after a fresh uninstall/install:
[logcat_2017-10-08.txt](https://github.com/rovo89/XposedBridge/files/1367194/logcat_2017-10-08.txt)

**Comment by rovo89** [comment]
Sounds like you're not using the latest Xposed Installer, you need to have version 3.1.2.

**Comment by krakan** [comment]
Ah, yes, of course. Thank you and sorry for wasting your time!
