### ISSUE TITLE
is any package here that can use in Mi6 Miui9? 

### ISSUE THREAD

**Issue by 838514984** [rovo89/XposedBridge#194]
i flashed this (xposed-v88-sdk25-arm64.zip ) package,and then my phone can't boot completely.boot loop.
is anybody use xposed in Mi6 Miui9 official rom successfully?
~~

**Comment by wanam** [comment]
Did you try with checked "Disable resources hooking" option on xposed installer?
I'm not sure about miui 9, but older miui versions have a heavy changes on res management.

**Comment by 838514984** [comment]
@wanam yeah,i have tried.it is not working~

**Comment by rovo89** [comment]
Does v88.1 fix it? If not, please post the full logs as described here: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by 838514984** [comment]
@rovo89 i can't get any log......
using via adb method,me phone just stay in the booting animation activity and the adb can't detect my device.
using via Xposed method,i have already created an empty file in specified folder..after installing v88.1,booting  and uninstalling.the file has no content....
my phone is XiaoMi6,Miui9, 7.1.1..

**Comment by 838514984** [comment]
https://github.com/838514984/dairy/blob/master/file/xposed_error_20171011_134714.log
is this log helpful?

**Comment by 838514984** [comment]
https://github.com/838514984/dairy/blob/master/file/xposed_error_20171011_134714.log
@rovo89 is this log helpful?

**Comment by rovo89** [comment]
Yes, at least a bit. Unfortunately, I don't see why generating those files has failed. Could you please try to get a full log? https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs

**Comment by 838514984** [comment]
i  have tried many times but couldn't get any log from the mothed above
maybe XiaoMi6 official rom is deep custom-made.
