### ISSUE TITLE
Xposed installed but not active on Redmi note 3

### ISSUE THREAD

**Issue by Naveenlucky** [rovo89/XposedBridge#196]
Hi,
I have installed xposed framework v87.1 on my redmi note 3 running on marshmallow MIUI 9 Global beta. Correct framework is installed with the latest xposed app. Rebooted many times but it says xposed installed but not active. Following is the log

10-10 20:24:21.952 I/Xposed  (  650): -----------------
10-10 20:24:21.952 I/Xposed  (  650): Starting Xposed version 87.1 (MIUI edition by SolarWarez / 20170612), compiled for SDK 23
10-10 20:24:21.952 I/Xposed  (  650): Device: Redmi Note 3 (Xiaomi), Android version 6.0.1 (SDK 23)
10-10 20:24:21.953 I/Xposed  (  650): ROM: MMB29M
10-10 20:24:21.953 I/Xposed  (  650): Build fingerprint: Xiaomi/kenzo/kenzo:6.0.1/MMB29M/7.9.22:user/release-keys
10-10 20:24:21.953 I/Xposed  (  650): Platform: arm64-v8a, 64-bit binary, system server: yes
10-10 20:24:21.953 I/Xposed  (  650): SELinux enabled: yes, enforcing: yes
10-10 20:24:22.973 I/Xposed  (  650): -----------------
10-10 20:24:22.973 I/Xposed  (  650): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-10 20:24:23.298 I/Xposed  (  650): Detected ART runtime
10-10 20:24:23.325 I/Xposed  (  650): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-10 20:24:23.349 I/Xposed  (  650): MIUI detected... Make some patch...
10-10 20:24:23.349 I/Xposed  (  650): All done!
10-10 20:24:23.461 E/Xposed  (  650): Errors during Xposed initialization
10-10 20:24:23.461 E/Xposed  (  650): java.lang.NoSuchFieldError: no "J" field "BOOT_START_TIME" in class "Lde/robv/android/xposed/XposedBridge;" or its superclasses
10-10 20:24:32.527 I/Xposed  (  651): -----------------
10-10 20:24:32.527 I/Xposed  (  651): Starting Xposed version 87.1 (MIUI edition by SolarWarez / 20170612), compiled for SDK 23
10-10 20:24:32.527 I/Xposed  (  651): Device: Redmi Note 3 (Xiaomi), Android version 6.0.1 (SDK 23)
10-10 20:24:32.527 I/Xposed  (  651): ROM: MMB29M
10-10 20:24:32.528 I/Xposed  (  651): Build fingerprint: Xiaomi/kenzo/kenzo:6.0.1/MMB29M/7.9.22:user/release-keys
10-10 20:24:32.528 I/Xposed  (  651): Platform: arm64-v8a, 32-bit binary, system server: no
10-10 20:24:32.528 I/Xposed  (  651): SELinux enabled: yes, enforcing: yes
10-10 20:24:32.529 I/Xposed  (  651): -----------------
10-10 20:24:32.529 I/Xposed  (  651): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-10 20:24:32.743 I/Xposed  (  651): Detected ART runtime
10-10 20:24:32.761 I/Xposed  (  651): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-10 20:24:32.780 I/Xposed  (  651): MIUI detected... Make some patch...
10-10 20:24:32.780 I/Xposed  (  651): All done!
10-10 20:24:56.002 E/Xposed  (  651): Unable to stat fd 3 : Permission denied
10-10 20:24:57.786 E/Xposed  (  651): Unable to stat fd 3 : Permission denied

**Comment by rovo89** [comment]
That's an unofficial version, which I obviously can't support.
