### ISSUE TITLE
Catch XposedHelpers.ClassNotFoundException

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#197]
How to catch it? AIDE writes error about unknown type. Is it same as system ClassNotFoundException?
```
try {
			Class<?> mClass = XposedHelpers.findClass(className, lpparam.classLoader);
		} catch (XposedHelpers.ClassNotFoundException e) {
			
		}
```

**Comment by rovo89** [comment]
It's actually `XposedHelpers.ClassNotFoundError`, not `XposedHelpers.ClassNotFoundException` (which indeed doesn't exist). The difference is that Exceptions must be declared as `throws` in the method (and **must** be caught by the caller), whereas Errors and RuntimeExceptions don't need to be declared, but can still optionally be caught.

**Comment by daimoniuma** [comment]
Wow, it was autosuggestion from AIDE. Didn't notice that here is Exception instead of Error at the end. Sorry. And congrats with Nougat release. 🎉

**Comment by daimoniuma** [comment]
Wow, it was autosuggestion from AIDE. Didn't notice that here is Exception instead of Error at the end. Sorry. And congrats with Nougat release. 🎉

**Comment by daimoniuma** [comment]
Wow, it was autosuggestion from AIDE. Didn't notice that here is "Exception" instead of "Error" at the end. Sorry. And congrats with Nougat release. 🎉
