### ISSUE TITLE
work good but the log show error

### ISSUE THREAD

**Issue by klcb2010** [rovo89/XposedBridge#199]
10-11 09:03:30.038 I/Xposed  (  959): -----------------
10-11 09:03:30.038 I/Xposed  (  959): Starting Xposed version 88.1, compiled for SDK 25
10-11 09:03:30.038 I/Xposed  (  959): Device: MI 6 (Xiaomi), Android version 7.1.1 (SDK 25)
10-11 09:03:30.038 I/Xposed  (  959): ROM: 45.0.A.7.90
10-11 09:03:30.038 I/Xposed  (  959): Build fingerprint: Sony/G8142/G8142:7.1.1/45.0.A.7.120/3798438998:user/release-keys
10-11 09:03:30.038 I/Xposed  (  959): Platform: arm64-v8a, 64-bit binary, system server: yes
10-11 09:03:30.038 I/Xposed  (  959): SELinux enabled: yes, enforcing: no
10-11 09:03:33.054 I/Xposed  (  959): -----------------
10-11 09:03:33.054 I/Xposed  (  959): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-11 09:03:40.482 I/Xposed  (  961): -----------------
10-11 09:03:40.482 I/Xposed  (  961): Starting Xposed version 88.1, compiled for SDK 25
10-11 09:03:40.482 I/Xposed  (  961): Device: MI 6 (Xiaomi), Android version 7.1.1 (SDK 25)
10-11 09:03:40.482 I/Xposed  (  961): ROM: 45.0.A.7.90
10-11 09:03:40.482 I/Xposed  (  961): Build fingerprint: Sony/G8142/G8142:7.1.1/45.0.A.7.120/3798438998:user/release-keys
10-11 09:03:40.482 I/Xposed  (  961): Platform: arm64-v8a, 32-bit binary, system server: no
10-11 09:03:40.482 I/Xposed  (  961): SELinux enabled: yes, enforcing: no
10-11 09:03:42.486 I/Xposed  (  961): -----------------
10-11 09:03:42.486 I/Xposed  (  961): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-11 09:04:06.383 I/Xposed  (  961): Detected ART runtime
10-11 09:04:06.385 I/Xposed  (  961): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-11 09:04:06.700 I/Xposed  (  961): Loading modules from /data/app/com.wrbug.gravitybox.nougat-1/base.apk
10-11 09:04:08.910 I/Xposed  (  961):   Loading class com.wrbug.gravitybox.nougat.GravityBox
10-11 09:04:08.911 I/Xposed  (  961): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
10-11 09:04:09.926 I/Xposed  (  961):   Loading class com.blanke.mdwechat.WechatHook
10-11 09:04:09.927 I/Xposed  (  961): Loading modules from /data/app/cn.wq.myandroidtoolsxposed-1/base.apk
10-11 09:04:11.277 I/Xposed  (  961):   Loading class cn.wq.myandroidtoolsxposed.XposedHook
10-11 09:04:11.278 I/Xposed  (  961): Loading modules from /data/app/com.fkzhang.qqxposed-1/base.apk
10-11 09:04:11.299 I/Xposed  (  961):   Loading class com.fkzhang.qqxposed.XposedInit
10-11 09:04:11.302 I/Xposed  (  961): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.CLON-1/base.apk
10-11 09:04:16.698 I/Xposed  (  961):   Loading class com.chelpus.XSupport
10-11 09:04:16.705 I/Xposed  (  961): Loading modules from /system/priv-app/com.oasisfeng.greenify/com.oasisfeng.greenify.apk
10-11 09:04:18.603 I/Xposed  (  961):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
10-11 09:04:18.604 I/Xposed  (  961):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
10-11 09:04:18.605 I/Xposed  (  961): Loading modules from /data/app/liubaoyua.poweramppatch-1/base.apk
10-11 09:04:18.719 I/Xposed  (  961):   Loading class liubaoyua.poweramppatch.MainHook
10-11 09:04:18.719 I/Xposed  (  961): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-11 09:04:18.764 I/Xposed  (  961):   Loading class com.fkzhang.wechatxposed.XposedInit
10-11 09:04:18.767 I/Xposed  (  961): Loading modules from /data/app/com.nijigenirubasho.mobiletailchanger-1/base.apk
10-11 09:04:18.962 I/Xposed  (  961):   Loading class com.nijigenirubasho.mobiletailchanger.Xpo
10-11 09:04:18.962 I/Xposed  (  961): Loading modules from /data/app/ce.hesh.wechatUI-1/base.apk
10-11 09:04:19.958 I/Xposed  (  961):   Loading class ce.hesh.wechatUI.MainHook
10-11 09:04:19.959 I/Xposed  (  961): Loading modules from /data/app/dev.ukanth.ufirewall-1/base.apk
10-11 09:04:22.543 I/Xposed  (  961):   Loading class dev.ukanth.ufirewall.xposed.XposedInit
10-11 09:04:22.546 I/Xposed  (  961): Loading modules from /data/app/ma.wanam.smartnetwork-1/base.apk
10-11 09:04:23.587 I/Xposed  (  961):   Loading class ma.wanam.smartnetwork.Xposed
10-11 09:04:23.589 I/Xposed  (  961): Loading modules from /data/app/com.sorcerer.sorcery.iconpack-2/base.apk
10-11 09:04:23.777 I/Xposed  (  961):   Loading class com.sorcerer.sorcery.iconpack.apply.xposed.Xposed
10-11 09:04:23.787 I/Xposed  (  961): Sorcery Xposed: new sorcery started
10-11 09:04:23.797 I/Xposed  (  961): Loading modules from /data/app/com.yyxx.wechatfp-1/base.apk
10-11 09:04:25.524 I/Xposed  (  961):   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
10-11 09:04:25.524 I/Xposed  (  961): Loading modules from /data/app/com.mhook.dialog-1/base.apk
10-11 09:04:25.717 I/Xposed  (  961):   Loading class com.mhook.dialog.Module
10-11 09:04:52.299 I/Xposed  (  959): Detected ART runtime
10-11 09:04:52.301 I/Xposed  (  959): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-11 09:04:52.451 I/Xposed  (  959): Loading modules from /data/app/com.wrbug.gravitybox.nougat-1/base.apk
10-11 09:04:52.464 I/Xposed  (  959):   Loading class com.wrbug.gravitybox.nougat.GravityBox
10-11 09:04:52.474 I/Xposed  (  959): GB:Hardware: qcom
10-11 09:04:52.474 I/Xposed  (  959): GB:Product: sagit
10-11 09:04:52.474 I/Xposed  (  959): GB:Device manufacturer: Xiaomi
10-11 09:04:52.474 I/Xposed  (  959): GB:Device brand: Xiaomi
10-11 09:04:52.474 I/Xposed  (  959): GB:Device model: MI 6
10-11 09:04:52.477 I/Xposed  (  959): GB:Device type: phone
10-11 09:04:52.477 I/Xposed  (  959): GB:Is MTK device: false
10-11 09:04:52.477 I/Xposed  (  959): GB:Is Xperia device: false
10-11 09:04:52.477 I/Xposed  (  959): GB:Is Moto XT device: false
10-11 09:04:52.478 I/Xposed  (  959): GB:Is OxygenOS 4.5 ROM: false
10-11 09:04:52.478 I/Xposed  (  959): GB:Has Lenovo custom UI: false
10-11 09:04:52.478 I/Xposed  (  959): GB:Has telephony support: true
10-11 09:04:52.478 I/Xposed  (  959): GB:Has Gemini support: false
10-11 09:04:52.478 I/Xposed  (  959): GB:Android SDK: 25
10-11 09:04:52.478 I/Xposed  (  959): GB:Android Release: 7.1.1
10-11 09:04:52.478 I/Xposed  (  959): GB:ROM: 45.0.A.7.90
10-11 09:04:52.502 I/Xposed  (  959): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
10-11 09:04:52.551 I/Xposed  (  959):   Loading class com.blanke.mdwechat.WechatHook
10-11 09:04:52.554 I/Xposed  (  959): Loading modules from /data/app/cn.wq.myandroidtoolsxposed-1/base.apk
10-11 09:04:52.601 I/Xposed  (  959):   Loading class cn.wq.myandroidtoolsxposed.XposedHook
10-11 09:04:52.603 I/Xposed  (  959): Loading modules from /data/app/com.fkzhang.qqxposed-1/base.apk
10-11 09:04:53.142 I/Xposed  (  959):   Loading class com.fkzhang.qqxposed.XposedInit
10-11 09:04:53.143 I/Xposed  (  959): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.CLON-1/base.apk
10-11 09:04:53.233 I/Xposed  (  959):   Loading class com.chelpus.XSupport
10-11 09:04:53.241 I/Xposed  (  959): Loading modules from /system/priv-app/com.oasisfeng.greenify/com.oasisfeng.greenify.apk
10-11 09:04:54.553 I/Xposed  (  959):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
10-11 09:04:54.555 I/Xposed  (  959):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
10-11 09:04:54.555 I/Xposed  (  959): Loading modules from /data/app/liubaoyua.poweramppatch-1/base.apk
10-11 09:04:54.564 I/Xposed  (  959):   Loading class liubaoyua.poweramppatch.MainHook
10-11 09:04:54.564 I/Xposed  (  959): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-11 09:04:55.148 I/Xposed  (  959):   Loading class com.fkzhang.wechatxposed.XposedInit
10-11 09:04:55.149 I/Xposed  (  959): Loading modules from /data/app/com.nijigenirubasho.mobiletailchanger-1/base.apk
10-11 09:04:55.159 I/Xposed  (  959):   Loading class com.nijigenirubasho.mobiletailchanger.Xpo
10-11 09:04:55.159 I/Xposed  (  959): Loading modules from /data/app/ce.hesh.wechatUI-1/base.apk
10-11 09:04:55.205 I/Xposed  (  959):   Loading class ce.hesh.wechatUI.MainHook
10-11 09:04:55.209 I/Xposed  (  959): Loading modules from /data/app/dev.ukanth.ufirewall-1/base.apk
10-11 09:04:55.322 I/Xposed  (  959):   Loading class dev.ukanth.ufirewall.xposed.XposedInit
10-11 09:04:55.343 I/Xposed  (  959): Loading modules from /data/app/ma.wanam.smartnetwork-1/base.apk
10-11 09:04:55.375 I/Xposed  (  959):   Loading class ma.wanam.smartnetwork.Xposed
10-11 09:04:55.376 I/Xposed  (  959): Loading modules from /data/app/com.sorcerer.sorcery.iconpack-2/base.apk
10-11 09:04:57.084 I/Xposed  (  959):   Loading class com.sorcerer.sorcery.iconpack.apply.xposed.Xposed
10-11 09:04:57.085 I/Xposed  (  959): Sorcery Xposed: new sorcery started
10-11 09:04:57.095 I/Xposed  (  959): Loading modules from /data/app/com.yyxx.wechatfp-1/base.apk
10-11 09:04:57.186 I/Xposed  (  959):   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
10-11 09:04:57.191 I/Xposed  (  959): Loading modules from /data/app/com.mhook.dialog-1/base.apk
10-11 09:04:57.207 I/Xposed  (  959):   Loading class com.mhook.dialog.Module
10-11 09:04:57.736 E/Xposed  ( 5842): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.nijigenirubasho.mobiletailchanger.Xpo.handleLoadPackage(Xpo.java)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.XposedInit$4$1.beforeHookedMethod(XposedInit.java:165)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:319)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.android.server.SystemServer.run(SystemServer.java:352)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.android.server.SystemServer.main(SystemServer.java:239)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at java.lang.reflect.Method.invoke(Native Method)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-11 09:04:57.736 E/Xposed  ( 5842): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-11 09:04:57.858 I/Xposed  ( 5842): processName:android  packageName:android
10-11 09:04:57.861 I/Xposed  ( 5842): GB:Is AOSP forced: false
10-11 09:04:57.884 I/Xposed  ( 5842): GB:ModHwKeys: method is:readConfigurationDependentBehaviors
10-11 09:04:57.885 I/Xposed  ( 5842): GB:ModHwKeys: method is: handleDoubleTapOnHome
10-11 09:05:08.970 E/Xposed  ( 5842): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
10-11 09:05:08.970 E/Xposed  ( 5842): 	at com.nijigenirubasho.mobiletailchanger.Xpo.handleLoadPackage(Xpo.java)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:202)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:353)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at android.app.LoadedApk.<init>(<Xposed>)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2043)
10-11 09:05:08.970 E/Xposed  ( 5842): 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1983)

**Comment by klcb2010** [comment]
Sony xzp  Xposed 88.1

**Comment by klcb2010** [comment]
Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.198 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.206 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.209 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.213 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.219 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.225 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.229 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.234 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.237 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.243 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.246 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.273 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.284 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.322 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.372 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.408 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.468 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.647 I/Xposed  (10373): Sorcery Xposed: not active
10-11 09:13:32.734 I/Xposed  (10373): Sorcery Xposed: not active

**Comment by djfeng** [comment]
Me too

**Comment by rovo89** [comment]
Both of these are errors in modules. For example, the first error is from com.nijigenirubasho.mobiletailchanger. Please contact the module author and ask for a fix.
