### ISSUE TITLE
The problems encountered in use

### ISSUE THREAD

**Issue by xwlean** [rovo89/XposedBridge#20]
Hello, I'm in the use of XposedBridge.jar time, ran into a problem, the problem such as:
DisplayMetrics DM = new (DisplayMetrics);
GetWindowManager (.GetDefaultDisplay)) (.GetMetrics (DM);
Float width=dm.widthPixels_dm.density;
Float height=dm.heightPixels_dm.density;
I want to modify the widthPixels and heightPixels values, how to modify,

**Comment by rovo89** [comment]
That doesn't sound like a problem with Xposed, but like a support request on how to use it. Please use XDA for that: http://forum.xda-developers.com/xposed
Oh, and please include the actual code when you post there. We can guess what you mean, but it's pretty messed up (maybe by autocorrect).

**Comment by xwlean** [comment]
How to use XposedBridgeApi to modify the mobile phone resolution

**Comment by rovo89** [comment]
Like I said, this is not the place for support questions.
