### ISSUE TITLE
Xposed Framework version 88.1 is installed but not active.

### ISSUE THREAD

**Issue by Zackx23** [rovo89/XposedBridge#200]
I recently installed the official xposed for my pure nexus custom rom. Flashed the framework, but this message came and xposed wasn't active. It was active for a while in between when I installed a mod and was working fine, but after reboot same problem persisted. Plz Help.

**Comment by rovo89** [comment]
Logs, please.

**Comment by Zackx23** [comment]
2-10 16:42:38.655 I/Xposed  (  288): -----------------
02-10 16:42:38.655 I/Xposed  (  288): Starting Xposed version 88, compiled for SDK 25
02-10 16:42:38.655 I/Xposed  (  288): Device: ZUK Z1 (ZUK), Android version 7.1.2 (SDK 25)
02-10 16:42:38.655 I/Xposed  (  288): ROM: NJH47D
02-10 16:42:38.655 I/Xposed  (  288): Build fingerprint: ZUK/ham/Z1:5.1.1/LMY49J/YOG4PAS9IG:user/release-keys
02-10 16:42:38.655 I/Xposed  (  288): Platform: armeabi-v7a, 32-bit binary, system server: yes
02-10 16:42:38.655 I/Xposed  (  288): SELinux enabled: yes, enforcing: no
10-11 01:36:51.605 I/Xposed  (  288): -----------------
10-11 01:36:51.605 I/Xposed  (  288): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-11 01:36:52.109 I/Xposed  (  288): Detected ART runtime
10-11 01:36:52.112 I/Xposed  (  288): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing

**Comment by rovo89** [comment]
Looks totally fine to me. Is this the full Xposed log? And could you show a screenshot of the error please?

**Comment by Zackx23** [comment]
Those were the old logs I suppose when I managed to activate xposed for a boot. After then, I cleared the old logs. But now there's no logs at all. It says "Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log (No such file or directory)".

**Comment by Zackx23** [comment]
[
![screenshot_20171011-142249](https://user-images.githubusercontent.com/32694597/31431079-4e2577ec-ae90-11e7-9d85-bf1579c159b5.png)
![Uploading Screenshot_20171011-142258.png…]()

](url)

**Comment by Zackx23** [comment]
[
![screenshot_20171011-142258](https://user-images.githubusercontent.com/32694597/31431175-8dfeceb8-ae90-11e7-8982-421008737566.png)
](url)

**Comment by x-Pepsy** [comment]
Click in the save button, allow permission, delete the log from menu and reboot.

**Comment by Gorneman** [comment]
Disable the modules if enabled. Some are not compatible

**Comment by rovo89** [comment]
Could you please check whether `/data/user_de/0/de.robv.android.xposed.installer` exists? You might need a shell or app with root permissions to navigate to that path.

**Comment by adityasubathu** [comment]
I'm also getting the same error. Logs don't show any error. A soft reboot fixes this, but on next full reboot, this error appears again.

DU 11.7.1
ARM64
Xposed 88/88.1

**Comment by ghost** [comment]
OnePlus One
Arm
Xposed 88.1
https://www.dropbox.com/s/tveqvdtwb9ph2bv/liveboot.log?dl=0
I also get yellow notification after hard reboot that xposed is installed but not active.
After choosing soft reboot in xposed installer, xposed is active with working modules.
/data/user_de/0/de.robv.android.xposed.installer exists.

**Comment by aviraxp** [comment]
`E/Xposed  (  230): Xposed's Zygote service is not running, cannot work without it`

Seems we should ramp the timeout up.

**Comment by Jedarc** [comment]
Here it is normal.

![screenshot_20171011-101748](https://user-images.githubusercontent.com/10923617/31446757-a6c55bca-ae76-11e7-9267-d154e93d3042.png)

**Comment by f41lbl0g** [comment]
Encountering the same issue on 7.1.2 Oneplus One ARM Xposed v88.1 (also happened with v88). Seems like an issue possibly with selinux enforcing?
Here is the log.
[xposed_error_20171013_144750.log](https://github.com/rovo89/XposedBridge/files/1383691/xposed_error_20171013_144750.log)

**Comment by Borbart** [comment]
Hey guys.
I had the same problem and managed to fix it. I was using systemless xposed (unofficial) and somehow there was still an active module on magisk (the app I'm using for superSU) that enabled systemless xposed. Uninstall that module and worked fine

**Comment by HebusLagad** [comment]
I had this issue yesterday and I fixed it by changing folder permissions (allow all) for the folder /data/user_de/0/de.robv.android.xposed.installer (using root explorer).
Then reboot the phone.

**Comment by azharudh33n** [comment]
Same problem here

**Comment by EinarasGar** [comment]
Like @HebusLagad said. His method worked

**Comment by azharudh33n** [comment]
Changing folder permission solved the problem now it's working fine thanks to @HebusLagad

**Comment by f41lbl0g** [comment]
I gave all permissions, reverts back to how it was on reboot.

**Comment by HebusLagad** [comment]
FYI: if you reboot your phone again then check if xposed is still active. You might set permission on the folder again.

**Comment by rehannali** [comment]
@HebusLagad I give all permission as you said and after reboot, it reverts back to the original state.

**Comment by yappooo** [comment]
I had same issue  here the log 


10-17 23:45:16.129 I/Xposed  (25255): -----------------
10-17 23:45:16.129 I/Xposed  (25255): Starting Xposed version 88.1, compiled for SDK 25
10-17 23:45:16.129 I/Xposed  (25255): Device: A0001 (OnePlus), Android version 7.1.2 (SDK 25)
10-17 23:45:16.129 I/Xposed  (25255): ROM: bacon-userdebug 7.1.2 NZH54D eng.build.20170818.152325 release-keys
10-17 23:45:16.129 I/Xposed  (25255): Build fingerprint: oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys
10-17 23:45:16.129 I/Xposed  (25255): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-17 23:45:16.129 I/Xposed  (25255): SELinux enabled: yes, enforcing: no
10-17 23:45:18.309 I/Xposed  (25255): -----------------
10-17 23:45:18.309 I/Xposed  (25255): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-17 23:45:19.055 I/Xposed  (25255): Detected ART runtime
10-17 23:45:19.060 I/Xposed  (25255): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-17 23:45:19.295 I/Xposed  (25255): Loading modules from /data/app/com.aviraxp.adblocker.continued-1/base.apk
10-17 23:45:19.315 I/Xposed  (25255):   Loading class com.aviraxp.adblocker.continued.hook.HookLoader
10-17 23:45:19.570 I/Xposed  (25255): Loading modules from /data/app/com.ceco.sbdp-1/base.apk
10-17 23:45:19.590 I/Xposed  (25255):   Loading class com.ceco.sbdp.ModSbdp
10-17 23:45:19.603 I/Xposed  (25255): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
10-17 23:45:19.625 I/Xposed  (25255):   Loading class ma.wanam.youtubeadaway.Xposed
10-17 23:45:19.627 I/Xposed  (25255):   Loading class ma.wanam.youtubeadaway.ResXposed
10-17 23:45:21.377 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@framework@services.jar@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@framework@services.jar@classes.dex@xposed' : No such file or directory
10-17 23:45:21.380 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@framework@ethernet-service.jar@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@framework@ethernet-service.jar@classes.dex@xposed' : No such file or directory
10-17 23:45:21.383 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@framework@wifi-service.jar@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@framework@wifi-service.jar@classes.dex@xposed' : No such file or directory
10-17 23:45:36.619 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@priv-app@SettingsProvider@SettingsProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@priv-app@SettingsProvider@SettingsProvider.apk@classes.dex@xposed' : No such file or directory
10-17 23:45:48.015 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@priv-app@Telecom@Telecom.apk@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@priv-app@Telecom@Telecom.apk@classes.dex@xposed' : No such file or directory
10-17 23:45:48.775 W/Xposed  (25564): Failed to load Xposed info for /data/dalvik-cache/arm/system@priv-app@FusedLocation@FusedLocation.apk@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@priv-app@FusedLocation@FusedLocation.apk@classes.dex@xposed' : No such file or directory
10-17 23:46:28.757 I/Xposed  (28135): YouTube: com.google.android.apps.youtube.gaming 2.01.15.4 loaded!
10-17 23:46:45.683 I/Xposed  (28536): YouTube: com.google.android.youtube 12.40.59 loaded!
10-17 23:47:08.899 I/Xposed  (28536): YouTube AdAway: Successfully hooked ads DB xxm
10-17 23:47:19.648 I/Xposed  (29729): YouTube: com.google.android.youtube 12.40.59 loaded!
10-17 23:47:26.360 I/Xposed  (29729): YouTube AdAway: Successfully hooked ads DB xxm
10-17 23:47:30.565 I/Xposed  (29729): YouTube AdAway: Successfully hooked ads wrapper 
10-17 23:47:38.116 I/Xposed  (29729): YouTube AdAway: Successfully hooked ads fetchers
10-17 23:52:47.252 I/Xposed  (31962): YouTube: com.google.android.apps.youtube.gaming 2.01.15.4 loaded!
10-17 23:52:50.545 I/Xposed  (32125): YouTube: com.google.android.youtube 12.40.59 loaded!
10-17 23:52:53.740 I/Xposed  (32125): YouTube AdAway: Successfully hooked ads DB xxm
10-17 23:52:55.462 I/Xposed  (32125): YouTube AdAway: Successfully hooked ads wrapper 
10-17 23:52:57.112 I/Xposed  (31962): YouTube AdAway: Successfully hooked ads DB lzt
10-17 23:52:58.710 I/Xposed  (31962): YouTube AdAway: Successfully hooked ads wrapper 
10-17 23:53:00.988 I/Xposed  (32125): YouTube AdAway: Successfully hooked ads fetchers
10-17 23:53:01.246 I/Xposed  (31962): YouTube AdAway: Successfully hooked ads fetchers

**Comment by calculator120d** [comment]
When I tap on the save button, it says, "Cannot write on SD Card". Why?

**Comment by ghost** [comment]
i  also have the problem  after  giving permision and reboot

**Comment by sagar2208** [comment]
Yes I also had this problem, it's actually not with the framework, make sure all your apps are in the internal storage (xposed installer, installed modules). 
This has helped me resolve multiple issues generally listed or talked about regarding Xposed on nougat.

**Comment by calebtwoodland** [comment]
Hey all,

For anyone else browsing this thread receiving the following error: 
`Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log (No such file or directory).`

sagar2208 is right on the mark. Make sure your Xposed Installer app and the modules are all on your _Internal Storage_ - that is what fixed the error for me. Such a simple solution. I did not realize the Xposed app installed itself to my external SD.

**Comment by yappooo** [comment]
My phone only have internal memory

**Comment by f41lbl0g** [comment]
For us guys on oneplus one, it hasn't been fixed yet with the fixes above.  But I think i may have a solution. Try disabling sdcardfs, imma try it soon and see if it makes a difference.

**Comment by yappooo** [comment]
i also think this is sdcardfs issue . .did anyone manage find solution ?

**Comment by f41lbl0g** [comment]
@nazmirul I tried disabling sdcardfs, didn't work

**Comment by rovo89** [comment]
Please try with v88.2 and Xposed Installer 3.1.3.

**Comment by Hero355** [comment]
Tried with v88.2 on 3.1.3 and unfortunately same.
Nexus 5  Android 7.1.2 Dirty Unicorns

**Comment by rovo89** [comment]
Do you get any red error message about a known issue? If yes, which one?

**Comment by Hero355** [comment]
No any red error, same error can't right log. But take it off. I got solution. After reboot it says, "Xposed installed, but not activated. Please check log". All you need is to "Hot reboot" not a reboot. "Hot reboot" is fixing.

Thank you so much.

**Comment by f41lbl0g** [comment]
@rovo89 here are the logs using the new v88.2 and new xposed installer 3.1.3.
The logs say 88.1, even though I have 88.2 installed in the first reboot with it not working. Then I did a hot reboot, xposed works. Then I did a another full reboot, and now the logs say 88.2 although it still doesn't work.
Oneplus One, Dirty Unicorns, 7.1.2
My guess is that these are the logs from the last time it works, so they are probably not even relevant to you. I think the hard reboot and hot reboot ones are identical, meaning that it cant even access the logs. Something related to permissions on hard reboot vs soft reboot seems like the issue.
First Reboot with 88.2 installed:
[xposed_error_20171030_171519.log](https://github.com/rovo89/XposedBridge/files/1428842/xposed_error_20171030_171519.log)
Hot Reboot with 88.2:
[xposed_error_20171030_173200.log](https://github.com/rovo89/XposedBridge/files/1428886/xposed_error_20171030_173200.log)
Hard Reboot with 88.2:
[xposed_error_20171030_173431.log](https://github.com/rovo89/XposedBridge/files/1428888/xposed_error_20171030_173431.log)

Also most of the reports above (as far as I can tell) are from Dirty Unicorns. It may be an incompatibilty issue with that rom.

**Comment by adityasubathu** [comment]
I think that this error is faced only by DU users.

**Comment by f41lbl0g** [comment]
I just switched from DU to another rom and I'm not facing issues anymore.

**Comment by yappooo** [comment]
Same with just change from du to candy don't have any issue

**Comment by drandrew1983** [comment]
I'm facing same problem, check this link it may help
http://club.huawei.com/thread-14239436-1-1.html

**Comment by looneytkp** [comment]
I'm on du and i have this issue, a friend uses rr and it installed well...so it's definitely an issue with du
don't know what causes that

**Comment by ghost** [comment]
Same error here after a full reboot. And I'm on Dirty Unicorns, too. 7.1.2, ARM64.

**Comment by gianmaxfactor** [comment]
Tried with latest installer 3.1.4 and 88.2 framework , still inactive issue for xposed exist. Any definitive fix? Thanks

**Comment by ghost** [comment]
Looks like DU issues framework doesn't active

**Comment by gianmaxfactor** [comment]
Please what does DU stands for ?

EDIT: ah ok, Dirty Unicorns. No, I'am on a stock EMUI rom...

Everytime that I reboot (or shutdown) then XPosed become inactive (and so Gravity, because it does not find the framework...). I don't see any log...

**Comment by xing2387** [comment]
I had the same issue and just fixed it. Like @HebusLagad , but what work for me is changing the "/data/user_de/0/de.robv.android.xposed.installer" folder to 700 not 777.
My device is using  lineageos14.1, xposed_sdk25, install 3.1.5.

**Comment by xing2387** [comment]
Finally, i find out that what actually worked is the "soft reboot" from the menu at top right corner .
Every time i select the soft reboot option the installer will requests the root permission again and the "Privacy Guard" dialog will shows again asking me allow or deny.

I think the "installed but not active" issue relate to the root permission.

**Comment by rovo89** [comment]
No, Xposed doesn't even need root once it's installed. y the reason why you are asked again and again is that the system reboots immediately and doesn't have enough time to store/remember your choice.

If soft reboot works but hard reboot doesn't, its either some "correction" done by the system (e.g. changing some permissions) or something isn't ready yet when Xposed tries to start (like /data mounts). Unfortunately, I don't have time to investigate currently.

**Comment by xing2387** [comment]
Sorry, my mistake... You are right.
I've tried two way to soft reboot, by select the "soft reboot" option form the power menu or from Xposed Installer. Both work for me.
So the “ ’installed but not active‘ issue relate to the root permission” is WRONG.

Here is my log:
------------------------ from logcat ------------------------------
don't know why the time is incorrect...
```
01-04 13:27:08.489 326-326/? D/XposedStartupMarker: Current time: 278828, PID: 326
01-04 13:27:08.489 326-326/? I/Xposed: -----------------
01-04 13:27:08.489 326-326/? I/Xposed: Starting Xposed version 89, compiled for SDK 25
01-04 13:27:08.489 326-326/? I/Xposed: Device: XT1095 (motorola), Android version 7.1.2 (SDK 25)
01-04 13:27:08.489 326-326/? I/Xposed: ROM: lineage_victara-userdebug 7.1.2 NJH47F af7f459982 test-keys
01-04 13:27:08.489 326-326/? I/Xposed: Build fingerprint: motorola/victara_tmo/victara:5.1/LPE23.32-21.3/5:user/release-keys
01-04 13:27:08.489 326-326/? I/Xposed: Platform: armeabi-v7a, 32-bit binary, system server: yes
01-04 13:27:08.489 326-326/? I/Xposed: SELinux enabled: yes, enforcing: yes
10-17 16:47:10.001 326-326/? E/Xposed: Xposed's Zygote service is not running, cannot work without it
10-17 16:47:21.987 877-877/system_process W/PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package de.robv.android.xposed.installer because it was previously installed without
10-17 16:47:21.987 877-877/system_process W/PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package de.robv.android.xposed.installer because it was previously installed without
10-17 16:47:22.199 329-329/? W/cutils: Expected path /data/user_de/0/de.robv.android.xposed.installer with mode 700 but found 711
10-17 16:47:23.722 877-1100/system_process W/PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package de.robv.android.xposed.installer because it was previously installed without
10-17 16:47:23.722 877-1100/system_process W/PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package de.robv.android.xposed.installer because it was previously installed without
10-17 16:47:52.309 3268-3268/? D/su: 10067 /system/bin/app_process32_xposed executing 0 /system/bin/sh using binary /system/bin/sh : sh
```
---------- from /data/user_de/0/de.robv.android.xposed.installer/log/error.log file -------------
seems no error
```
02-05 16:06:46.243 I/Xposed  ( 6510): -----------------
02-05 16:06:46.243 I/Xposed  ( 6510): Starting Xposed version 89, compiled for SDK 25
02-05 16:06:46.243 I/Xposed  ( 6510): Device: XT1095 (motorola), Android version 7.1.2 (SDK 25)
02-05 16:06:46.243 I/Xposed  ( 6510): ROM: lineage_victara-userdebug 7.1.2 NJH47F af7f459982 test-keys
02-05 16:06:46.243 I/Xposed  ( 6510): Build fingerprint: motorola/victara_tmo/victara:5.1/LPE23.32-21.3/5:user/release-keys
02-05 16:06:46.243 I/Xposed  ( 6510): Platform: armeabi-v7a, 32-bit binary, system server: yes
02-05 16:06:46.243 I/Xposed  ( 6510): SELinux enabled: yes, enforcing: no
02-05 16:06:48.391 I/Xposed  ( 6510): -----------------
02-05 16:06:48.391 I/Xposed  ( 6510): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-05 16:06:49.176 I/Xposed  ( 6510): Detected ART runtime
02-05 16:06:49.184 I/Xposed  ( 6510): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
02-05 16:06:49.496 I/Xposed  ( 6510): Loading modules from /data/app/com.ceco.nougat.gravitybox-1/base.apk
02-05 16:06:49.522 I/Xposed  ( 6510):   Loading class com.ceco.nougat.gravitybox.GravityBox
02-05 16:06:49.530 I/Xposed  ( 6510): GB:Hardware: qcom
02-05 16:06:49.530 I/Xposed  ( 6510): GB:Product: lineage_victara
02-05 16:06:49.530 I/Xposed  ( 6510): GB:Device manufacturer: motorola
02-05 16:06:49.530 I/Xposed  ( 6510): GB:Device brand: motorola
02-05 16:06:49.530 I/Xposed  ( 6510): GB:Device model: XT1095
02-05 16:06:49.531 I/Xposed  ( 6510): GB:Device type: phone
02-05 16:06:49.532 I/Xposed  ( 6510): GB:Is MTK device: false
02-05 16:06:49.532 I/Xposed  ( 6510): GB:Is Xperia device: false
02-05 16:06:49.534 I/Xposed  ( 6510): GB:Is Moto XT device: true
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Is OxygenOS ROM: false
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Has Lenovo custom UI: false
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Has telephony support: true
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Has Gemini support: false
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Android SDK: 25
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Android Release: 7.1.2
02-05 16:06:49.535 I/Xposed  ( 6510): GB:ROM: lineage_victara-userdebug 7.1.2 NJH47F af7f459982 test-keys
02-05 16:06:49.535 I/Xposed  ( 6510): GB:Error logging: false
02-05 16:06:51.135 I/Xposed  ( 6896): GB:Is AOSP forced: false
```

**Comment by paulkugaev** [comment]
HTC 10, PureFusionOS, 26 api, Xposed 90.1-beta3, same here. Here are my logs:


04-15 20:12:15.582 I/Xposed  (13427): -----------------
04-15 20:12:15.582 I/Xposed  (13427): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 26
04-15 20:12:15.582 I/Xposed  (13427): Device: HTC 10 (HTC), Android version 8.0.0 (SDK 26)
04-15 20:12:15.582 I/Xposed  (13427): ROM: OPR4.170623.020
04-15 20:12:15.582 I/Xposed  (13427): Build fingerprint: htc/pmewl_00617/htc_pmewl:7.0/NRD90M/831921.8:user/release-keys
04-15 20:12:15.582 I/Xposed  (13427): Platform: arm64-v8a, 64-bit binary, system server: yes
04-15 20:12:15.582 I/Xposed  (13427): SELinux enabled: yes, enforcing: no
04-15 20:12:17.885 I/Xposed  (13427): -----------------
04-15 20:12:17.886 I/Xposed  (13427): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-15 20:12:19.127 I/Xposed  (13427): Detected ART runtime
04-15 20:12:19.129 I/Xposed  (13427): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-15 20:12:19.366 I/Xposed  (13427): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.COIN-6SB0lI-4xMdjoK5KYIokwA==/base.apk
04-15 20:12:19.395 I/Xposed  (13427):   Loading class com.chelpus.XSupport
04-15 20:12:19.418 I/Xposed  (13427): Loading modules from /data/app/com.samstenner.instantunlock-YWnFgLCcNNwwusMQiI7Bmg==/base.apk
04-15 20:12:19.443 I/Xposed  (13427):   Loading class com.samstenner.instantunlock.UnlockManager
04-15 20:12:19.458 I/Xposed  (13427): Loading modules from /data/app/com.yuanwofei.cardemulator-II8Yzgly4hQJC1IefQEM5g==/base.apk
04-15 20:12:19.492 I/Xposed  (13427):   Loading class com.yuanwofei.cardemulator.xposed.MainHook
04-15 20:12:26.352 I/Xposed  (13698): Successfully Accessed Packages
04-15 20:12:26.352 I/Xposed  (13698): Corrected for Oreo
04-15 20:12:27.117 I/Xposed  (13698): Hooked Mediator
04-15 20:12:28.564 I/Xposed  (13698): Unlockable: false
04-15 20:12:28.954 I/Xposed  (13698): Hooked Notification Stack
04-15 20:12:29.129 I/Xposed  (13698): Unlockable: false
04-15 20:12:29.135 I/Xposed  (13698): Unlockable: false
04-15 20:12:29.296 I/Xposed  (13698): Hooked Ambient State
04-15 20:12:29.361 I/Xposed  (13698): Unlockable: false
04-15 20:12:29.364 I/Xposed  (13698): Unlockable: false
04-15 20:12:29.658 I/Xposed  (13698): Unlockable: false
04-15 20:12:29.946 I/Xposed  (13698): Status Bar Hooked
04-15 20:12:30.056 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.056 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.057 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.057 I/Xposed  (13698): Hooked Keyguard Changed
04-15 20:12:30.058 I/Xposed  (13698): Retrieving Preferences
04-15 20:12:30.068 I/Xposed  (13698): Enabled: true
04-15 20:12:30.068 I/Xposed  (13698): Controlled: true
04-15 20:12:30.068 I/Xposed  (13698): Visible: false
04-15 20:12:30.068 I/Xposed  (13698): Unlocked: false
04-15 20:12:30.068 I/Xposed  (13698): Not Eligible For Unlock
04-15 20:12:30.069 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.069 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.291 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.297 I/Xposed  (13698): Unlockable: false
04-15 20:12:30.358 I/Xposed  (13698): Hooked Notification Stack
04-15 20:12:30.360 I/Xposed  (13698): Unlockable: false
04-15 20:12:31.210 I/Xposed  (13698): Unlockable: false
04-15 20:12:31.224 I/Xposed  (13698): Unlockable: false
04-15 20:12:31.224 I/Xposed  (13698): Unlockable: false
04-15 20:12:31.235 I/Xposed  (13698): Hooked Keyguard Changed
04-15 20:12:31.235 I/Xposed  (13698): Retrieving Preferences
04-15 20:12:31.238 I/Xposed  (13698): Enabled: true
04-15 20:12:31.238 I/Xposed  (13698): Controlled: true
04-15 20:12:31.238 I/Xposed  (13698): Visible: true
04-15 20:12:31.238 I/Xposed  (13698): Unlocked: false
04-15 20:12:31.238 I/Xposed  (13698): Not Eligible For Unlock
04-15 20:12:31.258 I/Xposed  (13698): Unlockable: false
04-15 20:12:31.258 I/Xposed  (13698): Unlockable: false
04-15 20:12:32.411 I/Xposed  (13698): Unlockable: false
04-15 20:12:50.774 I/Xposed  (13698): Unlockable: false
04-15 20:12:50.784 I/Xposed  (13698): Unlockable: false
04-15 20:12:50.800 I/Xposed  (13698): Unlockable: false
04-15 20:12:52.884 I/Xposed  (13698): Unlockable: false
04-15 20:12:54.894 I/Xposed  (13698): Unlockable: false
04-15 20:12:55.550 I/Xposed  (13698): Hooked Exiting Animation
04-15 20:12:55.620 I/Xposed  (13698): Hooked Keyguard Changed
04-15 20:12:55.620 I/Xposed  (13698): Retrieving Preferences
04-15 20:12:55.644 I/Xposed  (13698): Enabled: true
04-15 20:12:55.644 I/Xposed  (13698): Controlled: true
04-15 20:12:55.644 I/Xposed  (13698): Visible: false
04-15 20:12:55.644 I/Xposed  (13698): Unlocked: false
04-15 20:12:55.644 I/Xposed  (13698): Not Eligible For Unlock
04-15 20:12:56.281 I/Xposed  (13698): Unlockable: false
04-15 20:12:56.282 I/Xposed  (13698): Unlockable: false
04-15 20:12:56.318 I/Xposed  (13698): Unlockable: false
04-15 20:12:56.319 I/Xposed  (13698): Unlockable: false
04-15 20:12:56.319 I/Xposed  (13698): Hooked Keyguard Changed
04-15 20:12:56.319 I/Xposed  (13698): Retrieving Preferences
04-15 20:12:56.382 I/Xposed  (13698): Enabled: true
04-15 20:12:56.382 I/Xposed  (13698): Controlled: true
04-15 20:12:56.382 I/Xposed  (13698): Visible: false
04-15 20:12:56.382 I/Xposed  (13698): Unlocked: false
04-15 20:12:56.382 I/Xposed  (13698): Not Eligible For Unlock
04-15 20:12:56.383 I/Xposed  (13698): Unlockable: false
04-15 20:12:56.384 I/Xposed  (13698): Unlockable: false
04-15 20:12:59.734 I/Xposed  (13698): Unlockable: false
04-15 20:12:59.747 I/Xposed  (13698): Unlockable: false
04-15 20:12:59.747 I/Xposed  (13698): Hooked Keyguard Changed
04-15 20:12:59.747 I/Xposed  (13698): Retrieving Preferences
04-15 20:12:59.765 I/Xposed  (13698): Enabled: true
04-15 20:12:59.765 I/Xposed  (13698): Controlled: true
04-15 20:12:59.765 I/Xposed  (13698): Visible: false
04-15 20:12:59.765 I/Xposed  (13698): Unlocked: false
04-15 20:12:59.765 I/Xposed  (13698): Not Eligible For Unlock
04-15 20:12:59.767 I/Xposed  (13698): Unlockable: false
04-15 20:12:59.767 I/Xposed  (13698): Unlockable: false

**Comment by Kara-ism** [comment]
Problem occurred on HTC U Ultra.
OS version is 7.0 with Magisk 16.4 ,and with systemless Xposed version 89.3(SDK24)

**Comment by Ellita** [comment]
@adityasubathu big thanks you for sharing your solution. "Soft reboot" in Xposed app helped to make it active.

**Comment by javierpr0** [comment]
**Message:** Version 89 of the Xposed Framework is installed, but it is not active. Please check the records for more details.
But, i check the records and nothing exist.

**Solution:**
1. Disable Xposed in Xposed Status
2. Reboot the device (After restarting, the folder and the file already exist in registers)
3. Activate Xposed in Xposed Status
4. Reboot the device (It should be up and running by now)
5. Ready

**Comment by ghost** [comment]
thanks  for your  warmhearted

2018年8月30日星期四，Eduardo Acevedo <notifications@github.com> 写道：

**Comment by ghost** [comment]
> I had this issue yesterday and I fixed it by changing folder permissions (allow all) for the folder /data/user_de/0/de.robv.android.xposed.installer (using root explorer).
> Then reboot the phone.

This did the trick for me. Thank you so much for the tip!

**Comment by ghost** [comment]
thank you for your reply

在 2018年12月4日星期二，Aaron <notifications@github.com> 写道：

**Comment by sujalshrestha-bit** [comment]
> 
![Screenshot_20200928-182712](https://user-images.githubusercontent.com/70069015/94433669-654baa80-01b8-11eb-9f1f-f241ea105fda.jpg)

**Comment by sujalshrestha-bit** [comment]
How to fix this?

**Comment by Phenom23** [comment]
I have android 8.1 and i face the same problem, any fixes?
