### ISSUE TITLE
Xposed Framework version 88.1 is installed but not active

### ISSUE THREAD

**Issue by henryconstante** [rovo89/XposedBridge#202]
10-11 08:14:26.330 E/Xposed  (15388): java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.MiuiTypedArray to class android.content.res.XResources$XTypedArray
10-11 08:14:26.330 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:473)
10-11 08:14:26.330 E/Xposed  (15388): 	at de.robv.android.xposed.XposedInit$11.afterHookedMethod(XposedInit.java:340)
10-11 08:14:26.330 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:353)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.TypedArray.<init>(<Xposed>)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.MiuiTypedArray.<init>(MiuiTypedArray.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.TypedArray.obtain(TypedArray.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.Resources.obtainAttributes(Resources.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.obtainAttributes(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.inflate(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.DrawableWrapper.inflate(DrawableWrapper.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.InsetDrawable.inflate(InsetDrawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.view.View.<init>(View.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.widget.ImageView.<init>(ImageView.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarLayout.createCloseButton(InfoBarLayout.java:217)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarCompactLayout.<init>(InfoBarCompactLayout.java:13)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBar.createView(InfoBar.java:19)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarContainer.addInfoBar(InfoBarContainer.java:56)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-11 08:14:26.330 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.os.Handler.dispatchMessage(Handler.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.os.Looper.loop(Looper.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at android.app.ActivityThread.main(ActivityThread.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at java.lang.reflect.Method.invoke(Native Method)
10-11 08:14:26.330 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
10-11 08:14:26.330 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-11 08:14:38.119 E/Xposed  (15388): java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.MiuiTypedArray to class android.content.res.XResources$XTypedArray
10-11 08:14:38.119 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:473)
10-11 08:14:38.119 E/Xposed  (15388): 	at de.robv.android.xposed.XposedInit$11.afterHookedMethod(XposedInit.java:340)
10-11 08:14:38.119 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:353)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.TypedArray.<init>(<Xposed>)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.MiuiTypedArray.<init>(MiuiTypedArray.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.TypedArray.obtain(TypedArray.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.Resources.obtainAttributes(Resources.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.obtainAttributes(Drawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.InsetDrawable.inflate(InsetDrawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.view.View.<init>(View.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.widget.ImageView.<init>(ImageView.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarLayout.createCloseButton(InfoBarLayout.java:217)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarCompactLayout.<init>(InfoBarCompactLayout.java:13)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBar.createView(InfoBar.java:19)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarContainer.addInfoBar(InfoBarContainer.java:56)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-11 08:14:38.119 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.os.Handler.dispatchMessage(Handler.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.os.Looper.loop(Looper.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at android.app.ActivityThread.main(ActivityThread.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at java.lang.reflect.Method.invoke(Native Method)
10-11 08:14:38.119 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
10-11 08:14:38.119 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-11 08:14:38.120 E/Xposed  (15388): java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.MiuiTypedArray to class android.content.res.XResources$XTypedArray
10-11 08:14:38.120 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:473)
10-11 08:14:38.120 E/Xposed  (15388): 	at de.robv.android.xposed.XposedInit$11.afterHookedMethod(XposedInit.java:340)
10-11 08:14:38.120 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:353)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.TypedArray.<init>(<Xposed>)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.MiuiTypedArray.<init>(MiuiTypedArray.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.TypedArray.obtain(TypedArray.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.Resources.obtainAttributes(Resources.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.obtainAttributes(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.inflate(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.DrawableWrapper.inflate(DrawableWrapper.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.InsetDrawable.inflate(InsetDrawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.Resources.loadDrawable(Resources.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.content.res.TypedArray.getDrawable(TypedArray.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.view.View.<init>(View.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.widget.ImageView.<init>(ImageView.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.widget.ImageButton.<init>(ImageButton.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarLayout.createCloseButton(InfoBarLayout.java:217)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarCompactLayout.<init>(InfoBarCompactLayout.java:13)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBar.createView(InfoBar.java:19)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.chrome.browser.infobar.InfoBarContainer.addInfoBar(InfoBarContainer.java:56)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-11 08:14:38.120 E/Xposed  (15388): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.os.Handler.dispatchMessage(Handler.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.os.Looper.loop(Looper.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at android.app.ActivityThread.main(ActivityThread.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at java.lang.reflect.Method.invoke(Native Method)
10-11 08:14:38.120 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
10-11 08:14:38.120 E/Xposed  (15388): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by rovo89** [comment]
https://github.com/rovo89/XposedBridge/issues/198
