### ISSUE TITLE
Random reboot leading to bootloop (SDK25)

### ISSUE THREAD

**Issue by PedroC1999** [rovo89/XposedBridge#204]
Running a Galaxy S8+ on the Renovate N950 Port. Everything was stable until Xposed was installed. I get random reboots at any time, which may or may not lead to a bootloop (Most of the time it does)

Below is a link to a log that I fetched while the phone was booting, it did eventually boot but the log is very large and cannot be posted there.

https://pastebin.com/raw/JRddaDAM

Do let me know if you need more info

**Comment by rovo89** [comment]
java.lang.RuntimeException: Unknown command line argument: --zygote-aslr-agent
Same as https://github.com/rovo89/XposedBridge/issues/205
