### ISSUE TITLE
samsung note8 7.1.1  msm8998 can not boot

### ISSUE THREAD

**Issue by ucxl** [rovo89/XposedBridge#208]
samsung note8 7.1.1  msm8998 can not boot  Thank God for the restoration 

samsung note8 7.1.1 universal8895 update 88.1 Unsmooth

**Comment by rovo89** [comment]
Logs please: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by ucxl** [comment]
[logcat.txt](https://github.com/rovo89/XposedBridge/files/1418157/logcat.txt)

**Comment by rovo89** [comment]
Duplicate of https://github.com/rovo89/Xposed/issues/273
