### ISSUE TITLE
MIUI9 andriod6.0 sdk23 xposed

### ISSUE THREAD

**Issue by LI-XIAOYAO** [rovo89/XposedBridge#212]
Why only 7.0 7.1 no 6.0 MIUI9?

**Comment by rovo89** [comment]
Be patient.

**Comment by LXIAOYO** [comment]
Thank you answer, hope MIUI9 Android6.0 can be used as soon as possible.

**Comment by LI-XIAOYAO** [comment]
@rovo89 Thank you answer, hope MIUI9 Android6.0 can be used as soon as possible.
