### ISSUE TITLE
v88.2 make system launcher keep stopping MIUI 9 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [rovo89/XposedBridge#214]
Here for logcat https://sendit.cloud/yzvqg59ly4m5
Android SDK24 . I already disabled resource hooks

**Comment by twu2** [comment]
Do you use adblock reborn module? 
I got this issue after enable this module. Disable it will solve this issue.

**Comment by What-Zit-Tooya** [comment]
@twu2 yes i installed it. 
How about minminguard?

**Comment by twu2** [comment]
minminguard work fine.

**Comment by What-Zit-Tooya** [comment]
Ok, thank , so its module related
