### ISSUE TITLE
wiki: Development tutorial updates

### ISSUE THREAD

**Issue by cernekee** [rovo89/XposedBridge#22]
I would like to suggest two changes to the development tutorial page:
- Modify this text:

```
You can download XposedBridgeApi-<version>.jar from the first post of [this XDA thread](http://forum.xda-developers.com/xposed/xposed-api-changelog-t2714067). 
```

This renders as "XposedBridgeApi-.jar".  HTML entities &amp;lt; and &amp;gt; should be used instead of the raw &lt; and &gt; symbols.
- Clarify the proper use of `xposedminversion`.  Tracing through the code, it looks like XposedInstaller opens up /data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar and reads the assets/VERSION file to figure out installedXposedVersion.  Then module.minVersion, extracted from the meta-data entry, is compared (as a truncated integer) against this number.  So, the meaningful values for this field seem to be: "2" (covering all XposedBridge versions between 2.0, Dec 2012, and 2.1.4, May 2013) and 30-54 (covering XposedBridge version 30 from Sept 2013 through the untagged XposedBridge releases 31..54).

Thanks.

**Comment by rovo89** [comment]
Thanks for the hints! I have adjusted the wiki page: https://github.com/rovo89/XposedBridge/wiki/Development-tutorial/_compare/90dd23837ac6434fe3d9dbdd10eece4c8e816ef0...a7ae61e32b4c71719da23527e3d4be12af12f120

The version history would be something for a trivia page if it existed, but in reality, it doesn't matter which old values used to exist. It's highly recommended to use the latest one available for new modules, everything else is deprecated and not supported by me.
