### ISSUE TITLE
Can't hook into Keyguard dismiss on Oreo

### ISSUE THREAD

**Issue by SamStenner** [rovo89/XposedBridge#229]
On previous versions of Android I could easily call the 'dismiss' method of the KeyguardViewMediator class. Now, it requires an argument to be passed to it:

```java
public void dismiss(IKeyguardDismissCallback callback) {
    mHandler.obtainMessage(DISMISS, callback).sendToTarget();
}
```

Elsewhere in the class, dismiss is called like this:

```java
@Override
        public void onUserSwitchComplete(int userId) {
            if (userId != UserHandle.USER_SYSTEM) {
                UserInfo info = UserManager.get(mContext).getUserInfo(userId);
                if (info != null && (info.isGuest() || info.isDemo())) {
                    // If we just switched to a guest, try to dismiss keyguard.
                    dismiss(null /* callback */);
                }
            }
        }
```

So dismiss can clearly be called with just 'null' as it's 'callback'. I'm still not sure what a callback is.
In fact, the dismissal method eventually gets around to calling this:

```java
private void handleDismiss(IKeyguardDismissCallback callback) {
        if (mShowing) {
            if (callback != null) {
                mDismissCallbackRegistry.addCallback(callback);
            }
            mStatusBarKeyguardViewManager.dismissAndCollapse();
        } else if (callback != null) {
            new DismissCallbackWrapper(callback).notifyDismissError();
        }
    }
```

Which looks like a null callback will perform 'dimissAndCollapse()', which is probably what I want.

So I call it like this:

```java
XposedHelpers.callMethod(controller, "dismiss", null);
```

However, when I do this, this error always happens:

> --------- beginning of crash
01-19 08:21:33.990 E/AndroidRuntime( 2451): FATAL EXCEPTION: main
01-19 08:21:33.990 E/AndroidRuntime( 2451): Process: com.android.systemui, PID: 2451
01-19 08:21:33.990 E/AndroidRuntime( 2451): java.lang.NullPointerException: Attempt to get length of null array
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at de.robv.android.xposed.XposedHelpers.getParameterTypes(XposedHelpers.java:482)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:456)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at com.samstenner.instantunlock.UnlockManager$4.run(UnlockManager.java:143)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at android.os.Handler.handleCallback(Handler.java:790)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at android.os.Looper.loop(Looper.java:164)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at java.lang.reflect.Method.invoke(Native Method)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-19 08:21:33.990 E/AndroidRuntime( 2451): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)<

I've been stuck on this for a while, would appreciate a hand. Thanks.

**Comment by rovo89** [comment]
Try this please: https://stackoverflow.com/questions/10087989/how-do-i-reflectively-invoke-a-method-with-null-as-argument

**Comment by SamStenner** [comment]
Thanks, should probably have seen that myself. I'll try it out.

**Comment by C3C0** [comment]
`XposedHelpers.callMethod(controller, "dismiss", (Object)null);`
should do the trick

**Comment by SamStenner** [comment]
@rovo89 I tried it and it didn't work. Using a new approach but now I'm getting this error:

> --------- beginning of crash
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): FATAL EXCEPTION: main
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): Process: com.android.systemui, PID: 2318
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.StatusBar#executeRunnableDismissingKeyguard(java.lang.Boolean,java.lang.Boolean,java.lang.Boolean)#bestmatch
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:443)
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:456)
> 01-20 12:34:14.247 E/AndroidRuntime( 2318): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)

Why isn't it finding executeRunnableDismissingKeyguard in the com.android.systemui.statusbar.phone.StatusBar class? It should be finding it.

**Comment by C3C0** [comment]
Try using primitive boolean.class instead of Boolean.class. Those are 2 different classes.

**Comment by SamStenner** [comment]
@C3C0 Thanks, your previous solution worked after all. :)
