### ISSUE TITLE
Add Replace Raw resources to guide

### ISSUE THREAD

**Issue by yoavst** [rovo89/XposedBridge#23]
In the guide [Replacting resources](https://github.com/rovo89/XposedBridge/wiki/Replacing-resources) you didn't mentioned how to replace raw resources. 

Edit: it is the same as replacing Complex resources, but you still need to tell that.

**Comment by rovo89** [comment]
It's not possible at this time to replace raw resources. PNG files (which you mentioned first) are usually not raw resources though, they are typically stored as drawables.

**Comment by yoavst** [comment]
@rovo89 Well, it works me in my code - https://github.com/yoavst/rolexquickcircle/

**Comment by rovo89** [comment]
The only explanation I have why this might work is that the app accesses these resources via getDrawable() or something like that. The correct way would be using openRawResource() though, which isn't handled in XResources: https://github.com/rovo89/XposedBridge/blob/master/src/android/content/res/XResources.java

**Comment by yoavst** [comment]
Well, LG put images on raw and use them as drawable...
