### ISSUE TITLE
Problems on Huawei P8 Lite (ALE-L21)

### ISSUE THREAD

**Issue by ThexXTURBOXx** [rovo89/XposedBridge#231]
Everytime, I start it up (tried with SuperSU and Magisk), I get this error:
https://hastebin.com/ajehubevoz.vbs
and it ends in a Bootloop
(Forgot to mention, that at first, I got the message "File not found"... then I created the file manually, now I get this error)

**Comment by rovo89** [comment]
That doesn't seem to be related to Xposed. If you get a bootloop, it must be some other error. Could you please post the full log?

**Comment by ThexXTURBOXx** [comment]
https://hastebin.com/tivococoxo.vbs
This is the full log

**Comment by ThexXTURBOXx** [comment]
Hmm.... Now it worked, but I don't know why. I did exactly the same thing for 20 times or so. But this is solved then...
![lol](http://i.bittwiddlers.org/Lu6.gif)

**Comment by rovo89** [comment]
The log showed that it was still compiling, dex2oat is mentioned in the last line. So maybe you just didn't wait long enough, the log you posted spanned just 2 minutes and the first boot might take longer than that.

**Comment by ThexXTURBOXx** [comment]
The log was from an example startup, which I did after crashing the phone. I waited about an hour at the first boot
