### ISSUE TITLE
Xsharedpreference Failing to read prefs file on Android MM and above

### ISSUE THREAD

**Issue by youngcet** [rovo89/XposedBridge#233]
I have tried almost all the options I could find on the net, but no luck. I am trying to read a prefs file from Xsharedpreferences but failing to read the values. Since the deprecation of MODE_WORLD_READABLE I store the preferences in MODE_PRIVATE in my activity as it couldn't even compile with MODE_WORLD_READABLE. How do I make this file readable publicly? Any workaround on this?

**Comment by rovo89** [comment]
I haven't tried to make files world-readable in a while, so I can't really help you with that. I can just repeat that this is definitely necessary for the current implementation.

**Comment by youngcet** [comment]
So there is no way to read a prefs file in Xsharepreferences?

**Comment by rovo89** [comment]
Please read my answer! It needs to be world-readable, then it should work. Also, the base directory of your application (`/data/data/<package>`) must be readable.

**Comment by youngcet** [comment]
The problem with that is I can't save the file as world-readable. It fails to compile the .apk complaining about 'world-readable' for Android API 24. But, anyways thanks for your time. I might be stretching a bit here, when will you implement this world-readable in the framework?

**Comment by C3C0** [comment]
You'll have to take care of the permissions on the preference files and respective folders explicitly using File operations.
https://developer.android.com/reference/java/io/File.html#setReadable(boolean, boolean)
https://developer.android.com/reference/java/io/File.html#setExecutable(boolean, boolean)
Apart from making preference xmls readable, you have to make sure app data folder as well as shared_prefs subfolder have execute flag for all for Xposed Framework to be able to descend and access preference xmls

Also, it is recommended to switch to using device protected storage so your module is compatible with devices having file-based encryption as on such devices, standard /data/data is not accessible until user is authenticated. Which means you won't be able to get prefs during boot if you need them.
https://developer.android.com/reference/android/content/Context.html#createDeviceProtectedStorageContext()
https://developer.android.com/reference/android/preference/PreferenceManager.html#setStorageDeviceProtected()

**Comment by Android1500** [comment]
i am facing same issue now got 

> You'll have to take care of the permissions on the preference files and respective folders explicitly using File operations.
> https://developer.android.com/reference/java/io/File.html#setReadable(boolean, boolean)
> https://developer.android.com/reference/java/io/File.html#setExecutable(boolean, boolean)
> Apart from making preference xmls readable, you have to make sure app data folder as well as shared_prefs subfolder have execute flag for all for Xposed Framework to be able to descend and access preference xmls
> 
> Also, it is recommended to switch to using device protected storage so your module is compatible with devices having file-based encryption as on such devices, standard /data/data is not accessible until user is authenticated. Which means you won't be able to get prefs during boot if you need them.
> https://developer.android.com/reference/android/content/Context.html#createDeviceProtectedStorageContext()
> https://developer.android.com/reference/android/preference/PreferenceManager.html#setStorageDeviceProtected()

I m facing ame issue Sir and i see your explation so please check is it good to go with File operation

`   public class Helper {



       public static void worldReadable(Context context) {
        File file = new File(context.getApplicationInfo().dataDir);
        File file2 = new File(context.getApplicationInfo().dataDir, "shared_prefs");
        if (file.exists()) {
            file.setExecutable(true, false);
            file.setReadable(true, false);
            if (file2.exists()) {
                file2.setExecutable(true, false);
                file2.setReadable(true, false);
                File file3 = new File(file2, "user_prefs.xml");
                if (file3.exists()) {
                    file3.setReadable(true, false);
                }
            }
        }
    }
}`
