### ISSUE TITLE
How to force loading of modules with this error?

### ISSUE THREAD

**Issue by beppe9000** [rovo89/XposedBridge#256]
01-18 13:58:18.377 I/Xposed  (  521): -----------------
01-18 13:58:18.377 I/Xposed  (  521): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-01 17:59:42.412 E/Xposed  (  521):   Cannot load module:
07-01 17:59:42.412 E/Xposed  (  521):   The Xposed API classes are compiled into the module's APK.
07-01 17:59:42.412 E/Xposed  (  521):   This may cause strange issues and must be fixed by the module developer.
07-01 17:59:42.412 E/Xposed  (  521):   For details, see: http://api.xposed.info/using.html
07-01 17:59:48.827 I/Xposed  (  522): -----------------

**Comment by joserebelo** [comment]
My guess is you just need to revert cbd033e7918a8f887b4e639ae5b0e6c479451914 and compile XposedBridge.

**Comment by beppe9000** [comment]
indeed i hoped for a toggle in the settings. Since i do not want to build xposed from scratch i will be modifying the module. What do I need to do?

**Comment by beppe9000** [comment]
Alright I resolved by editing the build.gradle file of the project and then recompiling. It accepted the new Xposed version too.

`dependencies {
    provided 'de.robv.android.xposed:api:82'
}`
