### ISSUE TITLE
Changing SELinux to Enforcing after modules are loaded causes XSharedPreferences failures

### ISSUE THREAD

**Issue by rsteckler** [rovo89/XposedBridge#33]
The root of the problem is that initForProcess is called once for each process when the process is loaded.  It's at this point that the XSharedPreferences strategy is chosen.  If the system boots in Permissive mode, the chosen strategy is DirectAccess (which makes perfect sense). Now, if the user changes the SELinux mode to Enforcing, the calls to XSharedPreferences will start to fail.  
Ideally, there would be a detection of the mode change, but I'm not sure if that's feasible.  At the least, I would recommend that a prefs.reload() should re-check if the process needs to change the access strategy.

**Comment by rovo89** [comment]
Wouldn't it make sense for the user to reboot after changing the SELinux mode? It sounds like something you would do just once after installing a new ROM or so, and by rebooting, the users would be sure that all the changes have been applied.

**Comment by rovo89** [comment]
Anyway, just to confirm: Yes, that's how it's currently working. There are other parts of the framework (e.g. the code to start the native services) which don't care whether SELinux is enforced or permissive. The idea is that even permissive mode will trigger warnings in the audit log, which should also be prevented (especially when seeing permissive mode as a preparation for enabling enforcing mode).

**Comment by rsteckler** [comment]
The issue I'm seeing on my HTC M8 is that I can set Enforcing using SELinuxModeChanger.  When I soft-reboot, the mode is reset to Permissive.  This means that I can never boot with Enforcing mode enabled to trigger XSharedPreferences to choose an IPC method other than direct.

The use case may be contrived.  I don't think most users that have a device/rom set to Permissive will ever want to change that to Enforcing at runtime.  I ran into it because I was debugging problems that only Enforcing mode users had, and I was on a device that only boots in Permissive mode.

Another symptom (may be a different issue) is that when I put the device in Enforcing mode, then Xposed Installer->Framework->Soft Reboot, Xposed is not loaded on that next boot.  I _must_ be in permissive mode for the soft reboot to result in Xposed being loaded.  I'm guessing this is for a similar reason:  the device was booted in permissive mode, then I changed it.

Thanks,
Ryan

**Comment by rovo89** [comment]
About the last thing you describe: A soft reboot should completely restart all processes that Xposed is involved in. So it shouldn't remember whether it was enforcing or not. Anyway, who knows what goes on in the background. Maybe it's actually switching the state back and forth.

I'll think about always using the native services if SELinux is enabled, no matter if it's enforcing or permissive. Several places need to be checked for this though, and I currently have other things on my list...

**Comment by pylerSM** [comment]
Not sure, but is this related to this issue?
http://forum.xda-developers.com/xposed/xsharedpreferences-lollipop-t3030834

**Comment by rovo89** [comment]
Are you also changing the SELinux mode to enforcing at runtime? If not, it's unrelated to this issue.

**Comment by pylerSM** [comment]
No, device boots with selinux enforced.

**Comment by rovo89** [comment]
Then it's not related to this issue. But I'll answer in the thread about the issues you might be having.

**Comment by rovo89** [comment]
@rsteckler Please test again with the next alpha version. Maybe this fixes your issue. If not, it would be great if you could give me a minimal test case to reproduce this. I'm on CM12, so I can call `setenforce` at will.

**Comment by rovo89** [comment]
No response, so I assume this is fixed with the commit mentioned referenced above.
