### ISSUE TITLE
Will my app work in KitKat if I reference the Lollipop version of XposedBridge.jar during development, or do I need to make two different apps?

### ISSUE THREAD

**Issue by waylaidwanderer** [rovo89/XposedBridge#37]
Two different apps, one referencing the non-Lollipop XposedBridge.jar, and one referencing the Lollipop XposedBridge.jar, that is.

Basically what the title says. I've been searching and I can't find a relevant answer. Thanks!

**Comment by manvir-singh** [comment]
Yes, your app will work on KitKat and lollipop if you reference the lollipop api jar.

**Comment by waylaidwanderer** [comment]
Thanks! I thought that was the case, but I just wanted to make sure so that I could rule out this being a source of any problems.

**Comment by manvir-singh** [comment]
Yup I've been using the 5.1 api on 5.0 and everything seems to be working still.

**Comment by rovo89** [comment]
Yes, generally it will work fine. However, I suggest that you use the API for Kitkat to avoid any usage of new functions (e.g. SELinux related stuff). And you can keep the best practice to set the minimum required Xposed version to the version of the API (58 or something). If you set it to 60, the module will be rejected by older Xposed versions.

Obviously, all of this requires that the hooked methods in Kitkat and Lollipop are the same, or that you use conditional statements to place the correct hooks.
