### ISSUE TITLE
Xposed Installer cannot find XposedBridge Classes in an App 

### ISSUE THREAD

**Issue by StevenStanleyBayes** [rovo89/XposedBridge#51]
I have tried almost everything such as to make modules from the classes, to make dependencies ensure the XposedBridge jar would not compile but just be referenced such as : 

dependencies {
    provided fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
} 

To change names of the custom class with lower case only, to uninstall and then re run again and many others I may not remember as I have had these problems for nearly a week and everything is the same regardless of what I try. 

I use Android Studio 1.2, Motorola MotoE XT1023, with Android KitKat 4.4.4, API 19, SDK 19, Rooted, Xposed Installer installed and works with other modules. 

Here is what happens: 

Loading Xposed v54 (for Zygote)...
Running ROM 'KXC21.5-40' with fingerprint 'motorola/condor_retca/condor_umts:4.4
.4/KXC21.5-40/48:user/release-keys'
Loading modules from /data/app/stevenstanleybayes.proximitysensor-2.apk
  Loading class package stevenstanleybayes.proximitysensor.ProximitySensorXposed

java.lang.ClassNotFoundException: Didn't find class "package stevenstanleybayes.
proximitysensor.psxhr" on path: DexPathList[[zip file "/data/app
/stevenstanleybayes.proximitysensor-2.apk"],nativeLibraryDirectories=[/vendor/li
b, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56
)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)

```
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386
```

)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
        at dalvik.system.NativeStart.main(Native Method) 

CAN I HAVE SOME HELP, PLEASE?

**Comment by manvir-singh** [comment]
Need the source code to help. Also add me on skype if you'd like help. Skype: progarmming4ife (no l in life)

**Comment by rovo89** [comment]
Seems that you have a wrong entry in your xposed_init file, the "package"  string doesn't belong there.

**Comment by StevenStanleyBayes** [comment]
THANKS A LOT, ROVO89! THIS SOLVED THE PROBLEM! 

I have removed the string " package " from the xposed_init and this solved the problem. Thus, instead of : 

package TheNameOfThePackage.TheNameOfTheClass 

xposed_init contains : 

TheNameOfThePackage.TheNameOfTheClass 

without the word " package " in front of the names as Android Studio usually puts and requires. 

Now, the custom class seems to load OK and XMain where zygote is init generates a novel. 

Regardless, the custom class with the test code works OK. The debug.log file is generated. However, the application does not seem to write in the file and the debug.log only says :  

d.xposed.installer/log/debug.log 

inside.

**Comment by rovo89** [comment]
Closing this issue as there doesn't seem to be a bug in XposedBridge. If you need help with developing your first module, XDA is the better place for that. However, as already mentioned by @Programming4life, nobody can really help if you don't provide the relevant extracts of your source code.

**Comment by StevenStanleyBayes** [comment]
OK. You are right. The most important issue has been solved. Again, the module works. I will look into the code and put some more XposedBridge.log(); Thank you for your help and advise. 

You have clearly outlined in your manual only the names have to be put and not the word " package " but the mainstream Android Studio notation seems to be make the inertia towards using the standard notations. 

Please, note, for your own information which you may wish to use accordingly, I have found XDA Forum not to be extremely helpful and responsive.

**Comment by manvir-singh** [comment]
@StevenStanleyBayes that's why I give you my Skype username I'll help you out with any questions you've got.

**Comment by StevenStanleyBayes** [comment]
Thanks. I will see what I can do to join you on Skype. Please, note, now is 3:41AM here. Thank you for your response, though. Again, I want to put some more  XposedBridge.log(); and see what happens, although, I do not think the problem is with the code. But the most important is the main problem has been solved and the Xposed classes and methods work. The rest : in a while. 

MANY THANKS!
