### ISSUE TITLE
Shared Preferences with XposedBridge Always Gives Defaults

### ISSUE THREAD

**Issue by StevenStanleyBayes** [rovo89/XposedBridge#56]
I have tried many different variation and XposedBridge methods for 4 hours. I have also tried many name variations with and without .xml. 

In the standard Java for Android, there is just one get method to read a shared preferences file. This does not seem to be the case with exposed. 

I do have : 

@Override
    public void initZygote(StartupParam startupParam) throws Throwable {
                MODULE_PATH = startupParam.modulePath;
                prefs = new XSharedPreferences("PackageName", "SharedPreferenceFileNameWithotDotXml");
             }

MODULE_PATH is not used, although I have tried many other methods where was. 

Because the file changes on the fly, I called : 

prefs.reload(); 

before I read the data. I tried without this call too. I also tried to get another prefs before the reload : 

prefs = new XSharedPreferences("PackageName", "SharedPreferenceFileNameWithotDotXml");
prefs.reload(); 

Then I try to read the data from the file : 

theStart=prefs.getInt("Start", 2);
theValue=prefs.getFloat("Value", 102.0f);

I always get the defaults 2 and 102.0 although the file is there and the values of the file are different. I have read the file. 

In standard java for android philosophy, just the initialisation in init zygote and prefs.reload() are sufficient to load the changing values of the shared preferences file into prefs and then into the variables. 

Xposed seems to be different. 

I have been told there is a way to read the data from the file. I have tried most anything and cannot. What is the way to do so. Must be simple and straight as in the standard java for android. I must not do everything necessary. 

Please, inform.

**Comment by StevenStanleyBayes** [comment]
I have also tried to read the file manually from the Xposed class. Access denied. Tried <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /> just in cases. Access denied, again. 

Tried to make the shared preferences file with Activity.MODE_WORLD_READABLE. Still access denied to be read manually. 

Even with Activity.MODE_WORLD_READABLE, Xposed cannot read the file as previously explained.

**Comment by StevenStanleyBayes** [comment]
Tried : 

@Override
    public void initZygote(StartupParam startupParam) throws Throwable {

```
    prefs = new XSharedPreferences(TheNameOfTheXposedClass.class.getPackage().getName());
            prefs.makeWorldReadable();

}
```

Then, in the hooked method : 

```
                prefs.reload();
                theStart = prefs.getInt("Start", 2);
                theValue = prefs.getFloat("Value", 102.0f);
```

Still returns only the default, although the file is there. I think, in all attempts, XSharedPreferences() cannot get the name of the package and or or the name of the file. 

The file is in /data/data/NameOfPackage/shared_prefs/NameOfFile.xml

**Comment by StevenStanleyBayes** [comment]
Tried : 

@Override
 public void initZygote(StartupParam startupParam) throws Throwable {
    prefs = new XSharedPreferences("/data/data/NameOfPackage/shared_prefs/NameOfFile.xml");
            prefs.makeWorldReadable();
}

with and without .xml 

Still nothing.

**Comment by StevenStanleyBayes** [comment]
Checked for a prefs == null. prefs is never null. Still cannot read the values of the keys.

**Comment by rovo89** [comment]
Can you check if `prefs.getFile().getAbsolutePath()` points to the correct file? And if yes, what are the permissions of that file? It has to be world readable, and of course it must contain the values you are looking for.

**Comment by StevenStanleyBayes** [comment]
PROBLEM SOLVED. 

Thank you for your reply. Everything was WORLD READABLE : in the non Xposed class and in the Xposed class on a number of occasions. 

Also, I have used the hard values for the package and path. 

The problem was not related to Java and Android but to Android arrangements and how much Xposed can cope with. The Android permissions for to access the file from the Xposed class had to be elevated which is unusual but this is what solved the problem, I think. Someone also reported the same problem and the same solution : http://forum.xda-developers.com/xposed/development-xsharedpreferences-issue-t2931396 

In the non Xposed class, I have used the same solution just with a hard coded path and file. After I make the shared preferences file in the non Xposed class, I gave more permissions by : 

File theSharedPrefsFile;
theSharedPrefsFile = new File("/data/data/PackageName/shared_prefs/FileName.xml");
theSharedPrefsFile.setReadable(true, false); 

This seems to have solved the problem. 

I am not sure of how reliable the solution is, though. I still check in the Xposed class whethere there is such a file or not. I have not tested what happens when the file is not there initially. Must do. 

theXposedCommunicationPreferenceFile = new File("/data/data/PackageName/shared_prefs/FileName.xml");
                    if (theXposedCommunicationPreferenceFile.exists() == false) XposedBridge.log("Check in hooked method cannot find the file");

Hope everything would be OK. 

Even though everything should be OK, I am not sure how reliable the dependence of permissions is. 

I have also tried the secure reload : 

StrictMode.ThreadPolicy oldPolicy;
oldPolicy = StrictMode.allowThreadDiskReads();
                    try {
                        prefs.reload();
                    } finally {
                        StrictMode.setThreadPolicy(oldPolicy);
                    } 

I am not sure how reliable this is either so I put another simple reload on top : 

prefs.reload();
StrictMode.ThreadPolicy oldPolicy;
oldPolicy = StrictMode.allowThreadDiskReads();
                    try {
                        prefs.reload();
                    } finally {
                        StrictMode.setThreadPolicy(oldPolicy);
                    } 

I think, neither of these has made any difference and the real solution was the higher permissions to access the shared preference file given in the non Xposed class, again : 

File theSharedPrefsFile;
theSharedPrefsFile = new File("/data/data/PackageName/shared_prefs/FileName.xml");
theSharedPrefsFile.setReadable(true, false); 

Pretty nasty problem and difficult to find solution although published in the XDA Forum the searchability of post in the said forum is not very good. 

Yet another sleepless night.

**Comment by rovo89** [comment]
Hm, I think using MODE_WORLD_READABLE in the place where the settings are written (i.e. in your Activity/Fragment) should be enough. Have you done it like this? https://github.com/rovo89/PlayStoreFixes/blob/master/src/de/robv/android/xposed/mods/playstorefix/SettingsActivity.java#L29
Is your module open-source?

**Comment by StevenStanleyBayes** [comment]
Most likely the way you suggest has also high access score. You can check the number and compare to the rest. 

However, neither this methods nor preferences.makeWorldReadable() work in a service. Not easily. Thus, I have had to use the Android Java standard preferences = getSharedPreferences("NameOfFile", Activity.MODE_WORLD_READABLE); Then, after writes and commits with the editor, I have done : 

thePrefsFile = new FileFullNameWithPathOfThePreferencesFile");
        if(thePrefsFile.setReadable(true, false)==false) Toast.makeText(getApplicationContext(), "Cannot make the shared preferences file readable.", Toast.LENGTH_SHORT).show();

**Comment by StevenStanleyBayes** [comment]
Here is some more info : 

http://stackoverflow.com/questions/10469902/the-method-getpreferencemanager-is-undefined-for-the-type-batteryservice-in-an 

http://forum.xda-developers.com/xposed/xsharedpreferences-loaded-t2851158

**Comment by t0astt** [comment]
@rovo89 @StevenStanleyBayes I'm also running into this same exact issue... it's been throwing me for a loop for quite some time. Does this method still work in Lollipop (5.0.2 and 5.1.1)? I saw in the XDA thread someone mentioned that SELinux in Lollipop would likely break XSharedPreferences...

**Comment by rovo89** [comment]
I will close this now. If you're on 64-bit ROMs, Xposed v73 might solve the issue.
As mentioned above, `getPreferenceManager().setSharedPreferencesMode(MODE_WORLD_READABLE)` should be all that's necessary to make it work. It should _not_ be required to change the file permissions manually. Nor should you need to disable SELinux. If it still doesn't work for you, please send me a link to your source code, I don't have the time for guessing.

**Comment by yingshaoxo** [comment]
https://github.com/XF-zhjnc/CloudMusicXposed/blob/7cd8feb789ce3ea79bb2b744cc9b8092f4a2b130/app/src/main/java/cn/com/zhjnc/cloudmusicxposed/ui/SettingsFragment.java#L26

**It can be as simple as:**

1. in your activity, do this every time after configuring commitment:
```kotlin
    fun setWorldReadable() {
        val dataDir = File(this.getApplicationInfo().dataDir)
        val prefsDir = File(dataDir, "shared_prefs")
        val prefsFile = File(prefsDir, "main" + ".xml")
        if (prefsFile.exists()) {
            //Toast.makeText(this, prefsFile.path.toString(), Toast.LENGTH_LONG).show()
            for (file in arrayOf<File>(dataDir, prefsDir, prefsFile)) {
                file.setReadable(true, false)
                file.setExecutable(true, false)
            }
        }
    }
```
```kotlin
        global_switch.setOnCheckedChangeListener { _, isChecked ->
            with (sharedPref.edit()) {
                this.putBoolean("switch", isChecked)
                this.commit()
            }
            setWorldReadable()
        }
```

2. in your xposed java class:
```java
        XSharedPreferences pref = new XSharedPreferences(BuildConfig.APPLICATION_ID.toString(), "main");
```

That's it!
You don't have to use `pref.makeWorldReadable()` or `pref.reload`...
