### ISSUE TITLE
XSharedPreferences not working (64 bit only?)

### ISSUE THREAD

**Issue by rsteckler** [rovo89/XposedBridge#58]
I know there are a couple of other XSharedPreferences issues ( #36 and #56 ), but I'm not 100% confident they're related to this and wanted to provide details on what I'm seeing. 

**Background**
I've had a bunch of users complaining that my module (Amplify) isn't working for them.  We've narrowed it down to newer devices with 64bit processors and SELinux.  Those folks are running the experimental versions of Xposed from romracer, wanam, and hashbang173 on XDA.  

**Problem and my investigation**
In my activity code, I'm using:

``` java
SharedPreferences prefs = context.getSharedPreferences("com.ryansteckler.nlpunbounce" + "_preferences", Context.MODE_WORLD_READABLE);
SharedPreferences.Editor edit = prefs.edit();
edit.putString("file_version", Wakelocks.FILE_VERSION);
edit.apply();
```

This is correctly creating and writing the file, and I've verified that the file permissions are 644 (rw-r--r--).

In my Xposed code that hooks the "android" process, I use the following code:

``` java
m_prefs = new XSharedPreferences("com.ryansteckler.nlpunbounce");
m_prefs.reload();
String lastVersion = m_prefs.getString("file_version", "0");
```

At this point, getString always returns the default ("0").  I also see the following in logcat (which appears to happen on the .reload()):

```
W/XSharedPreferences( 2470): getSharedPreferences
W/XSharedPreferences( 2470): org.xmlpull.v1.XmlPullParserException: Unexpected token (position:unknown @1:5 in java.io.InputStreamReader@a1c51a7) 
W/XSharedPreferences( 2470):    at org.kxml2.io.KXmlParser.next(KXmlParser.java:428)
W/XSharedPreferences( 2470):    at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
W/XSharedPreferences( 2470):    at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java)
W/XSharedPreferences( 2470):    at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java)
W/XSharedPreferences( 2470):    at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:122)
W/XSharedPreferences( 2470):    at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:27)
W/XSharedPreferences( 2470):    at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:105)
```

I thought the "position:unknown @ 1:5" was interesting, so I asked a couple of folks having the problem for their pref files.  I opened them up in a hex editor to make sure there weren't any weird binary characters, but everything looks good.  Here's an example file:

``` xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="file_version">3</string>
</map>
```

I don't have a 64 bit device I can debug with, so this is all based on logs and help from my userbase.  I have dug into the code a little bit and suspect one of two things:
1)  XSharedPreferences is having a problem loading the stream ( [XSharedPreferences.java @ 120:60](https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/XSharedPreferences.java#L120) ).  If I had a 64 bit device to debug on, I assume I would see something wrong with the stream at that point.
2)  That might actually be caused by SELinuxHelper returning the wrong ServiceAppDataFile type ( [SELinuxHelper.java](https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/SELinuxHelper.java#L62-L68) ).  I saw something similar before when SELinux first came out and people were switching their SELinux mode on the fly after boot.  Since SELinuxHelper only checks the SELinux status once per process, it would fail if people changed the policy on the fly.  Not sure if that's related - if maybe the newer devices are switching on SELinux mode after Xposed boots or something.

Let me know how I can help.  Worst case, I'll go buy a 64 bit device so I can test locally, but I'm trying to avoid that until something comes out that I really want  :)

Thanks!
Ryan

**Comment by rovo89** [comment]
Thanks for all the details. I have the Nexus 9, so I'll do some tests. But it may take some time - I'm currently busy with other things.

**Comment by rsteckler** [comment]
I just bought a Nexus 9 to see if I can help fix this.  I'm not sure how to compile XposedBridge into the XposedBridgeApi-*.jar file that gets included in the project though.  I see you have XTools for the native side - can you point me in the right direction for compiling the bridge?  If I get it working, I'll repay the favor with a pull-request that fixes this issue.

Thanks!
Ryan

**Comment by rovo89** [comment]
> I just bought a Nexus 9 to see if I can help fix this.

Seems to be urgent for you. ;)

> I'm not sure how to compile XposedBridge into the XposedBridgeApi-*.jar file that gets included in the project though.

Note that the API jar isn't included in the module APK, the modules just reference it. So you don't need to rebuild it unless you want to add new APIs. If you want to do it anyway, you can use the file "jarexport.jardesc" in Eclipse.

As for compiling XposedBridge: You can compile the APK as any other app, just make sure not to install it directly onto your device. Then you rename the file to .jar and you're done. If you like, you can delete all the contents except for classes.dex from it, but that's not really required.

**Comment by rsteckler** [comment]
Oh, got it!  That totally makes sense now that you explain it.

Thanks for the rapid response on your weekend!

**Comment by romracer** [comment]
If you look at my XposedBridge fork, I added gradle support too.  You can build from the command line, use Android Studio or automate it.

**Comment by rsteckler** [comment]
Awesome.  I just cloned that and have it compiling.  Thanks for the help guys.  I'll followup with what I find.

**Comment by rsteckler** [comment]
Here's what I've found so far:
If you look at the stream at [line 122 in XSharedPreferences.java](https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/XSharedPreferences.java#L122) on a 64bit SELinux enforcing device, you'll see 4 bytes at the front of the stream.  They're all 0x00 when I've looked at it, but I'm not sure that would always be the case.  The stream also ends 4 bytes early.  For example, if the correct file was:
0x65 0x66 0x67 0x68 0x69
The file size would correctly show 5, but the contents of the file would be:
0x00 0x00 0x00 0x00 0x65

I changed the FileResult from using a stream to using content (i.e. using readFile instead of getFileInputStream), and I get the same result.

So where do the extra 4 bytes come from?  This is where I start to get in over my head  ;)

It looks like on SELinux devices, there's a Binder that connects to a service in the c++ code ("user.xposed.app").  In that c++ code there's a readFile that does some fancy file reading.  My guess is that somewhere between the code that actually reads the file and the different layers that marshall it back up the stack to the java side, there's a place where a 64bit int is being written, but a 32bit int is being read, which causes the offset of the file contents to be off by 4 bytes.

I'm a bit stuck here because I'm having a hard time following the file read request down the stack and the file contents back up the stack.  I also have an entirely new appreciate for the cleverness and work that went into Xposed and Xposed for SELinux.  Wow.  Really, WOW.

I'll keep looking, but I'm not sure I can make any more progress beyond this point.  Hopefully this helps you guys when you get around to this bug  :)

Thanks!
Ryan

**Comment by rsteckler** [comment]
[These lines](https://github.com/rovo89/Xposed/blob/master/xposed_service.cpp#L584-L589) look very suspicious

**Comment by romracer** [comment]
Hmm, interesting. I'm only on my phone right now but it seems curious that there is no writeInt32 for SDK>=21 while filling the parcel. The BpXposedService readFile method certainly reads a 32bit int into the file size when processing the parcel reply. I'd need to look at the C++ implementation for writeByteArray, maybe it's not necessary. It'd seem like that would never have worked though, regardless of platform. 

Or maybe writeByteArray is writing the size on its own as the first integer. If that's the case, and that integer is different sizes on 32 and 64 bit, that could explain it. Suppose that's a 64 bit integer on 64 bit platforms but we only read the first 4 bytes as a 32 bit integer, that sounds like what you suggested earlier.

If @rovo89 doesn't beat us to it, I'll look at the C implementation tomorrow. I don't have a 64 bit device to test though.

**Comment by rsteckler** [comment]
Here's some code I put in the java side in BinderService.java.  Start at line 119 and replace the parcel reads with this:

```
        Log.e("Amplify64", "Parcel begin read.  Position: " + new Integer(reply.dataPosition()).toString());
        Log.e("Amplify64", "Parcel begin read.  Size: " + new Integer(reply.dataSize()).toString());
        reply.readException();
        int errno = reply.readInt();
        Log.e("Amplify64", "Parcel read: " + new Integer(errno).toString() + " Position: " + new Integer(reply.dataPosition()).toString());

        String errorMsg = reply.readString();
        long size = reply.readLong();
        Log.e("Amplify64", "Parcel read: " + new Long(size).toString() + " Position: " + new Integer(reply.dataPosition()).toString());
        long time = reply.readLong();
        Log.e("Amplify64", "Parcel read: " + new Long(time).toString() + " Position: " + new Integer(reply.dataPosition()).toString());
//        int throwaway = reply.readInt();
//        Log.e("Amplify64", "Parcel read: " + new Integer(throwaway).toString() + " Position: " + new Integer(reply.dataPosition()).toString());
        byte[] content = reply.createByteArray();
        Log.e("Amplify64", "Parcel read finished. Position: " + new Integer(reply.dataPosition()).toString());
        reply.recycle();
        data.recycle();
```

The output is telling (for a 1155 length file on disk):

```
E/Amplify64(  651): Parcel begin read.  Position: 0
E/Amplify64(  651): Parcel begin read.  Size: 1196
E/Amplify64(  651): Parcel read: 0 Position: 8
E/Amplify64(  651): Parcel read: 1155 Position: 24
E/Amplify64(  651): Parcel read: 1441054730 Position: 32
E/Amplify64(  651): Parcel read finished. Position: 1192
```

You can see that the file stops 4 bytes short and everything looks good up until the byteArray (e.g. size and timestamp are good).  I also peeked into the byte values of the parcel at the location of the byte array.  It's a 32bits with the length of the array, then another 32 bits of zeroes (combined could be interpreted as a 64 bit int), then the array content.  This leads me to think that what's happening is somehow the writeByteArray on the c++ side is writing a 64bit length and the array.  On the java side, createByteArray is reading a 32bit length, then reading the byte array content.  I'm not sure how there would be a mis-match between the two, though.  Are you guys compiling the binder/parcel code in from the AOSP codebase?  There may be a needed #ifdef 64bit or something, requiring (unfortunately) a 32 and 64bit release of the C++ portions of Xposed.

Just some thoughts - hope they help.

**Comment by romracer** [comment]
The C++ implementation for Parcel is [here](https://android.googlesource.com/platform/frameworks/native/+/android-5.1.1_r13/libs/binder/Parcel.cpp).  You can see it writes a byte aligned length before writing the data.  len is of type size_t which is almost certainly 8 bytes on AArch64.  Since we pass a 32-bit integer, it looks like the size is padded.

On your 64-bit test build, you can add a line right after [this line](https://github.com/rovo89/Xposed/blob/master/xposed_service.cpp#L497) similar to:

```
            int32_t trash = reply.readInt32();
```

to skip those 32 bits.  I bet it works, but that'd obviously skip the first 4 bytes of valid data on a 32-bit device.

Alternately, you could try [this build](http://xenserver.underpants-gnomes.biz/~romracer/xposed-v71-sdk22-arm64-by-romracer-20150901.zip) which I have not tested but is hopefully 32/64-bit compatible.  That code isn't fully up to date with what @rovo89 released yesterday, but it should be good enough.

Let me know how it goes if you can!  Thanks.

**Comment by rsteckler** [comment]
I'll upgrade my nexus 9 to sdk22 and test it today.  Thanks!
Ryan

**Comment by gregferns** [comment]
HI guys,

Sorry to butt in ,,, but i've been following this thread... so i decided to try this build..
Before trying ,, i flashed a clean rom TIPSY OS on yuphoria (lettuce) (including wiping internal sd card) with rovo89's v72 build. used amplify 3.0.9 but it didnt work.
SO i cleant everything, again full wipe including internal sd and reflashed the rom, and then flashed this test build by romracer, but still no go with amplify....

Ryan, you'll have to try it like you said, and maybe with a test build of amplify....

Let me know if you require any logs etc...

Thanks,
Greg

**Comment by rsteckler** [comment]
Confirmed.  Same problem in this build.  
I'm surprised that the C++ implementation of parcel isn't the same as, or called by, the Java implementation.  I would imagine that this would show up anywhere parcels are marshalled/unmarshalled by any app on 64bit (OS and Google Apps included).

In any case, a "custom" implementation of writeByteArray (on the C++ side) and createByteArray (on the Java side) would solve this particular problem.  Quick pseudo code:
C++:

```
theParcel.writeInt32(fileSize);
theParcel.write(theBytes, fileSize); //internally uses memcpy, so that's good.
```

Java:

```
int filesize = theParcel.readInt32();
byte[] = new byte[filesize];
for (i = 0 to filesize) {
byte[i] = theParcel.readByte();
}
```

Obviously the Java isn't "fast", but if it's limited to XSharedPreferences, it's probably fast enough.

This all assumes there's not a "correct" fix that bridges the mismatch between the c++ implementation writing size_t and the java implementation assuming a 32bit int.

I'm happy to write the above if that's the solution, and shoot you the code for compilation/testing on 32 bit.

Let me know,
Ryan

**Comment by romracer** [comment]
Well, what you propose is already what happens when SDK<21.  I'm not sure why @rovo89 decided to use writeByteArray in Lollipop.  If it was the same regardless of SDK version, then it would work fine (because readInt32 and writeInt32 internally use read/writeAligned), so that would be the "easy" fix.

I simplified my changes a bit, without removing writeByteArray, into a [new build](http://xenserver.underpants-gnomes.biz/~romracer/xposed-v72-sdk22-arm64-by-romracer-20150901.zip).

**Comment by rsteckler** [comment]
Just checked and the new build doesn't seem to fix the problem.  I checked your commit history and didn't see changes there, so I'm assuming it was just a local build.  If you want to push it to a test branch, I'm happy to lend a second set of eyes.

On the c++ side, reverting back to the pre-lollipop code is (I think) the fix.  I [blamed the lollipop code](https://github.com/rovo89/Xposed/blame/master/xposed_service.cpp#L584-L589) and it was part of a really big commit that basically had all of the SELinux code in one package.  If @rovo89 remembers why that's in there, awesome.  If not, I think it should be removed because I can't imagine it could ever work on a 64 bit device unless the Java side starts expecting a 64bit int header to match.

**Comment by romracer** [comment]
Yes, sorry, I was not committing my test changes.  I tried to avoid changing the Java side but I guess I wasn't having much luck.

I also reviewed the commit history for xposed_service.cpp, but yes, its a massive Lollipop/ART related commit so there's no history as to why writeByteArray() is used.  I made an [arm](http://xenserver.underpants-gnomes.biz/~romracer/xposed-v72-sdk22-arm-by-romracer-20150901-2.zip) and [arm64](http://xenserver.underpants-gnomes.biz/~romracer/xposed-v72-sdk22-arm64-by-romracer-20150901-2.zip) build using writeInt32()/write() instead of writeByteArray.

They didn't seem to break my 32-bit devices.  Any luck on 64-bit with them?

**Comment by rsteckler** [comment]
Beautiful.  The new build works on 64 bit.  I don't see any side effects, and Amplify makes pretty extensive use of XSharedPreferences.

You're the man!  Thanks so much for the help.  I'll watch both of your XDA threads for an update that includes this fix, then let the Amplify users know.

Thanks!
Ryan
