### ISSUE TITLE
Method found but calling throws NoSuchMethodError

### ISSUE THREAD

**Issue by nick1212** [rovo89/XposedBridge#62]
When trying to call a method I get a NoSuchMethodError even though:
- "findMethodExact" successfully works
- and  class.getMethods also returns the method as
  (public com.android.internal.telephony.Call$State com.android.internal.telephony.Connection.getState())

I have tried multiple variations and inspecting Xposed modules open source code but nothing has worked so far.

I would appreciate it if someone could please hint me at what am I doing wrong.

METHOD BEING CALLED
Class: Connection
Method: Call.State getState()
http://androidxref.com/4.4.2_r2/xref/frameworks/opt/telephony/src/java/com/android/internal/telephony/Connection.java#174

METHOD BEING HOOKED
This occurs when hooking
Class: CallNotifier
Method: "ringAndNotifyOfIncomingCall"
http://androidxref.com/4.4.2_r2/xref/packages/services/Telephony/src/com/android/phone/CallNotifier.java#656

``` java
ConnectionCustomClass = XposedHelpers.findClass("com.android.internal.telephony.Connection", lpparam.classLoader);

// inside the private void beforeHookedMethod ...

if (!(Boolean) XposedHelpers.callStaticMethod(PhoneUtils, "isRealIncomingCall", XposedHelpers.callMethod(ConnectionCustomClass, "getState"))) {
    XposedBridge.log("not true");
} else {
    XposedBridge.log("true");
}
```

I have also tried unsuccessfully: 

``` java
callMethod(param, "getState")
callMethod(param.thisObject, "getState")
callMethod("com.android.internal.telephony.Connection", "getState")
```

Thank you for your attention.

**Comment by rovo89** [comment]
None of these will work. Think about it similar to normal Java code. You want to call an instance method `getState()` so you will need an instance of the `Connection` class.

`ConnectionCustomClass` is an instance of `Class`. 

`param` is an instance of `XC_MethodHook.MethodHookParam`. 

`param.thisObject` is an instance of `CallNotifier`. 

`"com.android.internal.telephony.Connection"` is an instance of `String`. 

It seems that the (first) parameter of `ringAndNotifyOfIncomingCall` is an instance of `Connection`, and it's the same instance that is used inside the original implementation, so try using `param.args[0]` instead.
