### ISSUE TITLE
Check Whether Xposed Module is Enabled

### ISSUE THREAD

**Issue by StevenStanleyBayes** [rovo89/XposedBridge#64]
I have tried to find a way to check whether the module has been enabled in the Modules of Xposed Installer but I have not found any information. 

Can this be done from an application? Is there any list anywhere? 

One of the ways is to write something in the error log and read this from the application. Can the error log be read from elsewhere? 

To find out whether the module is enabled is very important for applications to display a reminder and to adjust performance. Otherwise people may think an application does not work.

**Comment by wanam** [comment]
A self hook should do it, within your module App, create a method "isModuleEnabled" that returns "false" and hook it to return "true".

**Comment by StevenStanleyBayes** [comment]
Thanks. I would still prefer to get this info from, say, a file which keeps a list of all modules and their status. As mentioned, I can write some key word in the error log which may contain a date in ms. 

I would assume there is a list of the modules and I prefer this way in case possible. Otherwise, I would consider your advise.

**Comment by wanam** [comment]
Then you will have to support more than one modules list file location, and you may not have normal access to them.

**Comment by manvir-singh** [comment]
I do this in my xposed module. It also detects if the user hasn't soft rebooted. Take a look at the source code lines linked below.

Xposed method hook: https://github.com/Programming4life/SnapColors/blob/master/app/src/main/java/com/manvir/SnapColors/App.java#L255-L256
Settings Activity: https://github.com/Programming4life/SnapColors/blob/master/app/src/main/java/com/manvir/SnapColors/Settings.java#L369-L373
Method Used to get version active: https://github.com/Programming4life/SnapColors/blob/master/app/src/main/java/com/manvir/common/Util.java#L131-L133

**Comment by StevenStanleyBayes** [comment]
Thanks. Please, wait. I now try to do so in a separate Xposed class and may have some questions. I have not checked yet but are there any specific requirements on how to put more than one class in the Xposed_Init? I have put each of them in a new line, no any separators except for the new line. Is this OK?

**Comment by StevenStanleyBayes** [comment]
The manual has answered the xposed_init question : must be one class per line.

**Comment by StevenStanleyBayes** [comment]
Seems to work. Will now check whether I can have two methods in the Xposed class for two different classes where I have the check method. Please, wait. May have questions.

**Comment by StevenStanleyBayes** [comment]
Works with multiple methods in multiple classes. 

I have not tested whether multiple packages can be loaded in one Xposed class but I assume this to be so. Therefore, this approach can be used for communication from and Xposed class to the rest of the application by the use of global ( class ) variable in the Xposed class. Please, comment.

**Comment by rovo89** [comment]
The "hook your own app" approach is indeed a best practice, as it not only checks whether your module is activated, but also checks whether it's actually loaded (i.e. if the reboot was done, Xposed is not disabled etc.)

> Therefore, this approach can be used for communication from and Xposed class to the rest of the application by the use of global ( class ) variable in the Xposed class.

No, at least not how I assume you mean it. You can of course return more information to your app. But keep in mind that a "global" variable is only global within the same process. If you hook a method e.g. in the Facebook app and fill your "global" variable there, you won't see this value in your app because it's running in a different process which doesn't share the memory with the Facebook app.
fill your "global" variable in a hook

**Comment by StevenStanleyBayes** [comment]
Thanks. I meant I can make the method to return, say, - 1 in the application and to override this method in the Xposed module to return, say, 0, 1, 2, 3,etcetera, as per the variables in the Xposed module.

**Comment by StevenStanleyBayes** [comment]
I am not sure whether right or wrong but I  have noticed this behaviour :  when the module is updated and previously selected in the Xposed Installer but yet not restarted, some things, as for example the check method, may work, others may not. This is observed when shared preferences are used. Thus, the Xposed class returns true although device not restarted but other parts of the exposed class do not work until after a restart. 

This is ONLY when the module had been selected, was updated and the device was not restarted which is an unusual and incorrect combination yet people may firget to restart.

**Comment by manvir-singh** [comment]
In Android studio use `BuildConfig.VERSION_CODE` instead of using preferences etc. Reason being when you build your apk in android studio, android studio generates the `BuildConfig.class` based on your project. This class never changes dynamically its a `final` class with all the variables `static final`. Preferences or any other code that would be changed when the user updates the module that code isn't going to work correctly as you've found out. Just use `BuildConfig.VERSION_CODE` like I did and you'll be good to go.

**Comment by StevenStanleyBayes** [comment]
Thanks. I am OK. I am happy to know this does not happen in reality. 

I wonder, however, whether to make a file for each Xposed module im the XposedBridge folder with information whether checked or unchecked or one file for all with defoned entries may be a good idea. Similar to Windows. Other info can also be displayed. Must be application readable or world readable.

**Comment by manvir-singh** [comment]
You can also check to see if a module is enabled by reading `/data/data/de.robv.android.xposed.installer/conf/modules.list`. If the module is enabled `modules.list` I believe should contain the path to the apk of that module. Note: To be able to write/read to/from `modules.list` you need to be root.

**Comment by StevenStanleyBayes** [comment]
Thanks. For now, I will not do so but this is a great piece of information. 

What do you mean " to be root "?

**Comment by manvir-singh** [comment]
`modules.list` can only be written to by the app that created it(Xposed the app) or the user root. Only two things that can modify the file so you need to be root. If you don't know what the root user is google it :)

**Comment by StevenStanleyBayes** [comment]
Thanks. I thought you meant something in Xposed terms, some kind of a special Xposed root access. Thanks for the clarification.

**Comment by manvir-singh** [comment]
Your welcome.

**Comment by SalimMahdAlmas** [comment]
modules.list is deprecated now. But still the developers added new files called modules_activated.xml where we can get about the data

**Comment by rovo89** [comment]
@AndroidFire  I have no idea what you're talking about, modules.list is still actively used. But this is an internal implementation detail that is subject to change without notice. Nothing except the Xposed Installer and XposedBridge should read or write this file.

The recommended way to check whether your module is enabled was already mentioned above: Create a function in your app which returns "false" or 0 or something like that by default, then hook it from your module and make it return "true" or your app's version instead. Then you can call this method from your app to find out whether the module is working.

**Comment by zhiguicai** [comment]
You can for example use this to send the user to the module section if you find out that your module isn't active yet. The best way to find out is something like that:

Code:

// in your Activity, call it to find out the activation status
private static boolean isModuleActive() {
    return false;
}

// in handleLoadPackage()
if (lpparam.packageName.equals("your.package.name")) {
    // don't use YourActivity.class here
    findAndHookMethod("your.package.name.YourActivity", lpparam.classLoader,
            "isModuleActive", XC_MethodReplacement.returnConstant(true));
}
