### ISSUE TITLE
I found the hook for package can be disabled by app itself

### ISSUE THREAD

**Issue by liudongmiao** [rovo89/XposedBridge#67]
So, what's the principle for xposed?

Currently, the hook for package is running in the same process with the running package, and can be disabled by the app. So how do you think about this?

For the app developers, it's not safe for xposed to hook some method, specially for billing app. But I don't think the hook should be disabled absolutely by the app too.

**Comment by rovo89** [comment]
> the hook for package is running in the same process with the running package

This sentence doesn't make sense to me. A hook isn't something that can "run" - it's basically just code injection into the app, so it _has to_ run in the same process. Can you explain in more detail please?

**Comment by liudongmiao** [comment]
```java
            Class<?> clazz = Class.forName("de.robv.android.xposed.XposedBridge", false, ClassLoader.getSystemClassLoader());
            Field field = clazz.getDeclaredField("disableHooks");
            field.setAccessible(true);
            field.set(null, true);
```

Above codes can disable xposed.

**Comment by rovo89** [comment]
That's one of probably many ways. Any suggestions how you would prevent this?

**Comment by pylerSM** [comment]
Class.forName - if argv[0] is XposedBridge, throw Class not found exception?

**Comment by pylerSM** [comment]
I wrote really simple module which does what I said above and it works.
Maybe it could be part of framework?

**Comment by liudongmiao** [comment]
@rovo89 I have no suggestions. 
I suggest to use a copy for the `callbackSnapshot`, so that `invokeOriginalMethodNative` cannot change the value.

https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/XposedBridge.java#L628
https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/XposedBridge.java#L668

So, if the app developers disables xposed or replace the element in `callbackSnapshot`, the `afterHookedMethod` still be invoked, so it can be turn on by the module author.

@pylerSM please refer my codes carefully, you should use the system classloader, as 
```java
Class.forName("de.robv.android.xposed.XposedBridge", false, ClassLoader.getSystemClassLoader());
```
I have remove the codes from my xposed module: https://github.com/liudongmiao/ForceStopGB/commit/2a848b3
These codes can turn xposed off in the user space.

**Comment by rovo89** [comment]
I strongly recommend not to hook such central classes/functionality because it might interfere with Xposed's internals and might lead to performance issues (e.g. Class.forName() is used a lot for every single layout that is inflated). Besides that, this closes just one possible access vector, while it might have unforeseeable side-effects. So no, this is nothing for the framework, and I wouldn't even want this to be done by any module.

**Comment by pylerSM** [comment]
Okey, so you want leave it as is...
