### ISSUE TITLE
Miui

### ISSUE THREAD

**Issue by miumok98** [rovo89/XposedBridge#68]

**Comment by rovo89** [comment]
A bug report needs more than a one-word title.

**Comment by Soft-Man** [comment]
lg h410

[error.log.txt](https://github.com/rovo89/XposedBridge/files/39670/error.log.txt)

**Comment by Soft-Man** [comment]
[error.log (2).txt](https://github.com/rovo89/XposedBridge/files/39672/error.log.2.txt)
