### ISSUE TITLE
How to run xposed with apkprotect?

### ISSUE THREAD

**Issue by dingtang2008** [rovo89/XposedBridge#69]
Currently ,app encrypted with apk protect caused xposed init can not found XposedHookLoadPackage,thanks to give me some suggestions

**Comment by rovo89** [comment]
What's the exact error message?

Is "apk protect" something like ProGuard? What does it do? Does it touch the file in the assets folder? Does it obfuscate/rename classes?

**Comment by liudongmiao** [comment]
@dingtang2008 Do you mean for some protect methods mainly used in China?

If you cannot find the package name, it's hard to hook the package. And, xposed cannot do follow things:
- hook for native application, yes, some app use a wrapper from native application
- hook for Instrumentation.
- and some app which disables the hook from xposed. (I have found it and use it in my application).

And I think, you should provide the package to test.

**Comment by ElvisLabs** [comment]
@rovo89 It means some protect methods in dex file, same as liudongmiao mentioned ,application's dex file was encrypted and zygote can not parse the dex properly. Is there any special method to do this ?
Like change the app_process?

**Comment by ElvisLabs** [comment]
@liudongmiao  you are right, do you have any idea?

**Comment by rovo89** [comment]
You didn't give me any helpful details, so I can't help you. Provide at least a test file.

**Comment by liudongmiao** [comment]
@dingtang2008 As I said, please provide the package to test.  If you don't provide any package, please don't bother rovo89 or me. And, rovo89 should be working on the xposed for android 6.0.

And I has said, there are some methods for the app to disable hook from xposed, if you subscribed to this project, you should have seen it. (Yes, I have removed it.)

**Comment by ElvisLabs** [comment]
Pls download it ![test apk](https://cloud.githubusercontent.com/assets/650383/10968023/a184684e-83f9-11e5-9759-39f557b2dac1.png) ,and rename it  with suffix .apk.

**Comment by liudongmiao** [comment]
You can hjack it at `attachBaseContext` in the Application.

There are some projects like `zjdroid`, you can use it to find real activity.

**Comment by rovo89** [comment]
@liudongmiao I think he is trying to encrypt his module, not hook a protected app.

@dingtang2008 From a quick look at the file, it seems that this tool replaces classes.dex with a stub which uses native libraries to decrypt the original dex file. Your class name "com.e_vertise.dopa.phab7.Phab7" wasn't found in classes.dex, so I don't think I can/want to support modules with such protection.

**Comment by liudongmiao** [comment]
Yes, it's some module using application protect by 360 safe (a chinese company).

It stores the original classes.dex via symbol in the `libjiagu.so`, when the application is attached, it decrypts the original classes.dex, and then continue the normal process. I don't think xposed should support it too.

**Comment by lozn00** [comment]
@liudongmiao 你是中国人吗我发现爱加密 360  tenctent,加密 等都无法解决正常找到 入口。

**Comment by lozn00** [comment]
@liudongmiao apkprotect1.0 离线保护工具可以 但是 不支持android5.0以及以上。
