### ISSUE TITLE
LG H410

### ISSUE THREAD

**Issue by Soft-Man** [rovo89/XposedBridge#73]
[error.log.2.txt](https://github.com/rovo89/XposedBridge/files/39807/error.log.2.txt)

**Comment by rovo89** [comment]
@Soft-Man Stop spamming or I will block you!

**Comment by Soft-Man** [comment]
Sorry, did not want. ;-)
20 нояб. 2015 г. 10:21 пользователь "rovo89" notifications@github.com
написал:
