### ISSUE TITLE
Misleading documentation in IXposedHookCmdInit

### ISSUE THREAD

**Issue by apsun** [rovo89/XposedBridge#78]
From the Javadoc for `IXposedHookCmdInit`:

> Starting with Xposed's app_process version 55, this will not be called unless a special file (conf/enable_for_tools) is created in the data directory of the installer.

However, it seems that this is no longer the case, and the configuration file no longer has any effect:

``` C++
#if !defined(XPOSED_ENABLE_FOR_TOOLS)
    if (!zygote)
        return false;
#endif
```

I hope the Javadoc can be updated to reflect this change. Thanks.

**Comment by rovo89** [comment]
IXposedHookCmdInit is now removed from the API.
