### ISSUE TITLE
Update docs regarding xposedminversion

### ISSUE THREAD

**Issue by ahstro** [rovo89/XposedBridge#79]
The docs currently say this: [`The <version> from the file name is the one you insert as xposedminversion in the manifest.`](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial#xposedbridgeapijar)
This isn't really true since the `<version>` part of the filename is now a date.

**Comment by rovo89** [comment]
This isn't really how it's supposed to stay... The API should be properly created via Gradle and should then be uploaded to Bintray for better Gradle integration.

**Comment by rovo89** [comment]
This is obsolete now: http://forum.xda-developers.com/showpost.php?p=66179241&postcount=29
