### ISSUE TITLE
Is it possible to backport new function?

### ISSUE THREAD

**Issue by liudongmiao** [rovo89/XposedBridge#8]
Now, Xposed is mainly used in hook function. How can we add new function?
For example, there is an simple function `addAll` in `ArrayAdapter`.
Is it possible to provide such function through xposed mod?

**Comment by rovo89** [comment]
Who would call that method? Usually it doesn't exist.
But to keep the answer short: No, that's not possible.

**Comment by liudongmiao** [comment]
No one would call such method, but it would be easier for back-porting xposed modules.
Thanks.

**Comment by M1cha** [comment]
That would be interesting to fix ported system apps via xposed.
Do you mean it's not possible with the current API or not possible by concept?

**Comment by rovo89** [comment]
> Do you mean it's not possible with the current API or not possible by concept?

I don't think it's possible at all.

**Comment by M1cha** [comment]
could you explain it a little bit more? I know how the dex fileformat works, but I don't know how it looks in RAM and how methods are looked up.

**Comment by rovo89** [comment]
You would have to check the Dalvik source code if you want to know how it works in details, it's quite complex... But I can say that there are many steps involved in loaded the methods from the .dex file, preparing them for execution, looking them up when necessary etc. These structures can't be simply extended with more methods, there isn't enough space allocated. And even if someone found a way to do it, it would be very complicated and would break again with ART.

**Comment by M1cha** [comment]
in ART, the methods are linked on compile time instead of looking them up by name, right?
There it would be truly impossible then because the art compiler would raise methodnotfound exceptions.

**Comment by rovo89** [comment]
Yes. And even in Dalvik, there are tools like dexopt which optimize the code outside of the virtual machine, which might detect missing methods early.

**Comment by M1cha** [comment]
the only way would be to inject the dexloader to add methods before the code is actually loaded.
