### ISSUE TITLE
Xposed cannot hook into systemui on LG G4 Lollipop

### ISSUE THREAD

**Issue by baongoc124** [rovo89/XposedBridge#86]
By logging loaded packages in handleLoadPackage, I never found com.android.systemui so I cannot use any modules related to systemui. Here's the log if it helps.
http://pastebin.com/Jyp5EcTL

**Comment by rovo89** [comment]
Could you please post the code that you used for logging, just to be sure that we're talking about the same thing?

**Comment by baongoc124** [comment]
Of course. Here it is. http://pastebin.com/GFnLDfs3

**Comment by michyprima** [comment]
Which rom are you on? I can hook into sysyemui just fine with my own module.

**Comment by baongoc124** [comment]
Hi @michyprima, I'm on stock 5.1.1.  I installed xposed via flashfire. Maybe it's the problem?

**Comment by baongoc124** [comment]
Ok, so because I used Flashfire. I should have been set selinux to permissive before using FlashFire to flash Xposed. The first time I flashed Xposed THEN set to permissive, it doesn't work fully somehow. Flash it again when selinux is already set to permissive works great!
