### ISSUE TITLE
XSharedPreferences can't read shared preferences

### ISSUE THREAD

**Issue by AllanWang** [rovo89/XposedBridge#88]
This seems to be slightly different than issues [74](https://github.com/rovo89/XposedBridge/issues/74) and [56](https://github.com/rovo89/XposedBridge/issues/56).

At one point, my preferences did work and read correctly, but now it seems to have stopped. I believe I've done all that's required, including 

`getPreferenceManager().setSharedPreferencesMode(Context.MODE_WORLD_READABLE);`

Making sure that the path is correct, and even checking that the permissions are at 0664

I had my app log the preferences found at each reload, and it seems that it will only correctly read it when I launch my module. Anything before or after that will not return the preferences.

[Here is my code](https://github.com/asdfasdfvful/Material-Glass-Xposed/tree/master/XMaterialGlass/src/main/java/com/pitchedapps/material/glass/xposed); any help or ideas?

The files to look at are ThemePreferences and XMaterialGlass

**Comment by F43nd1r** [comment]
Your link is 404.

**Comment by AllanWang** [comment]
I've made my repo private. I tried loading my module on a secondary rom and it worked, so it's probably just some cache issue that is messing with my preferences. This is no longer an issue.

**Comment by AllanWang** [comment]
@F43nd1r 
 well... it seems like no more than one new build later, the preferences aren't sticking again. I've added you as a collaborator to my repo so you can check it out.

**Comment by F43nd1r** [comment]
@asdfasdfvful First, I don't think I have the knowledge to help you. I just wanted to give you a heads up, because an issue with a dead link is likely to be ignored.
Second, I don't see XMaterialGlass.

**Comment by AllanWang** [comment]
I've [open sourced](https://github.com/asdfasdfvful/Material-Glass-Xposed/tree/master/XMaterialGlass/src/main/java/com/pitchedapps/material/glass/xposed) it again.

And now all the files are currently separate under the themes folder. I will merge them again once the preferences actually work.

**Comment by AllanWang** [comment]
Once again, I believe it's fixed, and it was probably because XSharedPreferences wasn't working in debug mode for  me. As of now I'll stay open sourced so other people with this issue may see what I've done
