### ISSUE TITLE
Hook into libraries instead of application packages

### ISSUE THREAD

**Issue by phoenixbird357** [rovo89/XposedBridge#90]
How can I hook method of external libraries (like com.squareup.retrofit) used by some package?

For example : I want to inject my code in some method of com.squareup.retrofit.Retrofit class used as library by some package com.example.implementation.retrofit

**Comment by rovo89** [comment]
Hook the application (`handleLoadPackage`), look for `com.example.implementation.retrofit` and then hook the method as usual.

Library code isn't really external when compiled, it becomes a part of the app. There's no difference between library code and "normal" app code, hence you have to handle it in the same way. It also means that that you can't hook the initialization of a library, there is no such thing.
