### ISSUE TITLE
Check if package has the ressource before setting replacement

### ISSUE THREAD

**Issue by sylveon** [rovo89/XposedBridge#91]
Sorry for bothering, but I'd like to know how to check if the current package has the ressource that I try to replace before replacing it.

**Comment by rovo89** [comment]
You can use the standard Android method `Resources.getIdentifier()` for that. It will return 0 in case the resource wasn't found. Alternatively, you can call `XResources.setReplacement()` and catch the `Resources.NotFoundException`.

**Comment by sylveon** [comment]
So it will be something like that:

```
    @Override
    public void handleInitPackageResources(XC_InitPackageResources.InitPackageResourcesParam resparam) throws Throwable {
        XModuleResources modRes = XModuleResources.createInstance(MODULE_PATH, resparam.res);
        if (resparam.res.getIdentifier("ic_allapps", "drawable", "com.android.launcher3") != 0 ) {
        resparam.res.setReplacement("com.android.launcher3", "drawable", "ic_allapps", modRes.fwd(R.drawable.drawer));
        resparam.res.setReplacement("com.android.launcher3", "drawable", "ic_allapps_pressed", modRes.fwd(R.drawable.drawer_pressed));}
    }
```

Am I correct?

**Comment by rovo89** [comment]
Looks good to me. Whether you want to use this approach or catch the exception depends on your personal preference, it shouldn't make a difference performance-wise.
