### ISSUE TITLE
Empty module not loading

### ISSUE THREAD

**Issue by DVDAndroid** [rovo89/XposedBridge#95]
I've created a blank Xposed Module and I executed it on GenyMotion emulator SDK22, xposed v82, xposed installer (by dvdandroid)

It doesn't work, it gives a ClassNotFoundException

~~[log](https://github.com/DVDAndroid/xposed-test/blob/master/log.txt)
[class](https://github.com/DVDAndroid/xposed-test/blob/master/app/src/main/java/com/dvd/android/myapplication/XposedMod.java)
[apk](https://github.com/DVDAndroid/xposed-test/blob/master/app-debug.apk?raw=true)
[repo](https://github.com/DVDAndroid/xposed-test/)~~

**Comment by rovo89** [comment]
Have you already tried to decompile the APK to check whether the class is actually there? It might have been removed by ProGuard...

**Comment by DVDAndroid** [comment]
Yes, the class exist ([smali](https://github.com/DVDAndroid/xposed-test/blob/master/smali/com/dvd/android/myapplication/XposedMod.smali)) but no Xposed dependency

**Comment by DVDAndroid** [comment]
Downgraded Gradle version from 2.1.0 to 1.5.0
Now gives another error ([log2](https://github.com/DVDAndroid/xposed-test/blob/master/log2.txt)), present in another issue #94 

---

Edit:

Tried with Gradle 1.3.1: same error

**With Gradle 1.3.0 I have no more issues. All going well**

Thanks for the help :+1:

**Comment by rovo89** [comment]
When you say "Gradle version", I assume you don't mean the version of Gradle, but of the Android plugin for Gradle?

I have just tried the APK you linked to above - it worked flawlessly on Genymotion with Android 5.1 and 6.0. Can you still reproduce the issue by using the current plugin again?

**Comment by DVDAndroid** [comment]
Yes, I assume Android plugin for Gradle, editable in /build.gradle file

I created another blank xposed module and a new GenyMotion SDK 23 emulator.
By default, Android Studio sets Android plugin for Gradle to 2.1.0; executed module, rebooted emulator, ClassNotFoundException on path: DexPathList etc..
Changed version from 2.1.0 to 2.0.0: all going well
Changed version from 2.0.0 to 1.5.0: all going well

Now I remain with version 2.0.0

**Comment by rovo89** [comment]
I think I need to try and reproduce this, so I reopen the issue.

**Comment by Firefly1337** [comment]
I can confirm this issue, in a way.
Neither 2.1.0 nor 2.0.0 work for me (ClassNotFound, DexPathList etc), but 1.5.0 does. So I'm using that one for now.

**Comment by rovo89** [comment]
Could you please try to disable Instant Run in Android Studio?

**Comment by rovo89** [comment]
Xposed v85 warns you to disable Instant Run. That should fix it.
