### ISSUE TITLE
Resource Redirection does not support R.xml

### ISSUE THREAD

**Issue by KieronQuinn** [rovo89/XposedBridge#98]
I don't know if I'm misinterpreting what resource redirection can do and if this is actuallf a bug, and if that is the case feel free to close and ignore this

I created the Google Keyboard Custom Smilies (http://repo.xposed.info/module/com.quinny898.xposed.googlekeyboardcustomsmileys) module, which worked before the latest update by modifying an array and all was good

In the latest Google Keyboard update it changed, they now use XMLs in xml, such as "softkeys_body_smiley"

My code when attempting to redirect this XML is:
`resparam.res.setReplacement("com.google.android.inputmethod.latin", "xml", "softkeys_body_smiley", modRes.fwd(R.xml.softkeys_body_smiley));`
Where the redirected XML file is the one attached (it controls the columns of the keyboard's emoji section, I made it empty to test if it's working)
However that doesn't work, and prints no errors in the log. 

I also tried it with "softkeys_input_emoticon_latin", which is the list of emoticons which have a dedicated page, again with an empty XML, with the same result, no changes and no errors 

I know the module is loading because I set it to log when it handleInitPackageResources is run, and the logging works fine

I've also tried the usual recommendation of testing by editing the APK, but there's a signature check in Google Keyboard so that's not an option

Here's my full Java: http://pastebin.com/raw/JnMpkvPj
The XML files from the decompiled APK:
"softkeys_input_emoticon_latin": http://pastebin.com/raw/MaBuHYar
"softkeys_body_smiley": http://pastebin.com/raw/dYq5Y4rk
And the XML file which is the blank replacement:
"softkeys_body_smiley": http://pastebin.com/raw/1HmUjMKn

If you need anything else, I'll provide it

**Comment by rovo89** [comment]
I have tried the exact same code that you posted and I think it works fine:
![google_keyboard](https://cloud.githubusercontent.com/assets/1573299/15833735/56d3248e-2c28-11e6-9a5c-1c61751f1b01.png)

**Comment by austinliou** [comment]
@rovo89 I'm actually getting an empty emoticon and emoji palette like you are, but only when using the Material Light theme in the keyboard settings. Switching to Material Dark will show the emoticons normally, but they are unaffected by XML changes. This happens whether or not I have Xposed enabled, so I wonder if you are encountering the same thing.

This is on a Nexus 6P, with Google Keyboard 5.0.25.122319759-arm64-v8a.

**Comment by rovo89** [comment]
Sounds to me like the other theme simply uses other resources... Just try to replace the XML in the APK, if necessary nuking the signature check.
